// End-to-end: the Process wizard (Path B) authoring flow in a real browser.
// Drives the REAL UI against a running stack at BASE_URL (nginx proxying /api -> backend):
// create a definition, select it, add start/user/end steps, connect them with two flows,
// click Generate, and assert the server-generated SVG diagram renders with its shapes and
// the download buttons arm. Auth is the page's own development bootstrap (the app
// auto-logs-in with the dev admin token — see warehouse.js _ensureAuth), so no token
// plumbing is needed here. Mirrors the conventions of suggestions.spec.js.
const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


const BASE = process.env.BASE_URL || 'http://localhost:8080';
const MARK = `wz${Date.now()}`; // unique per run so assertions never collide with existing rows

// Non-admin identity for the viewer pass (the criteria concern roles): a
// role 'user' identity booted the production way — the token in the URL
// hash as #access_token=..., /api/auth/config and /api/auth/me mocked for
// that user — proves the wizard still renders while the admin-only
// create controls are absent.
const AUTH_CONFIG = { auth_mode: 'development' };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-250';

// Boot the page the production way for a given identity: /api/auth/config
// and /api/auth/me mocked for `me`, every other /api/** an empty list, and
// the token riding the URL hash fragment (#access_token=...).  The boot
// proves the token was picked up the production way: Auth.init() migrates
// it into sessionStorage and it arrives as the Authorization header on
// /api/auth/me.
async function bootAs(page, me, token, url) {
    const meAuthorizations = [];
    await page.unrouteAll();
    await page.route('**/api/**', (route) => {
        const request = route.request();
        const reqUrl = request.url();
        if (reqUrl.includes('/api/auth/config')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
        }
        if (reqUrl.includes('/api/auth/me')) {
            const auth = request.headers()['authorization'];
            if (auth) meAuthorizations.push(auth);
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    });
    await page.goto(url + '#access_token=' + encodeURIComponent(token));
    await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

test('250_ac_1_data_source', async ({ page }) => {
    await page.goto(BASE + '/studio.html?panel=wizard');  // wizard moved to the Studio (AIDW#264/#269)

    // The wizard section rendered and the module bound (containers exist; empties are
    // zero-height, so presence is asserted via attachment and the controls via visibility).
    await expect(page.locator('[data-testid="wizard-definitions"]')).toBeAttached();
    await expect(page.locator('[data-testid="wizard-steps"]')).toBeAttached();
    await expect(page.locator('[data-testid="wizard-flows"]')).toBeAttached();
    await expect(page.locator('[data-testid="wizard-svg"]')).toBeAttached();
    await expect(page.locator('#wizard-create-def-btn')).toBeVisible();
    await expect(page.locator('[data-testid="wizard-generate"]')).toBeVisible();

    // Create a definition and select its card.
    await page.fill('#wizard-def-name', `Demo process ${MARK}`);
    await page.fill('#wizard-def-key', `${MARK}_proc`);
    await page.click('#wizard-create-def-btn');
    const card = page.locator('#wizard-definitions .wizard-card', { hasText: MARK });
    await expect(card).toBeVisible();
    await card.click();

    // Three steps: start, user, end — distinct step keys.
    const steps = [
        { name: 'Start', key: `${MARK}_start`, ordinal: '1', type: 'start' },
        { name: 'Review', key: `${MARK}_review`, ordinal: '2', type: 'user' },
        { name: 'Done', key: `${MARK}_end`, ordinal: '3', type: 'end' },
    ];
    for (const s of steps) {
        await page.fill('#wizard-step-name', s.name);
        await page.fill('#wizard-step-key', s.key);
        await page.fill('#wizard-step-ordinal', s.ordinal);
        await page.selectOption('#wizard-step-type', s.type);
        await page.click('#wizard-create-step-btn');
        // the steps list refresh also rebuilds the flow selects — wait for the option
        await expect(page.locator(`#wizard-flow-source option[value="${s.key}"]`)).toBeAttached();
    }

    // Two flows: start -> user, user -> end.
    const flows = [
        { name: 'to review', key: `${MARK}_f1`, from: `${MARK}_start`, to: `${MARK}_review` },
        { name: 'to done', key: `${MARK}_f2`, from: `${MARK}_review`, to: `${MARK}_end` },
    ];
    for (const f of flows) {
        await page.fill('#wizard-flow-name', f.name);
        await page.fill('#wizard-flow-key', f.key);
        await page.selectOption('#wizard-flow-source', f.from);
        await page.selectOption('#wizard-flow-target', f.to);
        await page.click('#wizard-create-flow-btn');
        await expect(page.locator('#wizard-flows .wizard-row', { hasText: f.key })).toBeVisible();
    }

    // Generate: the server returns {process_key, bpmn_xml, svg}; the SVG lands inline.
    await page.click('[data-testid="wizard-generate"]');
    const svg = page.locator('[data-testid="wizard-svg"] svg');
    await expect(svg).toBeVisible({ timeout: 15000 });

    // One shape per step (rect/circle/polygon) — at least the three we authored.
    const shapeCount = await svg.locator('rect, circle, polygon').count();
    expect(shapeCount).toBeGreaterThanOrEqual(3);

    // The staged artifacts armed the download buttons.
    await expect(page.locator('#wizard-download-xml')).toBeEnabled();
    await expect(page.locator('#wizard-download-svg')).toBeEnabled();
});

test('250_ac_1_data_source (viewer)', async ({ page }) => {
    // Non-admin pass: boot the production way as a role 'user' identity
    // (the token in the URL hash) and prove the wizard tool still renders
    // while the admin-only controls are absent.
    await bootAs(page, VIEWER_ME, VIEWER_TOKEN, BASE + '/studio.html?panel=wizard');

    // The page renders for a non-admin: the Process wizard tool shows...
    await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Process wizard');
    await expect(page.locator('[data-testid="wizard-definitions"]')).toBeAttached();
    await expect(page.locator('[data-testid="wizard-generate"]')).toBeVisible();
    await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

    // ...with the admin-only controls absent: the wizard's create buttons
    // leave the DOM for a non-admin, the role-gated Feed keys nav item does
    // not survive, the Feed keys section is removed by its module, and the
    // admin-only source form is gone.
    await expect(page.locator('#wizard-create-def-btn')).toHaveCount(0);
    await expect(page.locator('#wizard-create-step-btn')).toHaveCount(0);
    await expect(page.locator('#wizard-create-flow-btn')).toHaveCount(0);
    await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
    await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('#source-form')).toHaveCount(0);
});
