'use strict';

// Proof for issue #767, AC-3 — the navigation/sidebar markup is defined
// ONCE and rendered into both Dashboards (app/index.html) and Studio
// (app/studio.html) without duplicated HTML.
//
// The sidebar's markup (brand, primary navigation, auth-status footer)
// lives exactly once in app/js/shell.js; the two pages carry only a
// placeholder-free, markup-free reference to the shell (a script tag + a
// body attribute) and both render the identical sidebar in a real browser.
//
//   V     non-admin pass (the criteria concern roles): a role 'user'
//         identity booted the production way (the token in the URL hash as
//         #access_token=..., /api/auth/config and /api/auth/me mocked for
//         that user) still renders both pages from the same single
//         definition, but with no admin-only control -- the role-gated
//         "Feed keys" nav item is absent from the sidebar

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


// Deterministically admin identity for the browser part: the shell's
// role gate only puts the admin-only Feed keys item back once
// /api/auth/me has settled on an admin, and /api/** is mocked so the
// proof does not depend on whichever environment serves the pages.
const AUTH_CONFIG = { auth_mode: 'development' };
const ADMIN_ME = { authenticated: true, user: { id: 1, username: 'admin', roles: ['admin'] } };

// The sidebar's navigation, in the AC's order — what both pages must render.
const NAV_LABELS = [
  'Dashboards',
  'Data sources',
  'Suggestions',
  'PII flags',
  'Process wizard',
  'Load sequences',
  'Data retention',
  'Ingestion',
  'Feed keys',
  'Audit history',
];

// Non-admin identity for the viewer pass: the shell's fail-closed role
// gate keeps the admin-only Feed keys item out of the DOM for this user.
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };

// Boot the page the production way for a given identity: /api/auth/config
// and /api/auth/me mocked for `me`, every other /api/** an empty list, and
// the token riding the URL hash fragment (#access_token=...).  The boot
// proves the token was picked up the production way: Auth.init() migrates
// it into sessionStorage and it arrives as the Authorization header on
// /api/auth/me.
async function bootAs(page, me, token, url = '/index.html') {
  const meAuthorizations = [];
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const reqUrl = request.url();
    if (reqUrl.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (reqUrl.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorizations.push(auth);
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
  await page.goto(url + '#access_token=' + encodeURIComponent(token));
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

test('767_ac_3_data_source', async ({ page }) => {
  await page.route('**/api/**', (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(ADMIN_ME) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  await page.goto('/');

  const raw = (path) =>
    page.evaluate(async (p) => {
      const res = await fetch(p, { cache: 'no-store' });
      return res.text();
    }, path);

  const indexRaw = await raw('index.html');
  const studioRaw = await raw('studio.html');
  const shellRaw = await raw('js/shell.js');

  // Markers that identify the sidebar's navigation markup: each occurs in
  // the shell module and in NEITHER page — the pages do not duplicate the
  // sidebar HTML, they let the single definition render it.
  for (const marker of [
    'data-nav="dashboards"',
    'data-nav-panel="sources"',
    'data-nav-panel="feedkeys"',
    'data-nav-panel="audit"',
    'aidw-sidebar',
    'aidw-nav-item',
  ]) {
    expect(indexRaw.split(marker).length - 1, 'index.html duplicates the sidebar markup: ' + marker).toBe(0);
    expect(studioRaw.split(marker).length - 1, 'studio.html duplicates the sidebar markup: ' + marker).toBe(0);
  }

  // The definition itself: exactly one occurrence of the nav item markup
  // in the shell module...
  expect(shellRaw.split('data-nav="dashboards"').length - 1).toBe(1);
  for (const panel of [
    'sources', 'suggestions', 'pii', 'wizard', 'sequences', 'retention', 'ingestion', 'feedkeys', 'audit',
  ]) {
    expect(shellRaw.split('data-nav-panel="' + panel + '"').length - 1, 'missing panel in the single definition: ' + panel).toBe(1);
  }
  // ...with the Feed keys item role-gated for admins.
  expect(/data-nav-panel="feedkeys"[^>]*data-requires-role="admin"/.test(shellRaw)).toBe(true);
  // and it is rendered into both pages from that one definition.
  for (const pageHtml of [indexRaw, studioRaw]) {
    expect(pageHtml).toContain('js/shell.js');
    expect(pageHtml).toMatch(/data-aidw-page="(dashboards|studio)"/);
  }
  expect(indexRaw).toContain('data-aidw-page="dashboards"');
  expect(studioRaw).toContain('data-aidw-page="studio"');

  // In a real browser, both pages render the same sidebar from the single
  // definition: same items, same order, same hrefs.
  const itemsOf = () =>
    page.evaluate(() =>
      Array.from(document.querySelectorAll('[data-testid="sidebar-nav"] > a')).map((a) => ({
        label: a.textContent.trim(),
        href: a.getAttribute('href'),
      })));

  await page.goto('/index.html');
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  // The role gate puts the gated item back once auth settles — wait for
  // it so the rendered shape is the full ten.
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toBeVisible();
  const dashboardsItems = await itemsOf();

  await page.goto('/studio.html');
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toBeVisible();
  const studioItems = await itemsOf();

  expect(studioItems).toEqual(dashboardsItems);
  expect(dashboardsItems.map((i) => i.label)).toEqual(NAV_LABELS);
  expect(dashboardsItems.map((i) => i.href)).toEqual([
    'index.html',
    'studio.html?panel=sources',
    'studio.html?panel=suggestions',
    'studio.html?panel=pii',
    'studio.html?panel=wizard',
    'studio.html?panel=sequences',
    'studio.html?panel=retention',
    'studio.html?panel=ingestion',
    'studio.html?panel=feedkeys',
    'studio.html?panel=audit',
  ]);
});

test('767_ac_3_data_source (viewer)', async ({ page }) => {
  // Non-admin pass: the criteria concern roles, so the proof also boots a
  // role 'user' identity the production way (the token in the URL hash as
  // #access_token=..., /api/auth/config and /api/auth/me mocked for that
  // user) and proves both pages still render from the same single sidebar
  // definition while the admin-only control is absent.
  await bootAs(page, VIEWER_ME, 'viewer-token-767', '/index.html');

  // Dashboards renders for a non-admin: the shell is up, the page content
  // is intact, and the signed-in user sits at the sidebar bottom...
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-page-title')).toHaveText('Dashboards');
  await expect(page.locator('[data-testid="dashboards"]')).toBeVisible();
  await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

  // ...with the admin-only control absent: the role-gated Feed keys item
  // leaves the DOM for a non-admin and no role-gated item survives.
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
  // The remaining nine items still render from the single definition, in
  // the AC's order.
  const navLabels = () =>
    page.evaluate(() =>
      Array.from(document.querySelectorAll('[data-testid="sidebar-nav"] > a')).map((a) => a.textContent.trim()));
  await expect(page.locator('[data-testid="sidebar-nav"] > .aidw-nav-item')).toHaveCount(9);
  const dashboardsLabels = await navLabels();
  expect(dashboardsLabels).toEqual(NAV_LABELS.filter((l) => l !== 'Feed keys'));

  // A full reload on Studio: the page still renders, the admin-only
  // control is still absent, and the same nine items come from the same
  // one definition.
  await page.goto('/studio.html#access_token=' + encodeURIComponent('viewer-token-767'));
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Data sources');
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="sidebar-nav"] > .aidw-nav-item')).toHaveCount(9);
  const studioLabels = await navLabels();
  expect(studioLabels).toEqual(NAV_LABELS.filter((l) => l !== 'Feed keys'));
  // Both pages rendered the identical sidebar from the single definition.
  expect(studioLabels).toEqual(dashboardsLabels);
});
