'use strict';

// Proof for issue #769, AC-3/AC-4 — the shell owns the visibility of
// the Studio's .wh-panel sections: for the shown tool the controller
// unhides the full panel container (the enclosing section.wh-panel),
// and for every other tool it hides the full container — no inactive
// tool header, layout, or inner [data-panel] content remains visible.
// Inactive panels stay invisible even if a panel's own CSS (or an
// inline style) sets an explicit display value.
//
// Identity  the criteria concern roles, so the proof also runs a
//   non-admin pass (role 'user') booted the production way: the token
//   in the URL hash (#access_token=...), /api/auth/config and
//   /api/auth/me mocked for that user, and the hash token reaching
//   /api/auth/me as a Bearer header while the page still renders with
//   the admin-only control absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { auth_mode: 'development' };
const ADMIN_ME = { authenticated: true, user: { id: 1, username: 'admin', roles: ['admin'] } };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-769ac4';

// Every Studio panel section, by the panel name the shell resolves.
const PANELS = [
  'sources', 'suggestions', 'pii', 'wizard',
  'sequences', 'sequence-runs', 'retention', 'ingestion', 'feedkeys', 'audit',
];

async function mockApi(page, me) {
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
}

// The enclosing section.wh-panel of a panel's data-panel marker, with
// its shell visibility state.
function sectionState(page, panel) {
  return page.evaluate((p) => {
    const el = document.querySelector('main.wh-main [data-panel="' + p + '"]');
    const section = el ? el.closest('section.wh-panel') : null;
    if (!section) return null;
    const cs = getComputedStyle(section);
    const r = section.getBoundingClientRect();
    return {
      present: true,
      hidden: section.hasAttribute('hidden'),
      display: cs.display,
      visible: cs.display !== 'none' && r.width > 0 && r.height > 0,
    };
  }, panel);
}

async function expectSectionHidden(page, panel) {
  await expect.poll(async () => sectionState(page, panel), { timeout: 10000 })
    .toMatchObject({ hidden: true, display: 'none', visible: false });
}

async function expectSectionShown(page, panel) {
  await expect.poll(async () => sectionState(page, panel), { timeout: 10000 })
    .toMatchObject({ hidden: false, visible: true });
}

test('769_ac_4_data_source', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await mockApi(page, ADMIN_ME);

  // Boot on the Process wizard: its full section.wh-panel is the only
  // visible container, and every other tool's full container is hidden
  // (no inactive header, layout, or inner [data-panel] content shows).
  await page.goto('/studio.html?panel=wizard');
  await expectSectionShown(page, 'wizard');
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Process wizard');
  for (const panel of PANELS.filter((p) => p !== 'wizard')) {
    await expectSectionHidden(page, panel);
  }

  // AC-4: the shell owns the visibility.  An explicit inline display on
  // an inactive section does not unhide it...
  await page.evaluate(() => {
    const el = document.querySelector('main.wh-main [data-panel="sources"]');
    el.closest('section.wh-panel').style.display = 'block';
  });
  await expectSectionHidden(page, 'sources');

  // ...and neither does a panel stylesheet with explicit display values
  // for the inactive sections.
  await page.addStyleTag({
    content:
      'main.wh-main > .wh-panel[data-panel="sources"] { display: block; }' +
      'main.wh-main > .wh-panel[data-panel="retention"] { display: flex; }',
  });
  await expectSectionHidden(page, 'sources');
  await expectSectionHidden(page, 'retention');
  // ...while the shown tool's container is untouched.
  await expectSectionShown(page, 'wizard');

  // The mechanism follows the tool: switching unhides Data sources'
  // full container and hides the wizard's again.
  await page.click('.aidw-nav-item[data-nav-panel="sources"]');
  await expectSectionShown(page, 'sources');
  await expectSectionHidden(page, 'wizard');
});

test('769_ac_4_data_source (viewer)', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });

  // Boot the page the production way for a role 'user' identity: the
  // token rides the URL hash (#access_token=...), /api/auth/config and
  // /api/auth/me are mocked for that user, and the hash token must
  // reach /api/auth/me as a Bearer header.
  const meAuthorizations = [];
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const url = request.url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorizations.push(auth);
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(VIEWER_ME) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // A role-hidden tool (Feed keys) named by ?panel= falls back to Data
  // sources; the page still renders for the non-admin...
  await page.goto('/studio.html?panel=feedkeys#access_token=' + encodeURIComponent(VIEWER_TOKEN));
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + VIEWER_TOKEN);
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Data sources');
  await expectSectionShown(page, 'sources');
  await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

  // ...with the admin-only controls absent: the role-gated Feed keys
  // nav item leaves the DOM, no role-gated sidebar item survives, the
  // Feed keys section is removed by its module, and the admin-only
  // source form is gone.
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('#source-form')).toHaveCount(0);

  // The shell's visibility still holds for an inactive tool: an
  // explicit inline display on the Suggestions section does not unhide
  // it.
  await page.evaluate(() => {
    const el = document.querySelector('main.wh-main [data-panel="suggestions"]');
    el.closest('section.wh-panel').style.display = 'block';
  });
  await expectSectionHidden(page, 'suggestions');
  await expectSectionShown(page, 'sources');
});
