// Served-app Playwright spec (no backend): the accepted suggestion lands on a dashboard.
// Every /api/** endpoint the page needs is mocked with page.route BEFORE page.goto, so the
// spec never creates data through the request fixture or a live API — it drives only the DOM:
// the suggestion card on /studio.html, its accept button, and the dashboard item on / rendered
// from the mocked dashboards and dashboard-items. The mocked GET /api/suggestions is stateful:
// after the POST to /api/suggestions/{id}/accept it no longer lists that id, because the inbox
// re-renders from that list after every action (Warehouse.accept calls refresh).
const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


const BASE = (process.env.BASE_URL || 'http://localhost:8080').replace(/\/+$/, '');
const TOKEN = 'dev-secret-token:admin';
const MARK = `FE-DASH-${Date.now()}`; // unique per run so assertions never collide

const SUGGESTION_ID = 'sug-572-dash';
const DASHBOARD_ID = 'dash-572';
const ITEM_ID = 'item-572-dash';
const TITLE = `${MARK} Orders by Region`;

async function installRoutes(page) {
    // Stateful suggestion inbox: starts with one card; accept/dismiss remove it from the list.
    const inbox = new Set([SUGGESTION_ID]);
    // Stateful dashboard-items: the item only appears after a genuine accept.
    const dashboardItems = [];

    await page.route(`${BASE}/api/suggestions`, (route) => {
        const ids = [...inbox];
        const body = ids.map((id) => ({
            id,
            name: TITLE,
            title: TITLE,
            item_type: 'bar',
            aggregation: 'count',
            status: 'suggested',
            strategy: 'schema-only',
            score: 0.55,
        }));
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
    });

    await page.route(`${BASE}/api/suggestions/${SUGGESTION_ID}/accept`, (route) => {
        inbox.delete(SUGGESTION_ID);
        dashboardItems.push({
            id: ITEM_ID,
            dashboard_id: DASHBOARD_ID,
            suggestion_id: SUGGESTION_ID,
            name: TITLE,
            title: TITLE,
            item_type: 'bar',
            aggregation: 'count',
        });
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: SUGGESTION_ID, status: 'accepted' }) });
    });

    await page.route(`${BASE}/api/suggestions/${SUGGESTION_ID}/dismiss`, (route) => {
        inbox.delete(SUGGESTION_ID);
        // Dismiss does NOT add the item to any dashboard.
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: SUGGESTION_ID, status: 'dismissed' }) });
    });

    await page.route(`${BASE}/api/dashboards`, (route) => {
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify([{ id: DASHBOARD_ID, name: 'Operations', title: 'Operations' }]),
        });
    });

    await page.route(`${BASE}/api/dashboard-items`, (route) => {
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(dashboardItems) });
    });

    // Item data endpoint: the chart fill resolves to a terminal state (a rendered KPI value).
    await page.route(`${BASE}/api/dashboard-items/${ITEM_ID}/data`, (route) => {
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ value: 42, label: 'Orders' }),
        });
    });
}

test('accepting a suggestion on the studio inbox lands the item on a dashboard', async ({ page }) => {
    await installRoutes(page);
    await page.addInitScript((t) => { window.sessionStorage.setItem('aicrm_token', t); }, TOKEN);

    // Act on the inbox on the studio page.
    await page.goto('/studio.html');
    const card = page.locator(`[data-testid="suggestion"][data-id="${SUGGESTION_ID}"]`);
    await expect(card).toBeVisible();
    await expect(card.getByText(TITLE)).toBeVisible();

    await card.locator('[data-action="accept"]').click();

    // The inbox re-renders from the (now empty) mocked list, so the card leaves the screen.
    await expect(page.locator(`[data-testid="suggestion"][data-id="${SUGGESTION_ID}"]`)).toHaveCount(0);

    // The accepted item is listed by the mocked dashboard-items and renders on the dashboard page.
    await page.goto('/');
    const item = page.locator('[data-testid="dashboard-item"]', { hasText: TITLE });
    await expect(item).toBeVisible();
    const chart = item.getByTestId('chart');
    await expect(chart).toBeVisible();

    // The fill must terminate: a rendered chart (svg / kpi / value list) or a non-empty
    // explanatory note — never left on the transient "Loading data…" placeholder.
    await expect
        .poll(async () => {
            if (await chart.locator('[data-testid="chart-svg"], [data-testid="chart-kpi"]').count()) {
                return 'rendered';
            }
            const notes = await chart.locator('[data-testid="chart-note"]').allTextContents();
            if (notes.length && notes[0].trim() && !notes[0].startsWith('Loading')) return 'note';
            return 'pending';
        }, { timeout: 10000 })
        .not.toBe('pending');
});
