const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue755 surgical', async ({ browser }) => {
    // --- Scenario 1: production auth, unauthenticated → token cleared, redirect to index.html ---
    const ctx1 = await browser.newContext();
    const page1 = await ctx1.newPage();

    // Stub /index.html so no index-page script can touch the token
    await page1.route('**/index.html', (route) => {
        route.fulfill({ status: 200, contentType: 'text/html', body: '<html><body></body></html>' });
    });

    // Single branching handler for all /api/** requests
    await page1.route('**/api/**', (route) => {
        const url = route.request().url();
        if (url.includes('/api/auth/config')) {
            return route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ authEnabled: true, authMode: 'production' }),
            });
        }
        if (url.includes('/api/auth/me')) {
            return route.fulfill({
                status: 401,
                contentType: 'application/json',
                body: JSON.stringify({ detail: 'Not authenticated' }),
            });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    });

    // Seed sessionStorage only on the first navigation (studio.html);
    // the flag prevents re-seeding when the page navigates to index.html.
    await page1.addInitScript(() => {
        if (!sessionStorage.getItem('_seeded_755')) {
            sessionStorage.setItem('aicrm_token', 'test-token-755');
            sessionStorage.setItem('_seeded_755', '1');
        }
    });

    await page1.goto('/studio.html');

    // Wait for the navigation to index.html triggered by the boot script
    await page1.waitForURL('**/index.html', { timeout: 5000 });

    // Assert the stored token was cleared before the redirect
    const token1 = await page1.evaluate(() => sessionStorage.getItem('aicrm_token'));
    expect(token1).toBeNull();

    await ctx1.close();

    // --- Scenario 2: development auth, unauthenticated → stays on studio.html, token not null ---
    const ctx2 = await browser.newContext();
    const page2 = await ctx2.newPage();

    await page2.route('**/api/**', (route) => {
        const url = route.request().url();
        if (url.includes('/api/auth/config')) {
            return route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
            });
        }
        if (url.includes('/api/auth/me')) {
            return route.fulfill({
                status: 401,
                contentType: 'application/json',
                body: JSON.stringify({ detail: 'Not authenticated' }),
            });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    });

    await page2.addInitScript(() => {
        sessionStorage.setItem('aicrm_token', 'test-token-755');
    });

    await page2.goto('/studio.html');

    // In dev mode the boot continues past the auth check and calls module inits,
    // which issue non-auth API requests. Wait for one to prove the boot proceeded.
    await page2.waitForRequest(
        (req) => {
            const u = req.url();
            return u.includes('/api/') && !u.includes('/api/auth/');
        },
        { timeout: 5000 }
    );

    // Assert the page did NOT navigate away from studio.html
    expect(page2.url()).toContain('/studio.html');

    // Assert the token is still present (dev auth may replace it with its own dev token)
    const token2 = await page2.evaluate(() => sessionStorage.getItem('aicrm_token'));
    expect(token2).not.toBeNull();

    await ctx2.close();
});
