const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue394 surgical', async ({ page }) => {
    await page.goto('/studio.html?panel=sequences');

    // Assert the new panel heading is visible on screen
    await expect(page.getByText('Run history')).toBeVisible();

    // Assert the module global was wired in by DOMContentLoaded init
    await page.waitForFunction(() => typeof window.SequenceRuns !== 'undefined');

    // Append a probe row element and click it to exercise the delegated handler.
    // With no backend, GET /sequence-runs fails and the handler renders an error div.
    const errorSelector = '[data-panel="sequence-runs"] [data-testid="runs-error"]';
    await page.evaluate(() => {
        const probe = document.createElement('div');
        probe.setAttribute('data-testid', 'sequence-row');
        probe.setAttribute('data-id', 'seq-probe');
        probe.textContent = 'probe';
        document.body.appendChild(probe);
        probe.click();
    });

    // The error div must appear inside the sequence-runs panel container
    const errorEl = await page.waitForSelector(errorSelector);
    expect(await errorEl.isVisible()).toBe(true);
    expect(await errorEl.textContent()).toContain('Could not load runs.');
});

// Non-admin identity for the viewer pass (the criteria concern roles): a
// role 'user' identity booted the production way — the token in the URL
// hash as #access_token=..., /api/auth/config and /api/auth/me mocked for
// that user — proves the tool still renders while the admin-only control
// is absent.
const AUTH_CONFIG = { auth_mode: 'development' };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-394';

// Boot the page the production way for a given identity: /api/auth/config
// and /api/auth/me mocked for `me`, one mocked load sequence with one run
// for it (every other /api/** an empty list), and the token riding the URL
// hash fragment (#access_token=...).  The boot proves the token was picked
// up the production way: Auth.init() migrates it into sessionStorage and
// it arrives as the Authorization header on /api/auth/me.
async function bootAs(page, me, token, url) {
    const meAuthorizations = [];
    await page.unrouteAll();
    await page.route('**/api/**', (route) => {
        const request = route.request();
        const reqUrl = request.url();
        if (reqUrl.includes('/api/auth/config')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
        }
        if (reqUrl.includes('/api/auth/me')) {
            const auth = request.headers()['authorization'];
            if (auth) meAuthorizations.push(auth);
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
        }
        if (reqUrl.includes('/api/load-sequences') && reqUrl.includes('/bpmn')) {
            return route.fulfill({ status: 404, contentType: 'application/json', body: JSON.stringify({ detail: 'Not found' }) });
        }
        if (reqUrl.includes('/api/load-sequences')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: 'seq-394', name: 'Seq 394' }]) });
        }
        if (reqUrl.includes('/api/sequence-runs')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: 'run-394', name: 'Run 1', sequence_id: 'seq-394', status: 'completed' }]) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    });
    await page.goto(url + '#access_token=' + encodeURIComponent(token));
    await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

test('issue394 surgical (viewer)', async ({ page }) => {
    // Non-admin pass: boot the production way as a role 'user' identity
    // (the token in the URL hash) and prove the tool still renders while
    // the admin-only control is absent.
    await bootAs(page, VIEWER_ME, VIEWER_TOKEN, '/studio.html?panel=sequences');

    // The page renders for a non-admin: Load sequences is one tool over two
    // sections, so both the list and the Run history section show...
    await expect(page.getByRole('heading', { name: 'Load sequences', exact: true })).toBeVisible();
    await expect(page.getByText('Run history')).toBeVisible();
    await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

    // ...and selecting a sequence renders its runs read-only.
    await page.locator('[data-testid="sequence-row"]').first().click();
    await expect(page.locator('[data-testid="run-row"]').first()).toBeVisible();
    await expect(page.locator('[data-panel="sequence-runs"]')).toContainText('Run 1');

    // The admin-only controls are absent: the Execute button is not
    // rendered for a non-admin, the create button is not rendered either,
    // the role-gated Feed keys nav item leaves the DOM, the Feed keys
    // section is removed by its module, and the admin-only source form is
    // gone.
    await expect(page.locator('[data-testid="sequence-execute"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="sequence-create"]')).toHaveCount(0);
    await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
    await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('#source-form')).toHaveCount(0);
});
