const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue762 surgical', async ({ browser }) => {
    // --- Test 1: production auth, unauthenticated → token cleared, redirect to index.html ---
    {
        const context = await browser.newContext();
        const page = await context.newPage();

        await page.route('**/*', (route) => {
            const url = route.request().url();
            if (url.includes('/api/auth/config')) {
                route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ authEnabled: true, authMode: 'production' }) });
            } else if (url.includes('/api/auth/me')) {
                route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ detail: 'Not authenticated' }) });
            } else if (url.includes('/api/')) {
                route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
            } else if (url.includes('/index.html')) {
                route.fulfill({ status: 200, contentType: 'text/html', body: '<html><body></body></html>' });
            } else {
                route.continue();
            }
        });

        // Seed sessionStorage on the same origin via the stubbed index.html (no scripts)
        await page.goto('/index.html');
        await page.evaluate(() => sessionStorage.setItem('aicrm_token', 'test-token-762'));

        // Load studio.html; boot script should clear token and redirect to index.html
        await page.goto('/studio.html');
        await page.waitForURL('**/index.html', { timeout: 5000 });

        const token = await page.evaluate(() => sessionStorage.getItem('aicrm_token'));
        expect(token).toBeNull();

        await context.close();
    }

    // --- Test 2: development auth, unauthenticated → stays on studio.html ---
    {
        const context = await browser.newContext();
        const page = await context.newPage();

        await page.route('**/*', (route) => {
            const url = route.request().url();
            if (url.includes('/api/auth/config')) {
                route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ authEnabled: true, authMode: 'development' }) });
            } else if (url.includes('/api/auth/me')) {
                route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ detail: 'Not authenticated' }) });
            } else if (url.includes('/api/')) {
                route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
            } else {
                route.continue();
            }
        });

        const authMePromise = page.waitForResponse('**/api/auth/me', { timeout: 5000 });
        await page.goto('/studio.html');
        await authMePromise;

        expect(page.url()).toContain('/studio.html');

        await context.close();
    }
});
