const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue570 surgical', async ({ page }) => {
    await page.route('/api/**', async (route) => {
        const url = route.request().url();
        const method = route.request().method();
        const path = new URL(url).pathname;

        if (path === '/api/dashboards' && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: 1, name: 'Test Dashboard', grid_columns: 12 }]) });
        }
        if (path === '/api/dashboard-items' && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: 1, dashboard_id: 1, title: 'My Chart', item_type: 'bar', position: 1 }]) });
        }
        if (path === '/api/dashboard-item-layouts' && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (path === '/api/dashboard-item-layouts' && method === 'POST') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: 1, dashboard_item_id: 1, name: 'layout', grid_col_start: 2, grid_col_span: 3, grid_row_span: 2 }) });
        }
        if (path.startsWith('/api/dashboard-item-layouts/') && method === 'PUT') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: 1, dashboard_item_id: 1, name: 'layout', grid_col_start: 2, grid_col_span: 3, grid_row_span: 2 }) });
        }
        if (path.startsWith('/api/dashboard-items/') && path.endsWith('/data') && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ series: [{ label: 'A', value: 10 }, { label: 'B', value: 20 }], item_type: 'bar', dimension: 'category', aggregation: 'sum', measure: 'amount', sample_size: 100, title: 'My Chart' }) });
        }
        if (path === '/api/suggestions' && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (path === '/api/pii-flags' && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (path === '/api/datasets' && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (path === '/api/discovered-fields' && method === 'GET') {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({}) });
    });

    await page.goto('/');

    // Wait for the initial chart to reach a terminal state (SVG visible)
    const initialChart = page.locator('[data-testid="chart"]').first();
    await expect(initialChart.locator('svg')).toBeVisible({ timeout: 5000 });

    // Click "Edit layout" on the first item
    await page.locator('[data-action="edit-layout"]').first().click();

    // Wait for the layout editor inputs to appear
    const colStartInput = page.locator('[data-testid="layout-col-start"]').first();
    await expect(colStartInput).toBeVisible({ timeout: 5000 });

    // Change a value
    await colStartInput.fill('2');

    // Click Save — triggers API POST, re-render, and _fillCharts
    await page.locator('[data-action="save-layout"]').first().click();

    // After save, the chart must reach a terminal state: SVG or chart-note, NOT "Loading data…"
    const chartAfterSave = page.locator('[data-testid="chart"]').first();
    await expect(chartAfterSave).not.toContainText('Loading data\u2026', { timeout: 5000 });
    const hasSvg = await chartAfterSave.locator('svg').count();
    const hasNote = await chartAfterSave.locator('[data-testid="chart-note"]').count();
    expect(hasSvg + hasNote).toBeGreaterThan(0);
});
