'use strict';

// Proof for issue #692 — Ingestion panel in app/studio.html.
//
// Boots /studio.html?panel=ingestion with /api/auth/config and /api/auth/me
// mocked and every other /api/** request mocked (two pipelines, one dataset,
// three runs across them, plus a failed GET /api/runs response for the
// selected pipeline), and proves:
//   AC-1  both pipelines render in a table with name, dataset name (the
//         dataset id when no dataset matches), change-capture pattern,
//         schedule and Enabled/Disabled; the empty-pipelines and
//         failed-pipelines texts appear for their mocked responses
//   AC-2  selecting a pipeline row marks it selected and shows, below the
//         table, only that pipeline's runs from GET /api/runs, newest
//         started_at first (runs without a started_at last), each with its
//         status, trigger, started and finished times, rows read, rows
//         written, rows suppressed and its error detail when there is one;
//         the placeholder, no-runs and failed-runs texts appear for their
//         mocked responses; nothing in the section mutates data
//   AC-3  the empty-pipelines, failed-pipelines, no-runs and failed-runs
//         texts each appear for their mocked responses (the failed-runs
//         text is "Could not load runs."), and the panel=ingestion deep
//         link boots the section into view
//   V     non-admin pass (the criteria concern roles): a role 'user'
//         identity booted the production way (the token in the URL hash as
//         #access_token=..., /api/auth/config and /api/auth/me mocked for
//         that user) still renders the panel, but with no admin-only
//         control -- no per-row "Run now", no Enabled/Disabled toggle, and
//         nothing in the panel carrying the admin role marker

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { auth_mode: 'development' };
const AUTH_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const USER_ME = {
  authenticated: true,
  user: { id: 9, username: 'user', roles: ['user'] },
};

// One dataset; both pipelines point at it, so the dataset NAME (not the id)
// must render in the Dataset cell.
const DATASETS = [
  {
    id: 'ds-orders',
    name: 'Orders',
    object_type: 'table',
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
];

const PIPELINES = [
  {
    id: 'pipe-1',
    name: 'Orders CDC',
    dataset_id: 'ds-orders',
    cdc_pattern: 'orders.*',
    schedule: '0 * * * *',
    is_enabled: true,
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
  {
    id: 'pipe-2',
    name: 'Orders delta',
    dataset_id: 'ds-orders',
    cdc_pattern: 'orders_delta',
    schedule: '0 4 * * *',
    is_enabled: false,
    created_at: '2026-09-02T00:00:00',
    updated_at: '2026-09-02T00:00:00',
  },
];

// Three runs across the two pipelines; deliberately NOT newest-first so the
// sort assertion is meaningful (run-2 is newer than run-1).
const RUNS = [
  {
    id: 'run-1',
    pipeline_id: 'pipe-1',
    name: 'Nightly load',
    status: 'completed',
    trigger: 'schedule',
    started_at: '2026-09-10T02:00:00',
    finished_at: '2026-09-10T02:05:00',
    rows_read: 5000,
    rows_written: 4800,
    rows_suppressed: 200,
    error_detail: null,
  },
  {
    id: 'run-2',
    pipeline_id: 'pipe-1',
    name: 'Manual load',
    status: 'failed',
    trigger: 'manual',
    started_at: '2026-09-20T02:00:00',
    finished_at: '2026-09-20T02:10:00',
    rows_read: 120,
    rows_written: 0,
    rows_suppressed: 0,
    error_detail: 'Connection refused by source',
  },
  {
    id: 'run-3',
    pipeline_id: 'pipe-2',
    name: 'Weekly delta',
    status: 'completed',
    trigger: 'schedule',
    started_at: '2026-10-01T02:00:00',
    finished_at: '2026-10-01T02:04:00',
    rows_read: 900,
    rows_written: 900,
    rows_suppressed: 0,
    error_detail: null,
  },
];

const API_ERROR = { detail: 'simulated backend failure' };

/**
 * Mock every /api/** request for upcoming page loads: auth endpoints fixed,
 * the dataset list fixed to the one dataset, the pipeline and run lists per
 * arguments, and every other API call an empty JSON array (the Studio boot
 * fetches many lists on startup).
 */
async function mockApi(page, pipelines, pipelinesStatus, runs, runsStatus) {
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_ME),
      });
    }
    if (url.includes('/api/pipelines')) {
      return route.fulfill({
        status: pipelinesStatus,
        contentType: 'application/json',
        body: JSON.stringify(pipelines),
      });
    }
    if (url.includes('/api/datasets')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(DATASETS),
      });
    }
    if (url.includes('/api/runs')) {
      return route.fulfill({
        status: runsStatus,
        contentType: 'application/json',
        body: JSON.stringify(runs),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
}

// Boot the page the production way for a given identity: the auth
// endpoints are mocked for `me`, the ingestion endpoints for PIPELINES,
// DATASETS and RUNS (every other /api/** an empty list), and the token
// rides the URL hash fragment (#access_token=...).  The boot proves the
// token was picked up the production way: Auth.init() migrates it into
// sessionStorage and it arrives as the Authorization header on
// /api/auth/me.
async function bootAs(page, me, token, url = '/studio.html?panel=ingestion') {
  const meAuthorizations = [];
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const reqUrl = request.url();
    if (reqUrl.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (reqUrl.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorizations.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(me),
      });
    }
    if (reqUrl.includes('/api/pipelines')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(PIPELINES),
      });
    }
    if (reqUrl.includes('/api/datasets')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(DATASETS),
      });
    }
    if (reqUrl.includes('/api/runs')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(RUNS),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
  await page.goto(url + '#access_token=' + encodeURIComponent(token));
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

test('issue692 freeform', async ({ page }) => {
  // Make the page taller than the viewport so the ingestion panel (the last
  // section) sits below the fold and a successful deep-link scroll is
  // observable.
  await page.addInitScript(() => {
    document.addEventListener('DOMContentLoaded', () => {
      document.body.style.minHeight = '3000px';
    });
  });

  // ------------------------------------------------------------------
  // Phase 1 — two pipelines, one dataset, three runs; deep link
  // ?panel=ingestion
  // ------------------------------------------------------------------
  await mockApi(page, PIPELINES, 200, RUNS, 200);
  await page.goto('/studio.html?panel=ingestion');

  // AC-1: the module is loaded from js/ingestion.js and its init() runs on
  // Studio boot. The AC mandates "a module that defines const Ingestion
  // with an init() called on Studio boot" — the rendered table below proves
  // init() fired on boot, because the proof never calls it itself.
  const scriptSrcs = await page.evaluate(() =>
    Array.from(document.scripts).map((script) => script.getAttribute('src'))
  );
  expect(
    scriptSrcs.some((src) => /(^|\/)(js\/ingestion\.js)$/.test(src || ''))
  ).toBe(true);
  const section = page.locator('section[data-panel="ingestion"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Ingestion');
  const pipelineTable = page.locator('[data-testid="ingestion-pipeline-table"]');
  await expect(pipelineTable).toBeVisible();

  const row1 = page.locator('[data-testid="ingestion-pipeline-row"][data-id="pipe-1"]');
  const row2 = page.locator('[data-testid="ingestion-pipeline-row"][data-id="pipe-2"]');
  await expect(row1).toBeVisible();
  await expect(row2).toBeVisible();

  // AC-1: both pipelines render with their fields and the dataset's name.
  await expect(row1.locator('td[data-testid="ingestion-pipeline-name"]')).toHaveText('Orders CDC');
  await expect(row1.locator('td[data-testid="ingestion-pipeline-dataset"]')).toHaveText('Orders');
  await expect(row1.locator('td[data-testid="ingestion-pipeline-cdc-pattern"]')).toHaveText('orders.*');
  await expect(row1.locator('td[data-testid="ingestion-pipeline-schedule"]')).toHaveText('0 * * * *');
  await expect(row1.locator('td[data-testid="ingestion-pipeline-enabled"]')).toHaveText('Enabled');

  await expect(row2.locator('td[data-testid="ingestion-pipeline-name"]')).toHaveText('Orders delta');
  await expect(row2.locator('td[data-testid="ingestion-pipeline-dataset"]')).toHaveText('Orders');
  await expect(row2.locator('td[data-testid="ingestion-pipeline-cdc-pattern"]')).toHaveText('orders_delta');
  await expect(row2.locator('td[data-testid="ingestion-pipeline-schedule"]')).toHaveText('0 4 * * *');
  await expect(row2.locator('td[data-testid="ingestion-pipeline-enabled"]')).toHaveText('Disabled');

  // AC-2: nothing selected yet -> runs area shows the placeholder.
  const runsArea = page.locator('[data-testid="ingestion-runs"]');
  await expect(runsArea).toHaveText('Select a pipeline to see its runs.');

  // Select pipe-2: row is marked selected, only its run is shown.
  await row2.click();
  await expect(row2).toHaveClass(/wh-ingestion-row-selected/);
  await expect(row2).toHaveAttribute('data-selected', 'true');
  await expect(row1).not.toHaveClass(/wh-ingestion-row-selected/);
  await expect(runsArea.locator('[data-testid="ingestion-run-row"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="ingestion-run-status"]')).toHaveText('completed');
  await expect(runsArea.locator('[data-testid="ingestion-run-trigger"]')).toHaveText('schedule');
  await expect(runsArea.locator('[data-testid="ingestion-run-started"]')).toHaveText('2026-10-01T02:00:00');
  await expect(runsArea.locator('[data-testid="ingestion-run-finished"]')).toHaveText('2026-10-01T02:04:00');
  await expect(runsArea.locator('[data-testid="ingestion-run-read"]')).toHaveText('Read: 900');
  await expect(runsArea.locator('[data-testid="ingestion-run-written"]')).toHaveText('Written: 900');
  await expect(runsArea.locator('[data-testid="ingestion-run-suppressed"]')).toHaveText('Suppressed: 0');
  await expect(runsArea.locator('[data-testid="ingestion-run-error"]')).toHaveCount(0);
  await expect(runsArea).not.toContainText('2026-09-10T02:00:00');
  await expect(runsArea).not.toContainText('2026-09-20T02:00:00');

  // Select pipe-1: its two runs, newest started_at first, error detail shown.
  await row1.click();
  await expect(row1).toHaveClass(/wh-ingestion-row-selected/);
  await expect(row2).not.toHaveClass(/wh-ingestion-row-selected/);
  await expect(runsArea.locator('[data-testid="ingestion-run-row"]')).toHaveCount(2);
  await expect(runsArea.locator('[data-testid="ingestion-run-started"]')).toHaveText([
    '2026-09-20T02:00:00',
    '2026-09-10T02:00:00',
  ]);
  await expect(runsArea.locator('[data-testid="ingestion-run-status"]')).toHaveText(['failed', 'completed']);
  await expect(runsArea.locator('[data-testid="ingestion-run-trigger"]')).toHaveText(['manual', 'schedule']);
  await expect(runsArea.locator('[data-testid="ingestion-run-finished"]')).toHaveText([
    '2026-09-20T02:10:00',
    '2026-09-10T02:05:00',
  ]);
  await expect(runsArea.locator('[data-testid="ingestion-run-read"]')).toHaveText(['Read: 120', 'Read: 5000']);
  await expect(runsArea.locator('[data-testid="ingestion-run-written"]')).toHaveText(['Written: 0', 'Written: 4800']);
  await expect(runsArea.locator('[data-testid="ingestion-run-suppressed"]')).toHaveText(['Suppressed: 0', 'Suppressed: 200']);
  await expect(runsArea.locator('[data-testid="ingestion-run-error"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="ingestion-run-error"]')).toHaveText('Connection refused by source');
  await expect(runsArea).not.toContainText('2026-10-01T02:00:00');

  // AC-3: the panel=ingestion deep link scrolled the section into view.
  await expect.poll(async () => page.evaluate(() => document.querySelector('[data-testid="main-content"]').scrollTop)).toBeGreaterThan(0);
  await expect.poll(async () =>
    page.evaluate(() => {
      const rect = document.querySelector('[data-panel="ingestion"]').getBoundingClientRect();
      return rect.top < window.innerHeight && rect.bottom > 0;
    })
  ).toBeTruthy();

  // ------------------------------------------------------------------
  // Phase 2 — no deep link, empty pipeline list
  // ------------------------------------------------------------------
  await mockApi(page, [], 200, RUNS, 200);
  await page.goto('/studio.html');
  await expect(page.locator('[data-testid="ingestion-pipelines-empty"]')).toHaveText('No pipelines yet.');
  // Without panel=ingestion nothing scrolls the page.
  expect(await page.evaluate(() => document.querySelector('[data-testid="main-content"]').scrollTop)).toBe(0);

  // ------------------------------------------------------------------
  // Phase 3 — failed pipelines request
  // ------------------------------------------------------------------
  await mockApi(page, API_ERROR, 500, RUNS, 200);
  await page.goto('/studio.html');
  await expect(page.locator('[data-testid="ingestion-pipelines-error"]')).toHaveText('Could not load pipelines.');

  // ------------------------------------------------------------------
  // Phase 4 — selected pipeline with no runs
  // ------------------------------------------------------------------
  await mockApi(page, [PIPELINES[0]], 200, [], 200);
  await page.goto('/studio.html');
  const loneRow = page.locator('[data-testid="ingestion-pipeline-row"][data-id="pipe-1"]');
  await expect(loneRow).toBeVisible();
  await loneRow.click();
  await expect(page.locator('[data-testid="ingestion-runs-empty"]')).toHaveText('No runs for this pipeline yet.');

  // ------------------------------------------------------------------
  // Phase 5 — failed runs request for the selected pipeline
  // ------------------------------------------------------------------
  await mockApi(page, [PIPELINES[0]], 200, API_ERROR, 500);
  await page.goto('/studio.html');
  const loneRow2 = page.locator('[data-testid="ingestion-pipeline-row"][data-id="pipe-1"]');
  await expect(loneRow2).toBeVisible();
  await loneRow2.click();
  await expect(page.locator('[data-testid="ingestion-runs-error"]')).toHaveText('Could not load runs.');

  // ------------------------------------------------------------------
  // Phase 6 — dataset id when no dataset matches, a run without
  // started_at sorts last, and hostile free text renders inert
  // ------------------------------------------------------------------
  const ghostPipeline = {
    id: 'pipe-ghost',
    name: '<img src=x onerror=window.__pwned=1> & "quoted"',
    dataset_id: 'ds-ghost',
    cdc_pattern: null,
    schedule: null,
    is_enabled: null,
  };
  const ghostRuns = [
    {
      id: 'run-ghost-1',
      pipeline_id: 'pipe-ghost',
      name: 'Dated load',
      status: 'completed',
      trigger: 'manual',
      started_at: '2026-10-02T00:00:00',
      finished_at: null,
      rows_read: null,
      rows_written: null,
      rows_suppressed: null,
      error_detail: '<b onclick=window.__errPwned=1>bold</b>',
    },
    {
      id: 'run-ghost-2',
      pipeline_id: 'pipe-ghost',
      name: 'Undated load',
      status: 'running',
      trigger: 'schedule',
      started_at: null,
      finished_at: null,
      rows_read: null,
      rows_written: null,
      rows_suppressed: null,
      error_detail: null,
    },
  ];
  await mockApi(page, [ghostPipeline], 200, ghostRuns, 200);
  await page.goto('/studio.html');

  const ghostRow = page.locator('[data-testid="ingestion-pipeline-row"][data-id="pipe-ghost"]');
  await expect(ghostRow).toBeVisible();
  // No dataset matches ds-ghost -> the dataset id itself renders.
  await expect(ghostRow.locator('td[data-testid="ingestion-pipeline-dataset"]')).toHaveText('ds-ghost');
  await expect(ghostRow.locator('td[data-testid="ingestion-pipeline-name"]')).toHaveText('<img src=x onerror=window.__pwned=1> & "quoted"');
  // null fields render empty instead of "null"/"undefined".
  await expect(ghostRow.locator('td[data-testid="ingestion-pipeline-cdc-pattern"]')).toHaveText('');
  await expect(ghostRow.locator('td[data-testid="ingestion-pipeline-schedule"]')).toHaveText('');

  await ghostRow.click();
  const ghostRunsArea = page.locator('[data-testid="ingestion-runs"]');
  await expect(ghostRunsArea.locator('[data-testid="ingestion-run-row"]')).toHaveCount(2);
  // The run without a started_at sorts after the dated run.
  await expect(ghostRunsArea.locator('[data-testid="ingestion-run-started"]')).toHaveText([
    '2026-10-02T00:00:00',
    '',
  ]);
  await expect(ghostRunsArea.locator('[data-testid="ingestion-run-status"]')).toHaveText(['completed', 'running']);
  // Error detail renders as inert text; null counts render empty.
  await expect(ghostRunsArea.locator('[data-testid="ingestion-run-error"]')).toHaveCount(1);
  await expect(ghostRunsArea.locator('[data-testid="ingestion-run-error"]')).toHaveText('<b onclick=window.__errPwned=1>bold</b>');
  await expect(ghostRunsArea.locator('[data-testid="ingestion-run-read"]')).toHaveText(['', '']);
  await expect(ghostRunsArea.locator('[data-testid="ingestion-run-finished"]')).toHaveText(['', '']);

  // Nothing executable was injected — the payloads render as text.
  expect(
    await page.evaluate(() => {
      const pwned = window.__pwned === 1 || window.__errPwned === 1;
      const injected = document.querySelector(
        '[data-panel="ingestion"] img, [data-panel="ingestion"] script, [data-panel="ingestion"] b[onclick]'
      );
      return pwned || injected !== null;
    })
  ).toBe(false);
});

test('issue692 freeform (viewer)', async ({ page }) => {
  // Non-admin pass: the criteria concern roles, so the proof also boots a
  // role 'user' identity the production way (the token in the URL hash as
  // #access_token=..., /api/auth/config and /api/auth/me mocked for that
  // user) and proves the panel still renders while no admin-only control
  // exists.
  await bootAs(page, USER_ME, 'user-token-692');

  const section = page.locator('section[data-panel="ingestion"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Ingestion');
  const pipelineTable = page.locator('[data-testid="ingestion-pipeline-table"]');
  await expect(pipelineTable).toBeVisible();
  const row1 = page.locator('[data-testid="ingestion-pipeline-row"][data-id="pipe-1"]');
  const row2 = page.locator('[data-testid="ingestion-pipeline-row"][data-id="pipe-2"]');
  await expect(row1).toBeVisible();
  await expect(row2).toBeVisible();
  await expect(row1.locator('td[data-testid="ingestion-pipeline-name"]')).toHaveText('Orders CDC');
  await expect(row2.locator('td[data-testid="ingestion-pipeline-name"]')).toHaveText('Orders delta');

  // No admin-only control is rendered for a non-admin: no "Run now"
  // button, no per-row Actions cell, no Enable/Disable toggle, and
  // nothing in the panel carries the admin role marker.
  await expect(page.locator('[data-testid="ingestion-run-now"]')).toHaveCount(0);
  await expect(page.locator('td[data-testid="ingestion-pipeline-actions"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="ingestion-enabled-toggle"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="ingestion"] [data-requires-role="admin"]')).toHaveCount(0);

  // The Enabled/Disabled cell holds only the state word -- the admin-only
  // toggle that would share it for admins is not there.
  await expect(row1.locator('td[data-testid="ingestion-pipeline-enabled"]')).toHaveText('Enabled');
  await expect(row1.locator('td[data-testid="ingestion-pipeline-enabled"] button')).toHaveCount(0);
  await expect(row2.locator('td[data-testid="ingestion-pipeline-enabled"]')).toHaveText('Disabled');
  await expect(row2.locator('td[data-testid="ingestion-pipeline-enabled"] button')).toHaveCount(0);

  // The panel still functions for the viewer: selecting a pipeline shows
  // its runs (read-only, no mutation control involved).
  await row2.click();
  await expect(page.locator('[data-testid="ingestion-runs"] [data-testid="ingestion-run-row"]')).toHaveCount(1);
  await expect(page.locator('[data-testid="ingestion-runs"] [data-testid="ingestion-run-status"]')).toHaveText('completed');
});
