const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue582 surgical', async ({ page }) => {
    // --- Boot as a non-admin (viewer) user ---
    await page.route('/api/**', async (route) => {
        const url = route.request().url();
        if (url.includes('/api/auth/config')) {
            return route.fulfill({
                status: 200, contentType: 'application/json',
                body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
            });
        }
        if (url.includes('/api/auth/me')) {
            return route.fulfill({
                status: 200, contentType: 'application/json',
                body: JSON.stringify({ authenticated: true, user: { username: 'viewer1', roles: ['viewer'] } }),
            });
        }
        if (url.includes('/api/sources')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (url.includes('/api/source-connections')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (url.includes('/api/datasets')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
    });

    await page.goto('/studio.html');

    // Wait until the sources list has rendered (proves Sources.init() completed)
    await page.waitForFunction(() => {
        const el = document.getElementById('sources');
        return el && el.innerHTML.trim().length > 0;
    }, null, { timeout: 10000 });

    // Non-admin: #source-form and #src-submit must be ABSENT from the DOM
    await expect(page.locator('#source-form')).toHaveCount(0);
    await expect(page.locator('#src-submit')).toHaveCount(0);

    // Read-only content (the sources list) still rendered
    const srcList = page.locator('#sources');
    await expect(srcList).toBeVisible();
    const listText = await srcList.textContent();
    expect(listText.length).toBeGreaterThan(0);

    // --- Boot as an admin user ---
    await page.route('/api/**', async (route) => {
        const url = route.request().url();
        if (url.includes('/api/auth/config')) {
            return route.fulfill({
                status: 200, contentType: 'application/json',
                body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
            });
        }
        if (url.includes('/api/auth/me')) {
            return route.fulfill({
                status: 200, contentType: 'application/json',
                body: JSON.stringify({ authenticated: true, user: { username: 'admin1', roles: ['admin'] } }),
            });
        }
        if (url.includes('/api/sources')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (url.includes('/api/source-connections')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        if (url.includes('/api/datasets')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
        }
        // Capture POST /sources to verify form still submits correctly
        const method = route.request().method();
        if (method === 'POST' && url.includes('/api/sources')) {
            return route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify({ id: 'src-1' }) });
        }
        if (method === 'POST' && url.includes('/api/source-connections')) {
            return route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify({ id: 'conn-1' }) });
        }
        if (method === 'POST' && url.includes('/api/odata-service-configs')) {
            return route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify({ id: 'cfg-1' }) });
        }
        if (method === 'POST' && url.includes('/discover')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ datasets_discovered: 1, fields_discovered: 5, suggestions_created: 2, pii_flags_created: 0 }) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
    });

    await page.goto('/studio.html');

    // Wait until the sources list has rendered again
    await page.waitForFunction(() => {
        const el = document.getElementById('sources');
        return el && el.innerHTML.trim().length > 0;
    }, null, { timeout: 10000 });

    // Admin: #source-form and #src-submit must be PRESENT in the DOM
    await expect(page.locator('#source-form')).toHaveCount(1);
    await expect(page.locator('#src-submit')).toHaveCount(1);
});
