const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue352 surgical', async ({ page }) => {
    // Establish an admin identity via mocked HTTP responses BEFORE the page boots.
    // The catch-all is registered FIRST so it never shadows the specific mocks below
    // (Playwright checks the most recently registered route first).
    await page.route('**/api/**', async (route) => {
        return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({}) });
    });

    await page.route('/api/auth/config', async (route) => {
        return route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
        });
    });

    await page.route('/api/auth/me', async (route) => {
        return route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                authenticated: true,
                user: { username: 'admin', sub: 'admin', roles: ['admin'] },
            }),
        });
    });

    await page.goto('/');

    // The page's own boot-time Auth.init() (via Warehouse._ensureAuth) consumes the mocked
    // /api/auth/me. Wait for that to resolve into an admin state before rendering anything.
    await page.waitForFunction(() => Auth.isAdmin() === true);

    const results = await page.evaluate(() => {
        const host1 = document.createElement('div');
        host1.style.cssText = 'position:absolute;left:0;top:0;width:1200px;';
        document.body.appendChild(host1);

        const d1 = { id: 'd1', name: 'D1', grid_columns: 8 };
        const items = [
            { id: 'i1', dashboard_id: 'd1', item_type: 'kpi', title: 'I1' },
            { id: 'i2', dashboard_id: 'd1', item_type: 'bar', title: 'I2' }
        ];
        const layouts = [{ dashboard_item_id: 'i1', grid_col_start: 3, grid_col_span: 4 }];

        host1.innerHTML = Warehouse.renderDashboards([d1], items, layouts, 'i1');

        const i1Tile = host1.querySelector('[data-testid="dashboard-item"][data-id="i1"]');
        const i2Tile = host1.querySelector('[data-testid="dashboard-item"][data-id="i2"]');

        const colStartInp = i1Tile.querySelector('[data-testid="layout-col-start"]');
        const colSpanInp = i1Tile.querySelector('[data-testid="layout-col-span"]');
        const rowSpanInp = i1Tile.querySelector('[data-testid="layout-row-span"]');

        const host2 = document.createElement('div');
        host2.style.cssText = 'position:absolute;left:0;top:0;width:1200px;';
        document.body.appendChild(host2);
        host2.innerHTML = Warehouse.renderDashboards([d1], items, layouts, null);
        const i2TileNoEdit = host2.querySelector('[data-testid="dashboard-item"][data-id="i2"]');

        const r2 = i2Tile.getBoundingClientRect();
        const r2n = i2TileNoEdit.getBoundingClientRect();
        const btns = host1.querySelectorAll('[data-action="edit-layout"]');
        const btnHeights = Array.from(btns).map(b => b.getBoundingClientRect().height);

        host1.remove();
        host2.remove();

        return {
            i1InputCount: i1Tile.querySelectorAll('input[data-testid]').length,
            i2InputCount: i2Tile.querySelectorAll('input[data-testid]').length,
            colStartVal: colStartInp.value,
            colSpanVal: colSpanInp.value,
            rowSpanVal: rowSpanInp.value,
            colStartMax: colStartInp.getAttribute('max'),
            colSpanMax: colSpanInp.getAttribute('max'),
            hasSaveBtn: !!i1Tile.querySelector('[data-action="save-layout"]'),
            hasCancelBtn: !!i1Tile.querySelector('[data-action="cancel-layout"]'),
            i2WidthEdit: r2.width,
            i2WidthNoEdit: r2n.width,
            editLayoutBtnCount: btns.length,
            btnHeights
        };
    });

    expect(results.editLayoutBtnCount).toBe(2);
    expect(results.btnHeights.every(h => h > 0)).toBe(true);
    expect(results.i1InputCount).toBe(3);
    expect(results.i2InputCount).toBe(0);
    expect(results.colStartVal).toBe('3');
    expect(results.colSpanVal).toBe('4');
    expect(results.rowSpanVal).toBe('1');
    expect(results.colStartMax).toBe('8');
    expect(results.colSpanMax).toBe('8');
    expect(results.hasSaveBtn).toBe(true);
    expect(results.hasCancelBtn).toBe(true);
    expect(Math.abs(results.i2WidthEdit - results.i2WidthNoEdit)).toBeLessThan(20);
});
