const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue412 freeform', async ({ page }) => {
  // Establish an admin identity via mocked HTTP responses BEFORE the page boots.
  // The catch-all is registered FIRST so it never shadows the specific mocks below
  // (Playwright checks the most recently registered route first).
  await page.route('**/api/**', async (route) => {
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({}) });
  });

  await page.route('/api/auth/config', async (route) => {
    return route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
    });
  });

  await page.route('/api/auth/me', async (route) => {
    return route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        authenticated: true,
        user: { username: 'admin', sub: 'admin', roles: ['admin'] },
      }),
    });
  });

  await page.goto('/');

  // The page's own boot-time Auth.init() (via Warehouse._ensureAuth) consumes the mocked
  // /api/auth/me. Wait for that to resolve into an admin state before rendering anything.
  await page.waitForFunction(() => Auth.isAdmin() === true);

  await page.addScriptTag({ url: '/js/sequences.js' });
  await page.waitForFunction(() => typeof window.Sequences !== 'undefined');

  const result = await page.evaluate(() => {
    const Sequences = window.Sequences;
    const hostDiv = document.createElement('div');

    // Test empty list rendering
    const emptyHtml = Sequences.renderList([]);
    hostDiv.innerHTML = emptyHtml;

    const createBtnEmpty = hostDiv.querySelector('[data-testid="sequence-create"]');
    const nameInputEmpty = hostDiv.querySelector('[data-testid="sequence-name-input"]');
    const emptyState = hostDiv.querySelector('[data-testid="sequences-empty"]');

    // Test list with two sequences rendering
    const seqs = [
      { id: 'seq-uuid-1', name: 'Sequence One' },
      { id: 'seq-uuid-2', name: 'Sequence Two' }
    ];
    const listHtml = Sequences.renderList(seqs);
    hostDiv.innerHTML = listHtml;

    const rows = hostDiv.querySelectorAll('[data-testid="sequence-row"]');
    const createBtnList = hostDiv.querySelector('[data-testid="sequence-create"]');

    const rowIds = Array.from(rows).map(r => r.getAttribute('data-id'));

    return {
      empty: {
        hasCreateButton: !!createBtnEmpty,
        createButtonText: createBtnEmpty ? createBtnEmpty.textContent : null,
        hasNameInput: !!nameInputEmpty,
        nameInputIsInputTag: nameInputEmpty && nameInputEmpty.tagName.toLowerCase() === 'input',
        hasEmptyState: !!emptyState,
        emptyStateText: emptyState ? emptyState.textContent : null,
      },
      list: {
        rowCount: rows.length,
        rowIds: rowIds,
        hasCreateButtonInList: !!createBtnList,
      }
    };
  });

  // Assertions for empty state
  expect(result.empty.hasCreateButton).toBe(true);
  expect(result.empty.createButtonText).toContain('Create sequence');
  expect(result.empty.hasNameInput).toBe(true);
  expect(result.empty.nameInputIsInputTag).toBe(true);
  expect(result.empty.hasEmptyState).toBe(true);
  expect(result.empty.emptyStateText).toContain('No load sequences yet.');

  // Assertions for list state
  expect(result.list.rowCount).toBe(2);
  expect(result.list.rowIds).toEqual(['seq-uuid-1', 'seq-uuid-2']);
  expect(result.list.hasCreateButtonInList).toBe(true);
});
