'use strict';

// Proof for issue #701 — creating and rotating feed keys in the Studio
// "Feed keys" panel (app/js/feed_keys.js).
//
// Boots /studio.html?panel=feedkeys as an admin (roles: ["admin"]) with
// every /api/** request mocked — the create (POST /api/feed-credentials)
// and rotate (POST /api/feed-credentials/<id>/rotate) endpoints included,
// the rotate response carrying the key test-key-0123456789 — and records
// every non-GET request.  It proves:
//   AC-1  when Auth.isAdmin() is true the section shows a "New feed key"
//         button carrying data-requires-role="admin"; it opens a form
//         with a required "Name" and an optional "Principal" text input;
//         saving sends POST /api/feed-credentials with name and principal
//         (null when empty) and then POST /api/feed-credentials/<new
//         id>/rotate for the id the create returned; the rotate response's
//         key appears in the box data-testid="feedkey-reveal" with the
//         text "Copy this key now. It will not be shown again." and a
//         "Done" button; "Done" removes the box and the key from the page
//         and the table reloads, showing only the new key prefix; the key
//         is never written to localStorage, sessionStorage, a cookie, the
//         URL or the console; an empty name shows "Name is required."
//         without sending a request; a failed create or rotate shows the
//         response's detail, or "Could not create the feed key." when
//         there is none; for a non-admin no "New feed key" button is
//         rendered
//   AC-2  for an admin each credential that is not revoked has an
//         "Issue new key" button carrying data-requires-role="admin";
//         clicking it shows "Issuing a new key stops the current key from
//         working." with "Confirm" and "Cancel"; "Confirm" sends
//         POST /api/feed-credentials/<id>/rotate and shows the returned
//         key in the same once-only reveal box; "Cancel" sends nothing
//   AC-3  this spec: records every POST and proves that creating a key
//         sends the create and then the rotate for the returned id, that
//         the reveal box shows the key, that after "Done" the key appears
//         nowhere in the page's text or attributes nor in localStorage or
//         sessionStorage, that an empty name sends nothing, that "Issue
//         new key" with "Cancel" sends nothing and with "Confirm" sends
//         one rotate for that credential, and that a user with
//         roles: ["viewer"] sees neither button
//   AC-4  the one-time plaintext key is not exposed in DOM attributes,
//         console logs or client-side network payloads: it appears in the
//         DOM only as the reveal box's text until "Done", and no request
//         body, cookie, storage value, URL or console line ever carries it
//   Defect  a failed create/rotate whose detail is a non-string value
//         (a number, a boolean) shows that detail stringified, not the
//         generic fallback, and a row whose key_prefix is the boolean
//         false renders "no key issued", never the text "false"
//   Identity  the criteria concern roles, so the proof also runs a
//         non-admin pass (role 'viewer') booted the production way: the
//         token in the URL hash (#access_token=...), /api/auth/config and
//         /api/auth/me mocked for that user, the hash token reaching
//         /api/auth/me as a Bearer header while the page still renders
//         with the admin-only controls absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const VIEWER_ME = {
  authenticated: true,
  user: { id: 9, username: 'viewer', roles: ['viewer'] },
};

const ROTATED_KEY = 'test-key-0123456789';
const ROTATED_PREFIX = ROTATED_KEY.slice(0, 8);

let meBody = ADMIN_ME;
let meAuthorization = [];
let writeRequests = []; // every non-GET/HEAD request: { method, url, body }
let listGets = [];      // every GET /api/feed-credentials url
let credentials = [];   // the in-memory list the mock serves
let createMode = 'ok';  // 'ok' | 'fail-detail' | 'fail-nodetail'
let rotateMode = 'ok';  // 'ok' | 'fail-detail' | 'fail-nodetail' | 'fail-nondetail' | 'fail-bool-detail'
let createCounter = 0;
let consoleLines = [];

function resetPhase() {
  meBody = ADMIN_ME;
  createMode = 'ok';
  rotateMode = 'ok';
  credentials = [];
  createCounter = 0;
}

test('issue701 freeform', async ({ page }) => {
  page.on('console', (msg) => {
    consoleLines.push(msg.text());
  });

  await page.route('**/api/**', async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    if (method !== 'GET' && method !== 'HEAD') {
      writeRequests.push({ method, url, body: request.postData() || '' });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorization.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (url.includes('/api/feed-credentials')) {
      if (method === 'GET') {
        listGets.push(url);
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(credentials),
        });
      }
      const rotateMatch = url.match(/\/api\/feed-credentials\/([^/?#]+)\/rotate$/);
      if (method === 'POST' && rotateMatch) {
        const id = decodeURIComponent(rotateMatch[1]);
        if (rotateMode === 'fail-detail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 'rotate blew up' }),
          });
        }
        if (rotateMode === 'fail-nodetail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({}),
          });
        }
        if (rotateMode === 'fail-nondetail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 418 }),
          });
        }
        if (rotateMode === 'fail-bool-detail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: false }),
          });
        }
        const cred = credentials.find((c) => c.id === id);
        if (!cred) {
          return route.fulfill({
            status: 404,
            contentType: 'application/json',
            body: JSON.stringify({ detail: "FeedCredential '" + id + "' not found." }),
          });
        }
        cred.key_prefix = ROTATED_PREFIX;
        cred.updated_at = '2026-10-07T12:00:00';
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({ ...cred, key: ROTATED_KEY }),
        });
      }
      if (method === 'POST') {
        if (createMode === 'fail-detail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 'create blew up' }),
          });
        }
        if (createMode === 'fail-nodetail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({}),
          });
        }
        let parsed = {};
        try {
          parsed = JSON.parse(request.postData() || '{}');
        } catch (e) {
          parsed = {};
        }
        createCounter += 1;
        const cred = {
          id: 'fc-new-' + createCounter,
          name: parsed.name === undefined || parsed.name === null ? null : parsed.name,
          principal: parsed.principal === undefined ? null : parsed.principal,
          key_prefix: null,
          revoked: false,
          created_at: '2026-10-07T11:00:00',
          updated_at: '2026-10-07T11:00:00',
        };
        credentials.push(cred);
        return route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify(cred),
        });
      }
      return route.fulfill({
        status: 403,
        contentType: 'application/json',
        body: JSON.stringify({ detail: 'no' }),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // The key must never live in storage, a cookie or the URL (checked at
  // every point the key exists, and again after "Done").
  const assertKeyNotInStorageCookiesUrl = async () => {
    const stored = await page.evaluate(() => {
      const out = [];
      for (const storage of [window.localStorage, window.sessionStorage]) {
        for (let i = 0; i < storage.length; i++) {
          const name = storage.key(i);
          out.push(name + '=' + storage.getItem(name));
        }
      }
      return out;
    });
    for (const entry of stored) {
      expect(entry, 'key material found in storage: ' + entry).not.toContain(ROTATED_KEY);
    }
    const cookies = await page.context().cookies();
    for (const cookie of cookies) {
      expect(cookie.value, 'key material found in cookie ' + cookie.name).not.toContain(ROTATED_KEY);
    }
    expect(page.url(), 'key material found in the URL: ' + page.url()).not.toContain(ROTATED_KEY);
  };

  // After "Done" the key is gone from the whole page: every text node and
  // every attribute (outerHTML serializes both).
  const assertKeyNotInPage = async () => {
    expect(
      await page.evaluate((k) => document.documentElement.outerHTML.includes(k), ROTATED_KEY),
      'key material still in the page after "Done"'
    ).toBe(false);
    await assertKeyNotInStorageCookiesUrl();
  };

  // ------------------------------------------------------------------
  // Phase 1 — admin, empty list: "New feed key" creates the credential,
  // rotates it, reveals the key once; "Done" removes it and the table
  // reloads showing only the new key prefix
  // ------------------------------------------------------------------
  resetPhase();
  writeRequests = [];
  listGets = [];
  await page.goto('/studio.html?panel=feedkeys');

  const section = page.locator('[data-panel="feedkeys"]');
  await expect(section).toBeVisible();
  await expect(section).toHaveAttribute('data-requires-role', 'admin');

  const newBtn = page.locator('[data-testid="feedkeys-new-btn"]');
  await expect(newBtn).toBeVisible();
  await expect(newBtn).toHaveAttribute('data-requires-role', 'admin');
  await expect(newBtn).toHaveText('New feed key');

  await expect(page.locator('[data-testid="feedkeys-empty"]')).toHaveText('No feed keys yet.');

  // the form opens with a required Name and an optional Principal input
  await newBtn.click();
  const form = page.locator('[data-testid="feedkeys-new-form"]');
  await expect(form).toBeVisible();
  const nameInput = page.locator('[data-testid="feedkeys-name-input"]');
  const principalInput = page.locator('[data-testid="feedkeys-principal-input"]');
  await expect(nameInput).toBeVisible();
  await expect(nameInput).toHaveAttribute('required', '');
  await expect(principalInput).toBeVisible();

  // an empty name shows "Name is required." and sends nothing
  await page.locator('[data-testid="feedkeys-save"]').click();
  const formError = page.locator('[data-testid="feedkeys-form-error"]');
  await expect(formError).toHaveText('Name is required.');
  expect(writeRequests).toHaveLength(0);

  // saving sends the create ...
  await nameInput.fill('BI export');
  await principalInput.fill('svc-bi');
  await page.locator('[data-testid="feedkeys-save"]').click();
  await expect.poll(() => writeRequests.length).toBe(2);
  expect(writeRequests[0].method).toBe('POST');
  expect(writeRequests[0].url.endsWith('/api/feed-credentials')).toBe(true);
  expect(JSON.parse(writeRequests[0].body)).toEqual({ name: 'BI export', principal: 'svc-bi' });
  // ... and then the rotate for the id the create returned
  expect(writeRequests[1].method).toBe('POST');
  expect(writeRequests[1].url.endsWith('/api/feed-credentials/fc-new-1/rotate')).toBe(true);

  // the reveal box shows the key exactly once, with the warning and Done
  const reveal = page.locator('[data-testid="feedkey-reveal"]');
  await expect(reveal).toHaveCount(1);
  await expect(reveal).toBeVisible();
  await expect(reveal.locator('[data-testid="feedkey-reveal-note"]')).toHaveText(
    'Copy this key now. It will not be shown again.'
  );
  await expect(reveal.locator('[data-testid="feedkey-reveal-key"]')).toHaveText(ROTATED_KEY);
  await expect(page.locator('[data-testid="feedkey-reveal-done"]')).toHaveText('Done');
  // the key is visible text in the box — and nowhere else yet
  await assertKeyNotInStorageCookiesUrl();

  // "Done" removes the box and the key from the page ...
  await page.locator('[data-testid="feedkey-reveal-done"]').click();
  await expect(reveal).toHaveCount(0);
  await assertKeyNotInPage();

  // ... and the table reloads, showing only the new key prefix
  await expect.poll(() => listGets.length).toBeGreaterThanOrEqual(2);
  const table = page.locator('[data-testid="feedkeys-table"]');
  await expect(table.locator('[data-testid="feedkeys-row"]')).toHaveCount(1);
  await expect(table.locator('[data-testid="feedkeys-name"]')).toHaveText('BI export');
  await expect(table.locator('[data-testid="feedkeys-principal"]')).toHaveText('svc-bi');
  await expect(table.locator('[data-testid="feedkeys-key"]')).toHaveText(ROTATED_PREFIX + '\u2026');
  await expect(table.locator('[data-testid="feedkeys-status"]')).toHaveText('Active');
  await assertKeyNotInPage();

  // ------------------------------------------------------------------
  // Phase 2 — admin, empty list: a failed create or rotate shows the
  // response's detail, or "Could not create the feed key." when there is
  // none, and never reveals a key
  // ------------------------------------------------------------------
  resetPhase();
  writeRequests = [];
  listGets = [];
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys');
  await newBtn.click();

  // create fails with a detail (Principal left empty -> null in the body)
  createMode = 'fail-detail';
  await nameInput.fill('First attempt');
  await page.locator('[data-testid="feedkeys-save"]').click();
  await expect(formError).toHaveText('create blew up');
  await expect(page.locator('[data-testid="feedkey-reveal"]')).toHaveCount(0);
  expect(writeRequests).toHaveLength(1);
  expect(writeRequests[0].url.endsWith('/api/feed-credentials')).toBe(true);
  expect(JSON.parse(writeRequests[0].body)).toEqual({ name: 'First attempt', principal: null });

  // create fails without a detail
  createMode = 'fail-nodetail';
  await nameInput.fill('Second attempt');
  await page.locator('[data-testid="feedkeys-save"]').click();
  await expect(formError).toHaveText('Could not create the feed key.');
  await expect(page.locator('[data-testid="feedkey-reveal"]')).toHaveCount(0);
  expect(writeRequests).toHaveLength(2);

  // the create succeeds but the rotate fails with a detail
  createMode = 'ok';
  rotateMode = 'fail-detail';
  await nameInput.fill('Third attempt');
  await page.locator('[data-testid="feedkeys-save"]').click();
  await expect(formError).toHaveText('rotate blew up');
  await expect(page.locator('[data-testid="feedkey-reveal"]')).toHaveCount(0);
  expect(writeRequests).toHaveLength(4);
  expect(writeRequests[2].url.endsWith('/api/feed-credentials')).toBe(true);
  expect(writeRequests[3].url.endsWith('/api/feed-credentials/fc-new-1/rotate')).toBe(true);

  // the create succeeds but the rotate fails without a detail
  rotateMode = 'fail-nodetail';
  await nameInput.fill('Fourth attempt');
  await page.locator('[data-testid="feedkeys-save"]').click();
  await expect(formError).toHaveText('Could not create the feed key.');
  await expect(page.locator('[data-testid="feedkey-reveal"]')).toHaveCount(0);
  expect(writeRequests).toHaveLength(6);
  expect(writeRequests[5].url.endsWith('/api/feed-credentials/fc-new-2/rotate')).toBe(true);

  // the create succeeds but the rotate fails with a non-string detail:
  // the value is surfaced as text (stringified), not dropped (review
  // defect) -- a number ...
  rotateMode = 'fail-nondetail';
  await nameInput.fill('Fifth attempt');
  await page.locator('[data-testid="feedkeys-save"]').click();
  await expect(formError).toHaveText('418');
  await expect(page.locator('[data-testid="feedkey-reveal"]')).toHaveCount(0);
  expect(writeRequests).toHaveLength(8);
  expect(writeRequests[6].url.endsWith('/api/feed-credentials')).toBe(true);
  expect(writeRequests[7].url.endsWith('/api/feed-credentials/fc-new-3/rotate')).toBe(true);

  // ... and a boolean detail is surfaced the same way
  rotateMode = 'fail-bool-detail';
  await nameInput.fill('Sixth attempt');
  await page.locator('[data-testid="feedkeys-save"]').click();
  await expect(formError).toHaveText('false');
  await expect(page.locator('[data-testid="feedkey-reveal"]')).toHaveCount(0);
  expect(writeRequests).toHaveLength(10);
  expect(writeRequests[9].url.endsWith('/api/feed-credentials/fc-new-4/rotate')).toBe(true);

  // ------------------------------------------------------------------
  // Phase 3 — admin, two active + two revoked credentials: "Issue new
  // key" only on the active rows; "Cancel" sends nothing; "Confirm"
  // sends one rotate and reveals the key; "Done" reloads the table
  // ------------------------------------------------------------------
  resetPhase();
  writeRequests = [];
  listGets = [];
  credentials = [
    {
      id: 'fc-1',
      name: 'BI export',
      principal: 'svc-bi',
      key_prefix: 'abcd1234',
      revoked: false,
      created_at: '2026-09-15T10:30:00',
      updated_at: '2026-09-15T10:30:00',
    },
    {
      id: 'fc-2',
      name: 'Legacy ETL',
      principal: null,
      key_prefix: null,
      revoked: true,
      created_at: '2026-07-01T08:00:00',
      updated_at: '2026-08-20T12:00:00',
    },
    {
      id: 'fc-3',
      name: 'Warehouse sync',
      principal: 'svc-warehouse',
      key_prefix: 'ffff2222',
      revoked: false,
      created_at: '2026-08-10T09:00:00',
      updated_at: '2026-08-10T09:00:00',
    },
    {
      id: 'fc-4',
      name: 'Odd prefix',
      principal: null,
      key_prefix: false,
      revoked: true,
      created_at: '2026-06-01T07:00:00',
      updated_at: '2026-06-01T07:00:00',
    },
  ];
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys');

  const rows = table.locator('[data-testid="feedkeys-row"]');
  await expect(rows).toHaveCount(4);
  const rowFirst = rows.first();
  const rowRevoked = rows.nth(1);
  const rowThird = rows.nth(2);
  const rowFourth = rows.last();
  await expect(rowFirst.locator('[data-testid="feedkeys-status"]')).toHaveText('Active');
  await expect(rowRevoked.locator('[data-testid="feedkeys-status"]')).toHaveText('Revoked');
  await expect(rowThird.locator('[data-testid="feedkeys-status"]')).toHaveText('Active');
  // a row whose key_prefix is the boolean false renders "no key issued",
  // never the text "false" (review defect)
  await expect(rowFourth.locator('[data-testid="feedkeys-status"]')).toHaveText('Revoked');
  await expect(rowFourth.locator('[data-testid="feedkeys-key"]')).toHaveText('no key issued');

  // every non-revoked credential has the button, the revoked one does not
  await expect(page.locator('[data-testid="feedkeys-rotate-btn"]')).toHaveCount(2);
  const rotateBtn = rowFirst.locator('[data-testid="feedkeys-rotate-btn"]');
  await expect(rotateBtn).toHaveCount(1);
  await expect(rotateBtn).toHaveAttribute('data-requires-role', 'admin');
  await expect(rotateBtn).toHaveText('Issue new key');
  await expect(rowThird.locator('[data-testid="feedkeys-rotate-btn"]')).toHaveCount(1);
  await expect(rowRevoked.locator('[data-testid="feedkeys-rotate-btn"]')).toHaveCount(0);

  // clicking it shows the warning with Confirm and Cancel
  await rotateBtn.click();
  const confirm = page.locator('[data-testid="feedkeys-rotate-confirm"]');
  await expect(confirm).toBeVisible();
  await expect(confirm).toContainText('Issuing a new key stops the current key from working.');
  await expect(page.locator('[data-testid="feedkeys-rotate-confirm-ok"]')).toHaveText('Confirm');
  await expect(page.locator('[data-testid="feedkeys-rotate-confirm-cancel"]')).toHaveText('Cancel');

  // "Cancel" sends nothing and restores the button
  await page.locator('[data-testid="feedkeys-rotate-confirm-cancel"]').click();
  await expect(confirm).toHaveCount(0);
  await expect(rotateBtn).toHaveCount(1);
  expect(writeRequests).toHaveLength(0);

  // a failed rotate (Confirm) shows the detail and restores the button
  const thirdBtn = rowThird.locator('[data-testid="feedkeys-rotate-btn"]');
  rotateMode = 'fail-detail';
  await thirdBtn.click();
  await page.locator('[data-testid="feedkeys-rotate-confirm-ok"]').click();
  await expect(formError).toHaveText('rotate blew up');
  await expect(page.locator('[data-testid="feedkey-reveal"]')).toHaveCount(0);
  await expect(thirdBtn).toHaveCount(1);
  expect(writeRequests).toHaveLength(1);
  expect(writeRequests[0].url.endsWith('/api/feed-credentials/fc-3/rotate')).toBe(true);

  // "Confirm" on the first credential sends exactly one rotate for it ...
  rotateMode = 'ok';
  await rotateBtn.click();
  await page.locator('[data-testid="feedkeys-rotate-confirm-ok"]').click();
  const reveal2 = page.locator('[data-testid="feedkey-reveal"]');
  await expect(reveal2).toHaveCount(1);
  await expect(reveal2.locator('[data-testid="feedkey-reveal-note"]')).toHaveText(
    'Copy this key now. It will not be shown again.'
  );
  await expect(reveal2.locator('[data-testid="feedkey-reveal-key"]')).toHaveText(ROTATED_KEY);
  expect(writeRequests.length).toBe(2);
  expect(writeRequests[1].method).toBe('POST');
  expect(writeRequests[1].url.endsWith('/api/feed-credentials/fc-1/rotate')).toBe(true);
  const fc1Rotates = writeRequests.filter((r) => r.url.includes('/api/feed-credentials/fc-1/rotate'));
  expect(fc1Rotates).toHaveLength(1);
  await assertKeyNotInStorageCookiesUrl();

  // ... and "Done" removes the key and reloads the table with the new
  // prefix on the rotated credential
  await page.locator('[data-testid="feedkey-reveal-done"]').click();
  await expect(reveal2).toHaveCount(0);
  await assertKeyNotInPage();
  await expect.poll(() => listGets.length).toBeGreaterThanOrEqual(2);
  await expect(rowFirst.locator('[data-testid="feedkeys-key"]')).toHaveText(
    ROTATED_PREFIX + '\u2026'
  );
  await expect(rowRevoked.locator('[data-testid="feedkeys-key"]')).toHaveText('no key issued');
  await expect(rowThird.locator('[data-testid="feedkeys-key"]')).toHaveText('ffff2222\u2026');
  await expect(rowFourth.locator('[data-testid="feedkeys-key"]')).toHaveText('no key issued');

  // ------------------------------------------------------------------
  // Phase 4 — identity: a user with roles: ["viewer"] booted the
  // production way (token in the URL hash, /api/auth/config and
  // /api/auth/me mocked for that user) sees the page render with neither
  // admin button, and no request reaches /api/feed-credentials
  // ------------------------------------------------------------------
  resetPhase();
  meBody = VIEWER_ME;
  writeRequests = [];
  listGets = [];
  meAuthorization = [];
  // A fragment-only URL change would be a same-document navigation and
  // Auth.init() would not re-run; go through about:blank so this boot is
  // a full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys#access_token=viewer-token-701');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer viewer-token-701');
  // the page still renders its other panels ...
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policies-empty"]')).toHaveText(
    'No retention policies yet.'
  );
  // ... but the admin-only controls are absent: the whole section (and
  // with it the "New feed key" and "Issue new key" buttons) is gone
  await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'New feed key' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Issue new key' })).toHaveCount(0);
  // and no request reached /api/feed-credentials
  expect(listGets).toHaveLength(0);
  expect(writeRequests).toHaveLength(0);

  // ------------------------------------------------------------------
  // AC-4 — the one-time key never reached the console or any network
  // payload in any phase
  // ------------------------------------------------------------------
  for (const line of consoleLines) {
    expect(line, 'key material found in a console line: ' + line).not.toContain(ROTATED_KEY);
  }
  for (const req of writeRequests) {
    expect(req.body, 'key material found in the request to ' + req.url).not.toContain(ROTATED_KEY);
  }
});
