'use strict';

// Proof for issue #729 — admin management of retention policies in
// app/js/retention.js (add + delete), on top of the read-only panel of
// issue #689.
//
// Boots /studio.html?panel=retention the production way (the token in the
// URL hash, #access_token=...; /api/auth/config and /api/auth/me mocked)
// as an admin, with /api/datasets (two datasets) and
// /api/retention-policies mocked, and records every POST and DELETE. It
// proves:
//   AC-1  the section shows an "Add policy" button carrying
//         data-requires-role="admin"; clicking it shows the form
//         data-testid="retention-policy-form" with the mandated fields —
//         name (text, required), table class (select of connection_tests,
//         runs, discovery_runs, ingested_records, field_profiles), action
//         (select of purge/anonymize), retention period in days (number,
//         required, minimum 1), scope (select of class/dataset), dataset
//         (select from GET /api/datasets, name as the label and id as the
//         value, shown only when scope is dataset) and an Enabled checkbox
//         checked by default. Saving a dataset-scoped policy posts
//         POST /api/retention-policies with exactly name, table_class,
//         action, retention_period_days (a number), scope, dataset_id (the
//         chosen dataset's id) and is_enabled, closes the form and reloads
//         the table; a class-scoped policy posts dataset_id null; an empty
//         name or a period below 1 shows the form error without sending a
//         request; a 422 with a detail shows that detail and a failure
//         without one shows "Could not save the policy.", both with the
//         form still open; a failed GET /api/datasets keeps the form
//         usable for scope=class, disables the dataset select, and a
//         scope=dataset save shows "Could not load datasets." without
//         sending a request
//   AC-2  every admin policy row has a "Delete" button carrying
//         data-requires-role="admin"; clicking it replaces the button with
//         "Delete <policy name>?" plus "Confirm delete" and "Cancel";
//         Confirm sends exactly one DELETE /api/retention-policies/<id>
//         and reloads the table; Cancel restores the row unchanged and
//         sends no request; a failed delete shows "Could not delete the
//         policy." in the row; clicking Delete or its confirmation never
//         selects the row
//   AC-4  hostile policy names, dataset option labels, the API detail and
//         the delete confirmation text all render as inert text
//   Identity  after a full reload booted with #access_token=... for a
//         roles: ["viewer"] user (auth config + me mocked for that user),
//         the page still renders and neither the "Add policy" button nor
//         any "Delete" button is present

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const VIEWER_ME = {
  authenticated: true,
  user: { id: 7, username: 'viewer', roles: ['viewer'] },
};

// Two datasets; the second carries a hostile name (AC-4: the option label
// must render as inert text, and its id must ride along in the POST body).
const DATASETS = [
  {
    id: 'ds-orders',
    name: 'Orders',
    object_type: 'table',
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
  {
    id: 'ds-audit',
    name: 'Audit <log> & "exports"',
    object_type: 'table',
    created_at: '2026-09-02T00:00:00',
    updated_at: '2026-09-02T00:00:00',
  },
];

// Hostile free text (AC-4): markup + quotes in a policy name must render
// as inert text in the table cell and in the delete confirmation.
const HOSTILE_POLICY_NAME = 'Purge <img src=x> & "stale" rows';

test('issue729 freeform', async ({ page }) => {
  const postRequests = [];
  const deleteRequests = [];
  const meAuthorization = [];
  let authMeBody = ADMIN_ME;
  let policiesStatus = 200;
  let policiesBody = null; // null -> the live policy list
  let datasetsStatus = 200;
  let datasetsBody = DATASETS;
  let createPolicy = { status: 201, body: null }; // null body -> derive from the payload
  let deletePolicyStatus = 204;

  // Live policy list the mocked GET/POST/DELETE operate on, so the table
  // reload after an add/delete is observable (new row appears, deleted
  // row disappears).
  const policies = [
    {
      id: 'pol-1',
      name: 'Purge stale audit rows',
      dataset_id: 'ds-audit',
      table_class: 'connection_tests',
      action: 'purge',
      retention_period_days: 30,
      scope: 'class',
      is_enabled: true,
      created_at: '2026-09-01T00:00:00',
      updated_at: '2026-09-01T00:00:00',
    },
    {
      id: 'pol-del',
      name: HOSTILE_POLICY_NAME,
      dataset_id: null,
      table_class: 'runs',
      action: 'anonymize',
      retention_period_days: 14,
      scope: 'class',
      is_enabled: false,
      created_at: '2026-09-02T00:00:00',
      updated_at: '2026-09-02T00:00:00',
    },
  ];

  const json = (route, status, body) =>
    route.fulfill({
      status,
      contentType: 'application/json',
      body: body === null ? '' : JSON.stringify(body),
    });

  // Every /api/** request is mocked; every POST and DELETE is recorded.
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();

    if (method === 'POST') postRequests.push({ url, body: request.postData() });
    if (method === 'DELETE') deleteRequests.push({ url });

    if (url.includes('/api/auth/config')) return json(route, 200, AUTH_CONFIG);
    if (url.includes('/api/auth/me')) {
      meAuthorization.push(request.headers()['authorization'] || null);
      return json(route, 200, authMeBody);
    }
    if (url.includes('/api/datasets')) return json(route, datasetsStatus, datasetsBody);

    if (method === 'GET' && /\/api\/retention-policies(\?|$)/.test(url)) {
      return json(route, policiesStatus, policiesBody !== null ? policiesBody : policies);
    }
    if (method === 'POST' && /\/api\/retention-policies(\?|$)/.test(url)) {
      if (createPolicy.status !== 201) {
        return json(route, createPolicy.status, createPolicy.body);
      }
      const payload = JSON.parse(request.postData() || '{}');
      const created = {
        id: 'pol-new-' + postRequests.length,
        name: payload.name,
        dataset_id: payload.dataset_id,
        table_class: payload.table_class,
        action: payload.action,
        retention_period_days: payload.retention_period_days,
        scope: payload.scope,
        is_enabled: payload.is_enabled,
        created_at: '2026-10-01T00:00:00',
        updated_at: '2026-10-01T00:00:00',
      };
      policies.push(created);
      return json(route, 201, created);
    }
    if (method === 'DELETE' && /\/api\/retention-policies\/[^/?#]+/.test(url)) {
      const id = decodeURIComponent(
        url.split('/api/retention-policies/')[1].split(/[/?#]/)[0]
      );
      if (deletePolicyStatus !== 204) {
        return json(route, deletePolicyStatus, { detail: 'simulated delete failure' });
      }
      const idx = policies.findIndex((p) => String(p.id) === String(id));
      if (idx !== -1) policies.splice(idx, 1);
      return json(route, 204, null);
    }
    return json(route, 200, []);
  });

  // ------------------------------------------------------------------
  // Phase 1 — admin boot (production way: token in the URL hash)
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=retention#access_token=dev-secret-token:admin');

  const section = page.locator('section[data-panel="retention"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Data retention');
  // The hash token was adopted: /auth/me carried it as the Bearer token.
  await expect.poll(() => meAuthorization[meAuthorization.length - 1]).toBe(
    'Bearer dev-secret-token:admin'
  );

  // AC-1: the section shows the "Add policy" button, marked admin-only.
  const addPolicy = page.locator('[data-testid="retention-add-policy"]');
  await expect(addPolicy).toHaveCount(1);
  await expect(addPolicy).toBeVisible();
  await expect(addPolicy).toHaveText('Add policy');
  await expect(addPolicy).toHaveAttribute('data-requires-role', 'admin');

  const table = page.locator('[data-testid="retention-policy-table"]');
  await expect(table).toBeVisible();
  const rowDel = page.locator('[data-testid="retention-policy-row"][data-id="pol-del"]');
  await expect(rowDel).toBeVisible();

  // AC-2: every policy row carries the "Delete" button, marked admin-only.
  const rows = page.locator('[data-testid="retention-policy-row"]');
  await expect(rows).toHaveCount(2);
  for (let i = 0; i < 2; i++) {
    const del = rows.nth(i).locator('[data-testid="retention-policy-delete"]');
    await expect(del).toHaveCount(1);
    await expect(del).toHaveText('Delete');
    await expect(del).toHaveAttribute('data-requires-role', 'admin');
  }
  // AC-4: the hostile policy name renders as inert text in the table cell.
  await expect(rowDel.locator('td[data-testid="retention-policy-name"]')).toHaveText(HOSTILE_POLICY_NAME);
  await expect(rowDel.locator('img, script')).toHaveCount(0);

  // ------------------------------------------------------------------
  // Phase 2 — the form and its fields
  // ------------------------------------------------------------------
  await addPolicy.click();
  const form = page.locator('[data-testid="retention-policy-form"]');
  await expect(form).toBeVisible();

  // name: a text input, required.
  const formName = form.locator('[data-testid="retention-form-name"]');
  await expect(formName).toHaveAttribute('type', 'text');
  await expect(formName).toHaveAttribute('required');
  // table class: the five mandated options (labels and values).
  const formTableClass = form.locator('[data-testid="retention-form-table-class"]');
  expect(
    await formTableClass.locator('option').evaluateAll((opts) => opts.map((o) => [o.value, o.textContent]))
  ).toEqual([
    ['connection_tests', 'connection_tests'],
    ['runs', 'runs'],
    ['discovery_runs', 'discovery_runs'],
    ['ingested_records', 'ingested_records'],
    ['field_profiles', 'field_profiles'],
  ]);
  // action: purge / anonymize.
  const formAction = form.locator('[data-testid="retention-form-action"]');
  expect(
    await formAction.locator('option').evaluateAll((opts) => opts.map((o) => [o.value, o.textContent]))
  ).toEqual([
    ['purge', 'purge'],
    ['anonymize', 'anonymize'],
  ]);
  // retention period: a number input, required, minimum 1.
  const formPeriod = form.locator('[data-testid="retention-form-period"]');
  await expect(formPeriod).toHaveAttribute('type', 'number');
  await expect(formPeriod).toHaveAttribute('required');
  await expect(formPeriod).toHaveAttribute('min', '1');
  // scope: class / dataset.
  const formScope = form.locator('[data-testid="retention-form-scope"]');
  expect(
    await formScope.locator('option').evaluateAll((opts) => opts.map((o) => [o.value, o.textContent]))
  ).toEqual([
    ['class', 'class'],
    ['dataset', 'dataset'],
  ]);
  // Enabled checkbox, checked by default.
  await expect(form.locator('[data-testid="retention-form-enabled"]')).toBeChecked();
  // the form error element exists and is empty before any save.
  const formError = form.locator('[data-testid="retention-form-error"]');
  await expect(formError).toHaveText('');

  // dataset: hidden while scope is class (the default)...
  const datasetField = form.locator('[data-testid="retention-form-field-dataset"]');
  const datasetSelect = form.locator('[data-testid="retention-form-dataset"]');
  await expect(datasetField).toBeHidden();
  // ...shown for scope=dataset, filled from GET /api/datasets — each
  // dataset's name as the label, its id as the value.
  await formScope.selectOption('dataset');
  await expect(datasetField).toBeVisible();
  await expect(datasetSelect).toBeEnabled();
  // wait for GET /api/datasets to have filled the select ...
  await expect(datasetSelect.locator('option')).toHaveCount(2);
  expect(
    await datasetSelect.locator('option').evaluateAll((opts) => opts.map((o) => [o.value, o.textContent]))
  ).toEqual([
    ['ds-orders', 'Orders'],
    ['ds-audit', 'Audit <log> & "exports"'],
  ]);
  // AC-4: the hostile label rendered as inert text (escaped, not parsed).
  const auditOption = datasetSelect.locator('option[value="ds-audit"]');
  await expect(auditOption).toHaveText('Audit <log> & "exports"');
  // back to class hides it again.
  await formScope.selectOption('class');
  await expect(datasetField).toBeHidden();

  // ------------------------------------------------------------------
  // Phase 3 — add a dataset-scoped policy: the exact POST payload
  // ------------------------------------------------------------------
  await formScope.selectOption('dataset');
  await datasetSelect.selectOption('ds-audit');
  await formName.fill('Purge audit <log> & "exports"');
  await formPeriod.fill('45');
  await formAction.selectOption('anonymize');
  await formTableClass.selectOption('field_profiles');
  // the Enabled checkbox stays checked (its default).

  const postsBefore3 = postRequests.length;
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => postRequests.length).toBe(postsBefore3 + 1);
  const post3 = postRequests[postRequests.length - 1];
  expect(post3.url).toMatch(/\/api\/retention-policies(\?|$)/);
  // AC-1: exactly the mandated fields, dataset_id = the chosen id,
  // retention_period_days a number.
  expect(JSON.parse(post3.body)).toEqual({
    name: 'Purge audit <log> & "exports"',
    table_class: 'field_profiles',
    action: 'anonymize',
    retention_period_days: 45,
    scope: 'dataset',
    dataset_id: 'ds-audit',
    is_enabled: true,
  });
  // success: the form closes and the table reloads with the new policy.
  await expect(form).toBeHidden();
  await expect(formError).toHaveText('');
  const newRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-new-1"]');
  await expect(newRow).toBeVisible();
  await expect(newRow.locator('td[data-testid="retention-policy-name"]')).toHaveText('Purge audit <log> & "exports"');
  await expect(newRow.locator('td[data-testid="retention-policy-dataset"]')).toHaveText('ds-audit');
  await expect(newRow.locator('td[data-testid="retention-policy-table-class"]')).toHaveText('field_profiles');
  await expect(newRow.locator('td[data-testid="retention-policy-period"]')).toHaveText('45 days');
  await expect(newRow.locator('td[data-testid="retention-policy-scope"]')).toHaveText('dataset');
  await expect(newRow.locator('img, script')).toHaveCount(0);

  // ------------------------------------------------------------------
  // Phase 4 — add a class-scoped policy: dataset_id posts as null
  // ------------------------------------------------------------------
  await addPolicy.click(); // toggles the form open again (fresh defaults)
  await expect(form).toBeVisible();
  await formName.fill('Keep runs forever');
  await formPeriod.fill('30');
  await form.locator('[data-testid="retention-form-enabled"]').uncheck();

  const postsBefore4 = postRequests.length;
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => postRequests.length).toBe(postsBefore4 + 1);
  expect(JSON.parse(postRequests[postRequests.length - 1].body)).toEqual({
    name: 'Keep runs forever',
    table_class: 'connection_tests',
    action: 'purge',
    retention_period_days: 30,
    scope: 'class',
    dataset_id: null,
    is_enabled: false,
  });
  await expect(form).toBeHidden();
  const classRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-new-2"]');
  await expect(classRow).toBeVisible();
  await expect(classRow.locator('td[data-testid="retention-policy-dataset"]')).toHaveText('');
  await expect(classRow.locator('td[data-testid="retention-policy-enabled"]')).toHaveText('Disabled');

  // ------------------------------------------------------------------
  // Phase 5 — local validation: no request leaves the page
  // ------------------------------------------------------------------
  await addPolicy.click();
  await expect(form).toBeVisible();
  // an empty name (with a valid period) shows the error, sends nothing.
  await formPeriod.fill('10');
  const postsBefore5 = postRequests.length;
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect(formError).toHaveText('Name is required.');
  await expect(form).toBeVisible();
  // a period below 1 (name now filled) shows the error, sends nothing.
  await formName.fill('Short policy');
  await formPeriod.fill('0');
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect(formError).toHaveText('Retention period must be at least 1 day.');
  // and an empty period is refused the same way.
  await formPeriod.fill('');
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect(formError).toHaveText('Retention period must be at least 1 day.');
  // None of the three refused saves sent a request.
  await page.waitForTimeout(300);
  expect(postRequests.length).toBe(postsBefore5);

  // ------------------------------------------------------------------
  // Phase 6 — server failures keep the form open and show the detail
  // ------------------------------------------------------------------
  await formPeriod.fill('7');
  createPolicy = { status: 422, body: { detail: 'table_class <b>runs</b> already has a policy.' } };
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect(form).toBeVisible(); // still open
  await expect(formError).toHaveText('table_class <b>runs</b> already has a policy.');
  // AC-4: the API detail renders as inert text.
  await expect(formError.locator('b')).toHaveCount(0);

  createPolicy = { status: 500, body: { no_detail_here: true } };
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect(form).toBeVisible();
  await expect(formError).toHaveText('Could not save the policy.');
  createPolicy = { status: 201, body: null }; // restore the success behavior

  // ------------------------------------------------------------------
  // Phase 7 — GET /api/datasets failed: class still works, dataset is
  // refused without sending a request
  // ------------------------------------------------------------------
  datasetsStatus = 500;
  datasetsBody = { detail: 'dataset store unavailable' };
  // A fragment-only URL change is a same-document navigation: the page
  // would not reload and Auth.init() would not re-run, so the hash token
  // would never reach /api/auth/me.  Pass through about:blank first so
  // this boot is a full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=retention#access_token=dev-secret-token:admin');
  await expect(page.locator('[data-testid="retention-policy-table"]')).toBeVisible();

  await addPolicy.click();
  await expect(form).toBeVisible();
  // scope=class still saves fine.
  await formName.fill('Class only policy');
  await formPeriod.fill('5');
  const postsBefore7 = postRequests.length;
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => postRequests.length).toBe(postsBefore7 + 1);
  expect(JSON.parse(postRequests[postRequests.length - 1].body).dataset_id).toBe(null);
  expect(JSON.parse(postRequests[postRequests.length - 1].body).scope).toBe('class');
  await expect(form).toBeHidden();

  // reopen and switch to dataset: the select is disabled...
  await addPolicy.click();
  await expect(form).toBeVisible();
  await formScope.selectOption('dataset');
  await expect(datasetField).toBeVisible();
  await expect(datasetSelect).toBeDisabled();
  // ...and saving refuses without sending a request.
  await formName.fill('Dataset scoped <but not>');
  await formPeriod.fill('9');
  const postsBefore7b = postRequests.length;
  await form.locator('[data-testid="retention-form-save"]').click();
  await expect(formError).toHaveText('Could not load datasets.');
  await expect(form).toBeVisible();
  await page.waitForTimeout(300);
  expect(postRequests.length).toBe(postsBefore7b);
  datasetsStatus = 200;
  datasetsBody = DATASETS;

  // ------------------------------------------------------------------
  // Phase 8 — delete flow: confirm sends one DELETE, cancel sends none
  // ------------------------------------------------------------------
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=retention#access_token=dev-secret-token:admin');
  const rowDel8 = page.locator('[data-testid="retention-policy-row"][data-id="pol-del"]');
  await expect(rowDel8).toBeVisible();

  // Clicking Delete replaces the button with the confirmation; the row is
  // not selected.
  await rowDel8.locator('[data-testid="retention-policy-delete"]').click();
  await expect(rowDel8.locator('[data-testid="retention-policy-delete"]')).toHaveCount(0);
  await expect(rowDel8.locator('[data-testid="retention-policy-delete-confirm-text"]')).toHaveText(
    'Delete ' + HOSTILE_POLICY_NAME + '?'
  );
  await expect(rowDel8.locator('[data-testid="retention-policy-delete-confirm"]')).toHaveText('Confirm delete');
  await expect(rowDel8.locator('[data-testid="retention-policy-delete-cancel"]')).toHaveText('Cancel');
  // AC-4: the confirmation text carries the hostile name as inert text.
  await expect(rowDel8.locator('[data-testid="retention-policy-delete-confirm-text"] img, [data-testid="retention-policy-delete-confirm-text"] script')).toHaveCount(0);
  await expect(rowDel8).not.toHaveAttribute('data-selected');
  await expect(rowDel8).not.toHaveClass(/wh-retention-row-selected/);

  // Cancel: the row is restored unchanged, no request sent.
  const deletesBefore = deleteRequests.length;
  await rowDel8.locator('[data-testid="retention-policy-delete-cancel"]').click();
  await page.waitForTimeout(300);
  expect(deleteRequests.length).toBe(deletesBefore);
  await expect(rowDel8.locator('[data-testid="retention-policy-delete"]')).toHaveCount(1);
  await expect(rowDel8.locator('[data-testid="retention-policy-delete-confirm-text"]')).toHaveCount(0);
  await expect(rowDel8.locator('[data-testid="retention-policy-delete-status"]')).toHaveText('');

  // Confirm: exactly one DELETE for the policy id; the table reloads and
  // the row is gone; no row is selected.
  await rowDel8.locator('[data-testid="retention-policy-delete"]').click();
  await rowDel8.locator('[data-testid="retention-policy-delete-confirm"]').click();
  await expect.poll(() => deleteRequests.length).toBe(deletesBefore + 1);
  expect(deleteRequests[deleteRequests.length - 1].url).toMatch(/\/api\/retention-policies\/pol-del(\?|$)/);
  await expect(rowDel8).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-row"][data-selected="true"]')).toHaveCount(0);

  // A failed delete shows the fixed message in the row and keeps the row.
  deletePolicyStatus = 500;
  const row1 = page.locator('[data-testid="retention-policy-row"][data-id="pol-1"]');
  await row1.locator('[data-testid="retention-policy-delete"]').click();
  await row1.locator('[data-testid="retention-policy-delete-confirm"]').click();
  await expect(row1.locator('[data-testid="retention-policy-delete-status"]')).toHaveText('Could not delete the policy.');
  await expect(row1).toBeVisible();
  await expect(row1.locator('[data-testid="retention-policy-delete"]')).toHaveCount(1);
  deletePolicyStatus = 204;

  // ------------------------------------------------------------------
  // Phase 9 — identity: a viewer boots the same page and sees neither
  // admin control, while the page still renders
  // ------------------------------------------------------------------
  authMeBody = VIEWER_ME;
  // The real backend is admin-only for the policy list: a viewer gets a
  // 403, which the panel must render as its error terminal state.
  policiesStatus = 403;
  policiesBody = { detail: "Role 'admin' is required to perform this action." };
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=retention#access_token=dev-secret-token:viewer');

  // The hash token of the viewer was adopted for /auth/me.
  await expect.poll(() => meAuthorization[meAuthorization.length - 1]).toBe(
    'Bearer dev-secret-token:viewer'
  );
  // The page still renders...
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Data retention');
  await expect(page.locator('[data-testid="retention-policy-table-wrap"]')).toBeVisible();
  // ...and the admin-only controls are absent.
  await expect(page.locator('[data-testid="retention-add-policy"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-delete"]')).toHaveCount(0);
  await expect(section.locator('[data-requires-role="admin"]')).toHaveCount(0);
  // The panel reached its terminal state for the forbidden list.
  await expect(page.locator('[data-testid="retention-policies-error"]')).toHaveText(
    'Could not load retention policies.'
  );
});
