const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue357 surgical', async ({ page }) => {
    // Establish an admin identity via mocked HTTP responses BEFORE the page boots.
    // The catch-all is registered FIRST so it never shadows the specific mocks below
    // (Playwright checks the most recently registered route first).
    await page.route('**/api/**', async (route) => {
        return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({}) });
    });

    await page.route('/api/auth/config', async (route) => {
        return route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
        });
    });

    await page.route('/api/auth/me', async (route) => {
        return route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                authenticated: true,
                user: { username: 'admin', sub: 'admin', roles: ['admin'] },
            }),
        });
    });

    await page.goto('/');

    // The page's own boot-time Auth.init() (via Warehouse._ensureAuth) consumes the mocked
    // /api/auth/me. Wait for that to resolve into an admin state before rendering anything.
    await page.waitForFunction(() => Auth.isAdmin() === true);

    const result = await page.evaluate(async () => {
        const captures = [];
        const origPost = ApiClient.post;
        const origPut = ApiClient.put;
        // Temporary method-level swap: intercepts only the layout write calls, never
        // /api/auth/me (already consumed at boot) and never replaces the Auth module.
        ApiClient.put = (path, body) => {
            captures.push({ method: 'put', path, body });
            return Promise.resolve({ ok: true, data: { id: 'L1', dashboard_item_id: 'i1', grid_col_start: body.grid_col_start, grid_col_span: body.grid_col_span, grid_row_span: body.grid_row_span } });
        };
        ApiClient.post = (path, body) => {
            captures.push({ method: 'post', path, body });
            return Promise.resolve({ ok: true, data: Object.assign({ id: 'L-new' }, body) });
        };

        const host = document.createElement('div');
        Object.assign(host.style, { position: 'absolute', width: '1200px', height: '600px', top: '0', left: '0', zIndex: 9999, background: '#fff' });
        document.body.appendChild(host);

        const d1 = { id: 'D1', name: 'Test Dash', grid_columns: 8 };
        const i1 = { id: 'i1', dashboard_id: 'D1', title: 'Tile One', item_type: 'kpi', position: 0 };
        const i2 = { id: 'i2', dashboard_id: 'D1', title: 'Tile Two', item_type: 'bar', position: 1 };
        const items = [i1, i2];
        const layouts = [{ id: 'L1', dashboard_item_id: 'i1', grid_col_span: 4 }];

        host.innerHTML = Warehouse.renderDashboards([d1], items, layouts);
        Warehouse.bindLayoutEditor(host, [d1], items, layouts);

        await new Promise(r => setTimeout(r, 0));

        const tile1 = host.querySelector('[data-id="i1"]');
        tile1.querySelector('[data-action="edit-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));

        const colSpanInput = host.querySelector('input[data-testid="layout-col-span"]');
        colSpanInput.value = '2';
        colSpanInput.dispatchEvent(new Event('input', { bubbles: true }));

        host.querySelector('[data-action="save-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));

        const tile1Rect = host.querySelector('[data-id="i1"]').getBoundingClientRect();
        const hostWidth = host.getBoundingClientRect().width;

        const tile2 = host.querySelector('[data-id="i2"]');
        tile2.querySelector('[data-action="edit-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));

        host.querySelector('[data-action="save-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));

        const drilldown = document.getElementById('drilldown');

        ApiClient.post = origPost;
        ApiClient.put = origPut;
        document.body.removeChild(host);

        return { captures, tile1Width: tile1Rect.width, hostWidth, drillVisible: !!(drilldown && !drilldown.hidden) };
    });

    expect(result.captures.length).toBe(2);

    expect(result.captures[0].method).toBe('put');
    expect(result.captures[0].path).toBe('/dashboard-item-layouts/L1');
    expect(result.captures[0].body.grid_col_span).toBe(2);

    expect(result.captures[1].method).toBe('post');
    expect(result.captures[1].path).toBe('/dashboard-item-layouts');
    expect(result.captures[1].body.dashboard_item_id).toBe('i2');
    expect(typeof result.captures[1].body.name).toBe('string');
    expect(result.captures[1].body.name.length).toBeGreaterThan(0);
    expect(result.captures[1].body.user_id).toBe(undefined);

    const widthDiff = Math.abs(result.tile1Width - (result.hostWidth / 4));
    expect(widthDiff).toBeLessThanOrEqual(20);

    expect(result.drillVisible).toBe(false);
});
