'use strict';

// Proof for issue #769 — Studio shows exactly one tool at a time.
//
// The main area of app/studio.html renders the tool named by ?panel= —
// or Data sources when the param is absent, unknown, or names a tool
// the user's role hides.  Every other tool's section(s) carry the
// `hidden` attribute; Load sequences is one tool over two sections
// (Load sequences + Run history).  A sidebar switch shows its tool
// without a page load (pushState), moves aria-current="page", resets
// the main region's scroll to the top and updates the title to
// "Studio · <tool name>"; Back restores the previous tool.  Hidden
// tools keep their DOM and state — loaded data and form input survive
// a switch away and back.  At 1440x900 the document does not scroll
// (only the main region, and only when the shown tool is taller than
// it); at 390x844 there is no horizontal page scroll.
//
// Identity  the criteria concern roles, so the proof also runs a
//   non-admin pass (role 'user') booted the production way: the token
//   in the URL hash (#access_token=...), /api/auth/config and
//   /api/auth/me mocked for that user, and the hash token reaching
//   /api/auth/me as a Bearer header while the page still renders with
//   the admin-only control absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { auth_mode: 'development' };
const ADMIN_ME = { authenticated: true, user: { id: 1, username: 'admin', roles: ['admin'] } };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-769';

// The Studio tools, in sidebar order, with the section(s) each owns.
const TOOLS = [
  { name: 'sources', title: 'Data sources', sections: ['sources'] },
  { name: 'suggestions', title: 'Suggestions', sections: ['suggestions'] },
  { name: 'pii', title: 'PII flags', sections: ['pii'] },
  { name: 'wizard', title: 'Process wizard', sections: ['wizard'] },
  { name: 'sequences', title: 'Load sequences', sections: ['sequences', 'sequence-runs'] },
  { name: 'retention', title: 'Data retention', sections: ['retention'] },
  { name: 'ingestion', title: 'Ingestion', sections: ['ingestion'] },
  { name: 'feedkeys', title: 'Feed keys', sections: ['feedkeys'] },
  { name: 'audit', title: 'Audit history', sections: ['audit'] },
];

const toolByName = (name) => TOOLS.find((t) => t.name === name);

// Mock every /api/** request: the auth endpoints for `me`, /api/sources
// for `sources` (every other API call an empty JSON array).
async function mockApi(page, me, sources) {
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
    }
    if (url.includes('/api/sources')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(sources || []) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
}

// The enclosing section.wh-panel of a panel's data-panel marker (the
// marker may sit on the section itself or on an inner element), with
// its shell visibility state.
function sectionState(page, panel) {
  return page.evaluate((p) => {
    const el = document.querySelector('main.wh-main [data-panel="' + p + '"]');
    const section = el ? el.closest('section.wh-panel') : null;
    if (!section) return null;
    const cs = getComputedStyle(section);
    const r = section.getBoundingClientRect();
    return {
      present: true,
      hidden: section.hasAttribute('hidden'),
      display: cs.display,
      visible: cs.display !== 'none' && r.width > 0 && r.height > 0,
    };
  }, panel);
}

// The shown tool: its section(s) visible and unhidden, every other
// tool's sections hidden (and invisible), the title "Studio · <tool
// name>", aria-current="page" on the tool's nav item and only there.
// Auth settles after boot, so every state is polled.
async function expectOneTool(page, tool) {
  for (const panel of tool.sections) {
    await expect.poll(async () => (await sectionState(page, panel)), { timeout: 10000 })
      .toMatchObject({ hidden: false, visible: true });
  }
  for (const other of TOOLS) {
    if (other.name === tool.name) continue;
    for (const panel of other.sections) {
      await expect.poll(async () => sectionState(page, panel), { timeout: 10000 })
        .toMatchObject({ hidden: true, display: 'none', visible: false });
    }
  }
  await expect(page.locator('.aidw-page-title'), 'title for the shown tool').toHaveText('Studio · ' + tool.title);
  const current = await page.evaluate(() =>
    Array.from(document.querySelectorAll('.aidw-nav-item[aria-current="page"]'))
      .map((a) => a.getAttribute('data-nav-panel')));
  expect(current, 'aria-current on the shown tool only').toEqual([tool.name]);
}

// The document itself must not scroll (the shell's fixed-height layout).
async function expectNoDocumentScroll(page) {
  const m = await page.evaluate(() => ({
    doc: document.scrollingElement.scrollHeight - document.scrollingElement.clientHeight,
    body: document.body.scrollHeight - document.body.clientHeight,
    win: window.scrollY,
  }));
  expect(m.doc).toBeLessThanOrEqual(0);
  expect(m.body).toBeLessThanOrEqual(0);
  expect(m.win).toBe(0);
}

// Neither the document nor the body carries horizontal scrollable
// overflow, and the viewport cannot be moved sideways.
async function expectNoHorizontalScroll(page) {
  const m = await page.evaluate(() => {
    window.scrollTo(100, 0);
    const doc = document.documentElement;
    return {
      scrollX: window.scrollX,
      doc: doc.scrollWidth - doc.clientWidth,
      body: document.body.scrollWidth - document.body.clientWidth,
    };
  });
  expect(m.scrollX).toBe(0);
  expect(m.doc).toBeLessThanOrEqual(0);
  expect(m.body).toBeLessThanOrEqual(0);
}

test('issue769 freeform', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });

  // ------------------------------------------------------------------
  // Every ?panel= value shows only its tool; absent and unknown values
  // show Data sources.
  // ------------------------------------------------------------------
  await mockApi(page, ADMIN_ME, []);
  for (const tool of TOOLS) {
    await page.goto('/studio.html?panel=' + tool.name);
    await expectOneTool(page, tool);
  }
  await page.goto('/studio.html');
  await expectOneTool(page, toolByName('sources'));
  await page.goto('/studio.html?panel=bogus');
  await expectOneTool(page, toolByName('sources'));

  // ------------------------------------------------------------------
  // Scrolling: the document never scrolls; the main region scrolls only
  // when the shown tool is taller than it.
  // ------------------------------------------------------------------
  const tallSources = Array.from({ length: 30 }, (_, i) => ({
    id: 'src-' + i,
    name: 'Source ' + i,
    type: 'odata',
  }));
  await mockApi(page, ADMIN_ME, tallSources);
  await page.goto('/studio.html?panel=sources');
  await expectOneTool(page, toolByName('sources'));
  // The rendered list overflows the main region...
  await expect.poll(async () => page.evaluate(() => {
    const el = document.querySelector('[data-testid="main-content"]');
    return el.scrollHeight - el.clientHeight;
  }), 'a tall tool overflows the main region').toBeGreaterThan(0);
  // ...while the document itself does not scroll.
  await expectNoDocumentScroll(page);

  await page.goto('/studio.html?panel=ingestion');
  await expectOneTool(page, toolByName('ingestion'));
  // The empty Ingestion tool fits: the region does not scroll.
  await expect.poll(async () => page.evaluate(() => {
    const el = document.querySelector('[data-testid="main-content"]');
    return el.scrollHeight - el.clientHeight;
  })).toBeLessThanOrEqual(0);
  await expectNoDocumentScroll(page);

  // ------------------------------------------------------------------
  // Switching tools: no page load, aria-current moves, the region
  // scrolls back to the top, Back restores the previous tool.
  // ------------------------------------------------------------------
  await page.goto('/studio.html');
  await expectOneTool(page, toolByName('sources'));
  await page.evaluate(() => { window.__issue769Marker = 'alive'; });
  // The user scrolls the tall sources list away from the top...
  await page.evaluate(() => {
    const el = document.querySelector('[data-testid="main-content"]');
    el.scrollTop = el.scrollHeight;
  });
  // ...and a sidebar click shows its tool in place.
  await page.click('.aidw-nav-item[data-nav-panel="suggestions"]');
  expect(await page.evaluate(() => window.__issue769Marker), 'no page load on a sidebar switch').toBe('alive');
  expect(new URL(page.url()).searchParams.get('panel'), 'pushState rewrote ?panel=').toBe('suggestions');
  await expect.poll(async () => page.evaluate(() =>
    document.querySelector('[data-testid="main-content"]').scrollTop)).toBe(0);
  await expectOneTool(page, toolByName('suggestions'));

  // Switching again keeps the marker and the state.
  await page.click('.aidw-nav-item[data-nav-panel="sources"]');
  expect(await page.evaluate(() => window.__issue769Marker)).toBe('alive');
  await expectOneTool(page, toolByName('sources'));
  await page.click('.aidw-nav-item[data-nav-panel="suggestions"]');
  await expectOneTool(page, toolByName('suggestions'));

  // Back restores the previous tool (the pushState entry), without a
  // page load.
  await page.goBack();
  expect(new URL(page.url()).searchParams.get('panel'), 'Back restored ?panel=sources').toBe('sources');
  expect(await page.evaluate(() => window.__issue769Marker), 'Back is a same-document restore').toBe('alive');
  await expectOneTool(page, toolByName('sources'));

  // Forward restores the later tool, also without a page load.
  await page.goForward();
  expect(new URL(page.url()).searchParams.get('panel'), 'Forward restored ?panel=suggestions').toBe('suggestions');
  expect(await page.evaluate(() => window.__issue769Marker), 'Forward is a same-document restore').toBe('alive');
  await expectOneTool(page, toolByName('suggestions'));

  // ------------------------------------------------------------------
  // Hidden tools keep their state: a form value typed in Data sources
  // survives a switch away and back.
  // ------------------------------------------------------------------
  await page.click('.aidw-nav-item[data-nav-panel="sources"]');
  await expectOneTool(page, toolByName('sources'));
  await page.fill('#src-name', 'kept source name');
  await page.click('.aidw-nav-item[data-nav-panel="suggestions"]');
  await expectOneTool(page, toolByName('suggestions'));
  expect(await page.evaluate(() => document.getElementById('src-name').value),
    'the hidden form kept its value').toBe('kept source name');
  await page.click('.aidw-nav-item[data-nav-panel="sources"]');
  await expect(page.locator('#src-name')).toHaveValue('kept source name');

  // ------------------------------------------------------------------
  // 390x844: no horizontal page scroll.
  // ------------------------------------------------------------------
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/studio.html?panel=suggestions');
  await expectOneTool(page, toolByName('suggestions'));
  await expectNoHorizontalScroll(page);
});

test('issue769 freeform (viewer)', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });

  // Boot the page the production way for a role 'user' identity: the
  // token rides the URL hash (#access_token=...), /api/auth/config and
  // /api/auth/me are mocked for that user, and the hash token must
  // reach /api/auth/me as a Bearer header.
  const meAuthorizations = [];
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const url = request.url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorizations.push(auth);
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(VIEWER_ME) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // A role-hidden tool (Feed keys) named by ?panel= falls back to Data
  // sources...
  await page.goto('/studio.html?panel=feedkeys#access_token=' + encodeURIComponent(VIEWER_TOKEN));
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + VIEWER_TOKEN);
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Data sources');
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

  // ...while every other usable tool's section is hidden.  The role-
  // hidden tools keep their own fail-closed rendering: the Feed keys
  // section is removed by its module and the Audit section shows its
  // administrators-only note.
  for (const tool of TOOLS) {
    if (tool.name === 'sources' || tool.name === 'feedkeys' || tool.name === 'audit') continue;
    for (const panel of tool.sections) {
      await expect.poll(async () => sectionState(page, panel), { timeout: 10000 })
        .toMatchObject({ hidden: true, display: 'none', visible: false });
    }
  }
  await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="audit"]')).toBeVisible();
  await expect(page.locator('[data-testid="audit-admin-only-note"]')).toHaveText('Audit history is available to administrators.');

  // ...and the admin-only controls are absent: no role-gated nav item
  // survives for a non-admin, and the admin-only source form is gone.
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
  await expect(page.locator('#source-form')).toHaveCount(0);

  // An unknown panel for a non-admin also falls back to Data sources.
  await page.goto('/studio.html?panel=bogus#access_token=' + encodeURIComponent(VIEWER_TOKEN));
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Data sources');
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
});
