'use strict';

// Proof for issue #700 — admin controls on the Ingestion panel
// (app/js/ingestion.js).
//
// Boots /studio.html?panel=ingestion as an admin with every /api/** request
// mocked (recording every POST and PUT), and proves:
//   AC-1  every pipeline row carries a "Run now" button with
//         data-requires-role="admin"; clicking it disables the button while
//         the request is open and sends exactly one POST
//         /api/pipelines/<id>/runs with no body; the row then shows the
//         outcome — "Run finished: succeeded" for a 201 with that status,
//         "Run queued" for a 202, "Ingest is not enabled on this server."
//         for a 503, the response detail (or "Could not start the run."
//         when there is none) for any other failure — and the button is
//         enabled again after any outcome; the runs list reloads when the
//         clicked pipeline is the selected one (and only then), and the
//         selection never changes
//   AC-2  every admin row's Enabled/Disabled cell holds the toggle with
//         data-requires-role="admin" (review defect: no toggle in a
//         separate Actions cell), labelled "Disable" on an enabled
//         pipeline and "Enable" on a disabled one — on aria-label and
//         the ::before label, with no DOM text, so the cell's textContent
//         stays exactly the state word for every role (the issue #692
//         proof pins that text); clicking it sends PUT
//         /api/pipelines/<id> with exactly {"is_enabled": false} on an
//         enabled pipeline and reloads the table; a failure shows
//         "Could not update the pipeline." in the row — on the row's
//         live DOM even when a concurrent table reload replaced the
//         row's nodes while the PUT was still open (review defect:
//         stale statusEl)
//   Defect  a table re-render that happens while a run-now request is
//         still open (the toggle's reload) keeps the button disabled,
//         shows the outcome on the re-rendered row once it lands, keeps
//         the selection, and sends no duplicate POST
//   Identity  after a full reload booted the production way — the token in
//         the URL hash (#access_token=...), /api/auth/config and
//         /api/auth/me mocked for a roles: ["viewer"] user — the page still
//         renders with the "Enabled"/"Disabled" text and neither admin-only
//         control

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});
const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const VIEWER_ME = {
  authenticated: true,
  user: { id: 7, username: 'viewer', roles: ['viewer'] },
};

const DATASETS = [
  {
    id: 'ds-orders',
    name: 'Orders',
    object_type: 'table',
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
];

// In-memory pipeline state: the mocked PUT applies the toggle, so the
// post-toggle table reload is observable (the row's label flips).
const PIPELINES = [
  {
    id: 'pipe-1',
    name: 'Orders CDC',
    dataset_id: 'ds-orders',
    cdc_pattern: 'orders.*',
    schedule: '0 * * * *',
    is_enabled: true,
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
  {
    id: 'pipe-2',
    name: 'Orders delta',
    dataset_id: 'ds-orders',
    cdc_pattern: 'orders_delta',
    schedule: '0 4 * * *',
    is_enabled: false,
    created_at: '2026-09-02T00:00:00',
    updated_at: '2026-09-02T00:00:00',
  },
];

const RUNS = [
  {
    id: 'run-1',
    pipeline_id: 'pipe-1',
    name: 'Nightly load',
    status: 'succeeded',
    trigger: 'schedule',
    started_at: '2026-09-10T02:00:00',
    finished_at: '2026-09-10T02:05:00',
    rows_read: 5000,
    rows_written: 4800,
    rows_suppressed: 200,
    error_detail: null,
  },
  {
    id: 'run-2',
    pipeline_id: 'pipe-2',
    name: 'Weekly delta',
    status: 'failed',
    trigger: 'manual',
    started_at: '2026-10-01T02:00:00',
    finished_at: '2026-10-01T02:10:00',
    rows_read: 900,
    rows_written: 0,
    rows_suppressed: 0,
    error_detail: 'Connection refused by source',
  },
];

test('issue700 freeform', async ({ page }) => {
  const postRequests = [];
  const putRequests = [];
  let runGets = 0;
  const meAuthorization = [];
  let authMeBody = ADMIN_ME;
  // Behavior of the mocked POST /api/pipelines/<id>/runs.
  let runNow = {
    status: 201,
    delayMs: 0,
    body: {
      id: 'run-100',
      pipeline_id: 'pipe-1',
      status: 'succeeded',
      trigger: 'manual',
      started_at: '2026-10-05T02:00:00',
      finished_at: '2026-10-05T02:00:30',
      rows_read: 100,
      rows_written: 95,
      rows_suppressed: 5,
      error_detail: null,
    },
  };
  // Pipeline ids whose mocked PUT /api/pipelines/<id> fails with a 500.
  const putFailIds = new Set();
  // Pipeline id -> delay (ms) before the mocked PUT responds.
  const putDelayMs = new Map();

  const json = (route, status, body, delayMs = 0) => {
    const respond = () =>
      route.fulfill({
        status,
        contentType: 'application/json',
        body: JSON.stringify(body),
      });
    return delayMs
      ? new Promise((resolve) => setTimeout(resolve, delayMs)).then(respond)
      : Promise.resolve(respond());
  };

  // Every /api/** request is mocked; every POST and PUT is recorded.
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();

    if (method === 'POST') postRequests.push({ method, url, body: request.postData() });
    if (method === 'PUT') putRequests.push({ method, url, body: request.postData() });

    if (url.includes('/api/auth/config')) return json(route, 200, AUTH_CONFIG);
    if (url.includes('/api/auth/me')) {
      meAuthorization.push(request.headers()['authorization'] || null);
      return json(route, 200, authMeBody);
    }
    if (method === 'POST' && /\/api\/pipelines\/[^/?#]+\/runs$/.test(url)) {
      return json(route, runNow.status, runNow.body, runNow.delayMs);
    }
    if (method === 'PUT' && /\/api\/pipelines\/[^/?#]+$/.test(url)) {
      const id = decodeURIComponent(url.split('/api/pipelines/')[1]);
      const pipeline = PIPELINES.find((p) => String(p.id) === String(id));
      const delayMs = putDelayMs.get(id) || 0;
      if (putFailIds.has(id)) {
        return json(route, 500, { detail: 'simulated update failure' }, delayMs);
      }
      const body = JSON.parse(request.postData() || '{}');
      if (pipeline && typeof body.is_enabled === 'boolean') {
        pipeline.is_enabled = body.is_enabled;
      }
      return json(route, 200, pipeline || {}, delayMs);
    }
    if (url.includes('/api/pipelines')) return json(route, 200, PIPELINES);
    if (url.includes('/api/datasets')) return json(route, 200, DATASETS);
    if (url.includes('/api/runs')) {
      runGets += 1;
      return json(route, 200, RUNS);
    }
    return json(route, 200, []);
  });

  const row = (id) => page.locator(`[data-testid="ingestion-pipeline-row"][data-id="${id}"]`);
  const rowName = (id) => row(id).locator('[data-testid="ingestion-pipeline-name"]');
  const enabledCell = (id) =>
    row(id).locator('td[data-testid="ingestion-pipeline-enabled"]');
  const runNowOf = (id) => row(id).locator('[data-testid="ingestion-run-now"]');
  const runNowStatusOf = (id) => row(id).locator('[data-testid="ingestion-run-now-status"]');
  const toggleOf = (id) => row(id).locator('[data-testid="ingestion-enabled-toggle"]');
  const toggleStatusOf = (id) => row(id).locator('[data-testid="ingestion-enabled-status"]');
  // The toggle carries no DOM text (the cell's textContent must stay
  // exactly the state word — issue #692 pins it), so its label is
  // read from the attributes and pseudo-element that carry it.
  const toggleAriaOf = (id) =>
    toggleOf(id).evaluate((el) => el.getAttribute('aria-label')).catch(() => null);
  const toggleBeforeOf = (id) =>
    toggleOf(id).evaluate((el) => getComputedStyle(el, '::before').content).catch(() => null);
  const toggleDomTextOf = (id) =>
    toggleOf(id).evaluate((el) => el.textContent).catch(() => null);
  const runsArea = page.locator('[data-testid="ingestion-runs"]');

  // ------------------------------------------------------------------
  // Phase 1 — admin boot: the controls render for the admin role
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=ingestion');

  await expect(page.locator('[data-testid="ingestion-pipeline-table"]')).toBeAttached();
  await expect(row('pipe-1')).toBeVisible();
  await expect(row('pipe-2')).toBeVisible();

  // AC-1: every row carries the "Run now" button, marked admin-only.
  for (const id of ['pipe-1', 'pipe-2']) {
    const button = runNowOf(id);
    await expect(button).toHaveCount(1);
    await expect(button).toHaveText('Run now');
    await expect(button).toHaveAttribute('data-requires-role', 'admin');
    await expect(row(id).locator('[data-testid="ingestion-pipeline-actions"]')).toHaveCount(1);
  }

  // AC-2: the toggle lives in the row's Enabled/Disabled cell (review
  // defect: not in a separate Actions cell), labelled by the pipeline's
  // enabled state.  The label rides on aria-label and the ::before rule
  // (no DOM text), so the cell's textContent stays exactly the state
  // word — the same text the issue #692 proof pins, for an admin.
  for (const [id, state, label] of [
    ['pipe-1', 'Enabled', 'Disable'],
    ['pipe-2', 'Disabled', 'Enable'],
  ]) {
    const toggle = enabledCell(id).locator('[data-testid="ingestion-enabled-toggle"]');
    await expect(toggle).toHaveCount(1);
    await expect(toggle).toHaveAttribute('data-requires-role', 'admin');
    expect(await toggleAriaOf(id)).toBe(label);
    expect(await toggleBeforeOf(id)).toBe(`"${label}"`);
    expect(await toggleDomTextOf(id)).toBe('');
    await expect(enabledCell(id)).toHaveText(state);
    // Exactly one toggle in the row, and none in the Actions cell (which
    // holds only the Run now button).
    await expect(row(id).locator('[data-testid="ingestion-enabled-toggle"]')).toHaveCount(1);
    await expect(
      row(id).locator('[data-testid="ingestion-pipeline-actions"] [data-testid="ingestion-enabled-toggle"]')
    ).toHaveCount(0);
  }

  // ------------------------------------------------------------------
  // Phase 2 — "Run now" on the selected pipeline: 201, one POST, no body,
  // the row shows "Run finished: succeeded", the runs list reloads and
  // the selection does not change
  // ------------------------------------------------------------------
  await rowName('pipe-1').click();
  await expect(runsArea.locator('[data-testid="ingestion-run-row"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="ingestion-run-status"]')).toHaveText('succeeded');
  await expect(row('pipe-1')).toHaveAttribute('data-selected', 'true');
  await expect(row('pipe-2')).not.toHaveAttribute('data-selected');
  const runGetsAfterSelect = runGets;

  runNow = { status: 201, delayMs: 500, body: { id: 'run-100', pipeline_id: 'pipe-1', status: 'succeeded', trigger: 'manual', started_at: '2026-10-05T02:00:00', finished_at: '2026-10-05T02:00:30', rows_read: 100, rows_written: 95, rows_suppressed: 5, error_detail: null } };
  await runNowOf('pipe-1').click();
  // The button is disabled while the request is open ...
  await expect(runNowOf('pipe-1')).toBeDisabled();
  // ... and enabled again once the outcome has landed.
  await expect(runNowOf('pipe-1')).toBeEnabled();
  await expect(runNowStatusOf('pipe-1')).toHaveText('Run finished: succeeded');

  // Exactly one POST to this pipeline's /runs endpoint, with no body.
  const pipe1RunsPosts = postRequests.filter((r) => r.url.endsWith('/api/pipelines/pipe-1/runs'));
  expect(pipe1RunsPosts).toHaveLength(1);
  expect(pipe1RunsPosts[0].body).toBeNull();

  // The selected pipeline's runs list reloaded ...
  await expect.poll(() => runGets).toBe(runGetsAfterSelect + 1);
  // ... and the selection did not change.
  await expect(row('pipe-1')).toHaveAttribute('data-selected', 'true');
  await expect(row('pipe-2')).not.toHaveAttribute('data-selected');

  // ------------------------------------------------------------------
  // Phase 3 — "Run now" 202 on the second (disabled) pipeline
  // ------------------------------------------------------------------
  await rowName('pipe-2').click();
  await expect(runsArea.locator('[data-testid="ingestion-run-row"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="ingestion-run-status"]')).toHaveText('failed');
  const runGetsBefore202 = runGets;

  runNow = { status: 202, delayMs: 0, body: { id: 'run-101', pipeline_id: 'pipe-2', status: 'pending' } };
  await runNowOf('pipe-2').click();
  await expect(runNowStatusOf('pipe-2')).toHaveText('Run queued');
  await expect(runNowOf('pipe-2')).toBeEnabled();
  const pipe2RunsPosts = postRequests.filter((r) => r.url.endsWith('/api/pipelines/pipe-2/runs'));
  expect(pipe2RunsPosts).toHaveLength(1);
  expect(pipe2RunsPosts[0].body).toBeNull();
  await expect.poll(() => runGets).toBe(runGetsBefore202 + 1);

  // ------------------------------------------------------------------
  // Phase 4 — 503: the fixed "not enabled" text; pipe-2 is still selected,
  // so clicking pipe-1 must NOT reload a runs list
  // ------------------------------------------------------------------
  const runGetsBefore503 = runGets;
  runNow = {
    status: 503,
    delayMs: 0,
    body: {
      detail:
        'in-API ingest is disabled (set ENABLE_INAPI_EGRESS=true to enable the interim in-API egress path, or INGEST_EXECUTOR=worker to enqueue for the connector worker)',
    },
  };
  await runNowOf('pipe-1').click();
  await expect(runNowStatusOf('pipe-1')).toHaveText('Ingest is not enabled on this server.');
  await expect(runNowOf('pipe-1')).toBeEnabled();
  expect(runGets).toBe(runGetsBefore503); // unselected pipeline: no runs reload

  // ------------------------------------------------------------------
  // Phase 5 — other failures: the response detail, else the fallback text
  // ------------------------------------------------------------------
  runNow = { status: 404, delayMs: 0, body: { detail: 'pipeline not found' } };
  await runNowOf('pipe-1').click();
  await expect(runNowStatusOf('pipe-1')).toHaveText('pipeline not found');
  await expect(runNowOf('pipe-1')).toBeEnabled();

  runNow = { status: 500, delayMs: 0, body: {} };
  await runNowOf('pipe-1').click();
  await expect(runNowStatusOf('pipe-1')).toHaveText('Could not start the run.');
  await expect(runNowOf('pipe-1')).toBeEnabled();

  // ------------------------------------------------------------------
  // Phase 5b — review defect: a table re-render that happens while the
  // run-now request is still open (triggered here by a successful toggle
  // on another row) must not lose the outcome or the button's disabled
  // state, must not drop the selection, and must not let a duplicate
  // POST through; the selected pipeline's runs list still reloads once
  // the outcome lands
  // ------------------------------------------------------------------
  await rowName('pipe-1').click();
  await expect(runsArea.locator('[data-testid="ingestion-run-row"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="ingestion-run-status"]')).toHaveText('succeeded');
  await expect(row('pipe-1')).toHaveAttribute('data-selected', 'true');
  const runGetsBeforeMidRender = runGets;
  const postsBeforeMidRender = postRequests.length;

  runNow = { status: 201, delayMs: 2000, body: { id: 'run-102', pipeline_id: 'pipe-1', status: 'succeeded', trigger: 'manual', started_at: '2026-10-05T03:00:00', finished_at: '2026-10-05T03:00:30', rows_read: 10, rows_written: 9, rows_suppressed: 1, error_detail: null } };
  await runNowOf('pipe-1').click();
  // The button is disabled while the request is open ...
  await expect(runNowOf('pipe-1')).toBeDisabled();

  // Re-render the table mid-request: the toggle on pipe-2 (label "Enable"
  // while disabled) succeeds and reloads the table, replacing every row's
  // DOM nodes while the run-now POST above is still in flight.
  await expect.poll(() => toggleAriaOf('pipe-2')).toBe('Enable');
  await toggleOf('pipe-2').click();
  await expect.poll(() => toggleAriaOf('pipe-2')).toBe('Disable'); // table reloaded

  // The re-rendered "Run now" button stays disabled ...
  await expect(runNowOf('pipe-1')).toBeDisabled();
  // ... the selection survived the re-render ...
  await expect(row('pipe-1')).toHaveAttribute('data-selected', 'true');
  // ... and no duplicate POST went out while the request was open.
  expect(postRequests.length).toBe(postsBeforeMidRender + 1);

  // ... and once the response lands, the outcome is shown on the
  // re-rendered row, the button is enabled again, and the selected
  // pipeline's runs list reloaded.
  await expect(runNowStatusOf('pipe-1')).toHaveText('Run finished: succeeded');
  await expect(runNowOf('pipe-1')).toBeEnabled();
  await expect.poll(() => runGets).toBe(runGetsBeforeMidRender + 1);
  const pipe1RunsPostsMidRender = postRequests.filter((r) => r.url.endsWith('/api/pipelines/pipe-1/runs'));
  expect(pipe1RunsPostsMidRender).toHaveLength(5); // phases 2, 4, 5 (x2) and this phase: exactly one POST each
  expect(pipe1RunsPostsMidRender[4].body).toBeNull();

  PIPELINES[1].is_enabled = false; // restore the state for the later phases

  // ------------------------------------------------------------------
  // Phase 6 — "Disable" on the enabled pipeline: exactly
  // {"is_enabled": false} on PUT /api/pipelines/pipe-1, then a reload
  // ------------------------------------------------------------------
  await expect.poll(() => toggleAriaOf('pipe-1')).toBe('Disable');
  await toggleOf('pipe-1').click();
  // The table reloaded: the mocked state flipped, so the label now reads
  // "Enable" and the row carries no failure text.
  await expect.poll(() => toggleAriaOf('pipe-1')).toBe('Enable');
  await expect(toggleStatusOf('pipe-1')).toHaveText('');

  const pipe1Puts = putRequests.filter((r) => r.url.endsWith('/api/pipelines/pipe-1'));
  expect(pipe1Puts).toHaveLength(1);
  expect(pipe1Puts[0].body).toBe('{"is_enabled":false}');
  expect(Object.keys(JSON.parse(pipe1Puts[0].body))).toHaveLength(1);
  expect(pipe1Puts[0].method).toBe('PUT');

  // ------------------------------------------------------------------
  // Phase 7 — toggle failure: the row shows "Could not update the
  // pipeline." and the table is NOT reloaded
  // ------------------------------------------------------------------
  putFailIds.add('pipe-2');
  await expect.poll(() => toggleAriaOf('pipe-2')).toBe('Enable');
  await toggleOf('pipe-2').click();
  // A reload would re-render the row and wipe this text; it must survive.
  await expect(toggleStatusOf('pipe-2')).toHaveText('Could not update the pipeline.');
  await expect.poll(() => toggleAriaOf('pipe-2')).toBe('Enable');
  putFailIds.delete('pipe-2');

  // ------------------------------------------------------------------
  // Phase 7b — review defect: the failure text must land on the
  // row's LIVE DOM.  A concurrent table re-render (pipe-1's successful
  // toggle) replaces every row's nodes while pipe-2's failing PUT is
  // still open; the status element captured at click time is then
  // detached, and the message must not be written into it.
  // ------------------------------------------------------------------
  // Both pipelines are disabled here, so both toggles read "Enable".
  await expect.poll(() => toggleAriaOf('pipe-1')).toBe('Enable');
  await expect.poll(() => toggleAriaOf('pipe-2')).toBe('Enable');

  putFailIds.add('pipe-2');
  putDelayMs.set('pipe-2', 1500); // pipe-2's PUT stays open across the re-render
  const pipe2RowBefore = await row('pipe-2').elementHandle();
  await toggleOf('pipe-2').click(); // failing PUT: 500 after 1500 ms
  await toggleOf('pipe-1').click(); // fast success -> loadTable re-renders

  // The re-render really happened while pipe-2's PUT was still open: the
  // row node captured at click time is detached from the document.
  await expect.poll(async () => pipe2RowBefore.evaluate((el) => el.isConnected)).toBe(false);
  // pipe-1's state flipped and the reloaded table shows it ...
  await expect.poll(() => toggleAriaOf('pipe-1')).toBe('Disable');
  const pipe1Puts7b = putRequests.filter((r) => r.url.endsWith('/api/pipelines/pipe-1'));
  expect(pipe1Puts7b[pipe1Puts7b.length - 1].body).toBe('{"is_enabled":true}');
  // ... and pipe-2's failing PUT went out with the opposite of its
  // rendered state (disabled -> is_enabled: true).
  const pipe2Puts7b = putRequests.filter((r) => r.url.endsWith('/api/pipelines/pipe-2'));
  expect(pipe2Puts7b[pipe2Puts7b.length - 1].body).toBe('{"is_enabled":true}');

  // Once pipe-2's failing PUT settles, its message lands on the LIVE
  // (re-rendered) row — the stale statusEl captured at click time is
  // detached and must not swallow the message.
  await expect(toggleStatusOf('pipe-2')).toHaveText('Could not update the pipeline.');

  putFailIds.delete('pipe-2');
  putDelayMs.clear();
  PIPELINES[0].is_enabled = true; // restore a clean state for the viewer phase
  PIPELINES[1].is_enabled = false;

  // ------------------------------------------------------------------
  // Phase 8 — identity: a non-admin (roles: ["viewer"]) booted the
  // production way (token in the URL hash, /api/auth/config and
  // /api/auth/me mocked for that user) sees the page render with the
  // Enabled/Disabled text and neither admin-only control
  // ------------------------------------------------------------------
  PIPELINES[0].is_enabled = true; // restore a clean viewer view
  authMeBody = VIEWER_ME;
  meAuthorization.length = 0;

  // A fragment-only URL change is a same-document navigation: the page
  // would not reload and Auth.init() would not re-run, so the hash token
  // would never reach /api/auth/me.  Pass through about:blank first so
  // this boot is a full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=ingestion#access_token=viewer-token-700');

  await expect(page.locator('[data-testid="ingestion-pipeline-table"]')).toBeAttached();
  await expect(row('pipe-1')).toBeVisible();
  await expect(row('pipe-2')).toBeVisible();

  // The hash token was picked up the production way and sent on /auth/me.
  expect(meAuthorization.length).toBeGreaterThan(0);
  expect(meAuthorization).toContain('Bearer viewer-token-700');

  // The page still renders: the rows show only the plain text labels.
  await expect(rowName('pipe-1')).toHaveText('Orders CDC');
  await expect(enabledCell('pipe-1')).toHaveText('Enabled');
  await expect(enabledCell('pipe-2')).toHaveText('Disabled');
  // No toggle in the cell for the viewer either — the cell is text
  // only.
  await expect(enabledCell('pipe-1').locator('[data-testid="ingestion-enabled-toggle"]')).toHaveCount(0);
  await expect(enabledCell('pipe-2').locator('[data-testid="ingestion-enabled-toggle"]')).toHaveCount(0);

  // Neither admin-only control exists for the viewer.
  await expect(runNowOf('pipe-1')).toHaveCount(0);
  await expect(runNowOf('pipe-2')).toHaveCount(0);
  await expect(toggleOf('pipe-1')).toHaveCount(0);
  await expect(toggleOf('pipe-2')).toHaveCount(0);
  await expect(row('pipe-1').locator('[data-testid="ingestion-pipeline-actions"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="ingestion"] [data-requires-role="admin"]')).toHaveCount(0);
});
