const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue697 surgical', async ({ page }) => {
  const postRequests = [];

  await page.route('**/api/**', async (route) => {
    const req = route.request();
    const url = req.url();
    const method = req.method();

    if (method === 'POST') {
      postRequests.push({ method, url });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
      });
    }

    if (url.includes('/api/auth/me')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ authenticated: true, user: { username: 'testuser', roles: ['admin'] } }),
      });
    }

    if (url.includes('/api/load-sequences')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([{ id: 'seq-1', name: 'Seq' }]),
      });
    }

    if (method === 'GET' && url.includes('/api/sequence-runs')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([{ id: 'run-1', name: 'Run 1', sequence_id: 'seq-1', status: 'completed' }]),
      });
    }

    if (method === 'POST' && url.includes('/api/sequence-runs') && !url.includes('/execute')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ id: 'run-2', name: 'run-2', sequence_id: 'seq-1', status: 'pending' }),
      });
    }

    if (method === 'POST' && url.includes('/execute')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ id: 'run-2', name: 'run-2', sequence_id: 'seq-1', status: 'completed', steps: [] }),
      });
    }

    return route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify([]),
    });
  });

  await page.goto('/studio.html');

  const seqRow = page.locator('[data-testid="sequence-row"]');
  await expect(seqRow).toBeVisible();
  await seqRow.click();

  const executeBtn = page.locator('[data-testid="sequence-execute"]');
  await expect(executeBtn).toBeVisible();

  // Demote to viewer in page scope
  await page.evaluate(() => { Auth._user = { ...Auth._user, roles: ['viewer'] }; });

  await executeBtn.click();

  const errorEl = page.locator('[data-testid="runs-error"]');
  await expect(errorEl).toContainText('Not authorized to execute runs.');

  // No POST to /api/sequence-runs should have been recorded
  const seqRunPosts = postRequests.filter(r => r.url.includes('/api/sequence-runs'));
  expect(seqRunPosts).toHaveLength(0);
});

test('issue697 surgical (admin execute)', async ({ page }) => {
  const postRequests = [];

  await page.route('**/api/**', async (route) => {
    const req = route.request();
    const url = req.url();
    const method = req.method();

    if (method === 'POST') {
      postRequests.push({ method, url });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
      });
    }

    if (url.includes('/api/auth/me')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ authenticated: true, user: { username: 'testuser', roles: ['admin'] } }),
      });
    }

    if (url.includes('/api/load-sequences')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([{ id: 'seq-1', name: 'Seq' }]),
      });
    }

    if (method === 'GET' && url.includes('/api/sequence-runs')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([{ id: 'run-1', name: 'Run 1', sequence_id: 'seq-1', status: 'completed' }]),
      });
    }

    if (method === 'POST' && url.includes('/api/sequence-runs') && !url.includes('/execute')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ id: 'run-2', name: 'run-2', sequence_id: 'seq-1', status: 'pending' }),
      });
    }

    if (method === 'POST' && url.includes('/execute')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ id: 'run-2', name: 'run-2', sequence_id: 'seq-1', status: 'completed', steps: [] }),
      });
    }

    return route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify([]),
    });
  });

  await page.goto('/studio.html');

  const seqRow = page.locator('[data-testid="sequence-row"]');
  await expect(seqRow).toBeVisible();
  await seqRow.click();

  const executeBtn = page.locator('[data-testid="sequence-execute"]');
  await expect(executeBtn).toBeVisible();

  await executeBtn.click();

  // Wait for the execute flow to complete: two run-rows (run-1 + run-2)
  await expect(page.locator('[data-testid="run-row"]')).toHaveCount(2);

  // A POST to /api/sequence-runs was recorded
  const seqRunPosts = postRequests.filter(r => r.url.includes('/api/sequence-runs'));
  expect(seqRunPosts.length).toBeGreaterThan(0);
});
