'use strict';

// Proof for issue #754 — the read-only "Audit history" admin panel on
// /studio.html (app/js/audit.js + the audit section in app/studio.html).
//
// Boots /studio.html?panel=audit with /api/auth/config and /api/auth/me
// mocked and every other /api/** request mocked, and proves:
//   AC-1  app/studio.html gains <section class="wh-panel"
//         data-panel="audit"> with the "Audit history" heading, loads
//         app/js/audit.js defining const AuditView with an init() called
//         on Studio boot after Auth.init(), and for an admin calls
//         GET /api/audit?limit=100 through the API client. It renders
//         inside an element marked data-requires-role="admin": first a
//         block element (data-testid="audit-filter-row") holding a
//         select that lists "All entity types" plus each distinct
//         entity type in the loaded events, then, after that block in
//         document order, a table of the events ordered newest first by
//         timestamp (ISO strings and numeric epoch values compared
//         chronologically), showing time, action, entity type, entity
//         id, the actor's username (or actor_sub when there is none)
//         and the details as compact "key: value" pairs — every value
//         written with textContent, the actor's email never shown;
//         choosing an entity type shows only its events and "All
//         entity types" shows them all again; no events shows
//         "No audit events yet."; a failed request shows "Could not
//         load audit history."
//   AC-2  four mocked events across two entity types: one with no actor
//         username, one whose details carry
//         <img src=x onerror=alert(1)>, and timestamps mixing ISO
//         strings with numeric epoch values.  As an admin: the events
//         render newest first in true chronological order (the mock
//         order and a lexicographic string order both differ); no
//         example.com email appears in the page text or the serialized
//         DOM; the no-username event shows its actor_sub; the <img>
//         payload appears only as text and no <img> element exists;
//         the filter row precedes the table in document order
//         (compareDocumentPosition, not pixel positions); the select
//         filters and resets.  A second boot as a user with
//         roles: ["user"] shows the administrators-only text, no
//         data-requires-role="admin" element and no /api/audit
//         request.  A third boot where /api/auth/me answers 500, so
//         Auth.init() fails, shows the same fail-closed state.  A boot
//         where Auth.init() itself throws shows the static fail-closed
//         note as well.  Further boots show the empty and failed texts
//         for their mocked responses
//   Identity  the criteria concern roles, so the proof also runs a
//         non-admin pass (role 'user') booted the production way: the
//         token in the URL hash (#access_token=...), /api/auth/config
//         and /api/auth/me mocked for that user, and the hash token
//         reaching /api/auth/me as a Bearer header while the page still
//         renders with the admin-only control absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const USER_ME = {
  authenticated: true,
  user: { id: 9, username: 'user', roles: ['user'] },
};

// Four events across two entity types (dataset, source), deliberately in
// a mixed server order that is neither newest-first nor lexicographic.
// Timestamps mix ISO strings and numeric epoch (seconds) values:
//   E_new  2026-10-02T00:00:00Z  (epoch seconds 1790899200)  dataset
//   E2     2026-10-01T08:00:00Z  (ISO string)                source
//   E3     2026-09-20T12:30:00+00:00 (ISO string)            dataset
//   E_old  2025-12-31T23:59:59Z  (epoch seconds 1767225599)  source
// True chronological newest-first order: E_new, E2, E3, E_old.
// A lexicographic string sort would give E2, E3, E_new, E_old instead.
// E2 has no actor username (actor_sub must be shown) and E_old's details
// carry an XSS payload that must render as inert text only.
const EVENTS = [
  {
    id: 2,
    entity_type: 'dataset',
    entity_id: 'ds-orders',
    action: 'delete',
    actor_sub: 'sub-admin-0001',
    actor_username: 'admin',
    actor_email: 'admin@example.com',
    actor_roles: 'admin',
    timestamp: '2026-09-20T12:30:00+00:00',
    details: {},
  },
  {
    id: 1,
    entity_type: 'source',
    entity_id: 'src-legacy',
    action: 'create',
    actor_sub: 'sub-admin-0001',
    actor_username: 'admin',
    actor_email: 'admin@example.com',
    actor_roles: 'admin',
    timestamp: 1767225599,
    details: { note: '<img src=x onerror=alert(1)>' },
  },
  {
    id: 4,
    entity_type: 'dataset',
    entity_id: 'ds-payments',
    action: 'update',
    actor_sub: 'sub-admin-0001',
    actor_username: 'admin',
    actor_email: 'admin@example.com',
    actor_roles: 'admin',
    timestamp: 1790899200,
    details: { field: 'amount', reason: 'manual fix' },
  },
  {
    id: 3,
    entity_type: 'source',
    entity_id: 'src-orders',
    action: 'create',
    actor_sub: 'sub-svc-42',
    actor_username: null,
    actor_email: 'svc@example.com',
    actor_roles: 'service',
    timestamp: '2026-10-01T08:00:00Z',
    details: { endpoint: 'https://orders.acme.internal/v2' },
  },
];

const XSS_PAYLOAD = '<img src=x onerror=alert(1)>';

// Phase switches for the single mock.
let meBody = ADMIN_ME;
let meStatus = 200; // 200 | 500
let auditMode = 'ok'; // 'ok' | 'empty' | 'error'
let meAuthorization = [];
let auditRequests = [];
let writeRequests = [];

test('issue754 freeform', async ({ page }) => {
  await page.route('**/api/**', async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    const pathname = new URL(url).pathname;
    if (method !== 'GET' && method !== 'HEAD') {
      writeRequests.push({ method, url });
    }

    if (pathname === '/api/auth/config') {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (pathname === '/api/auth/me') {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorization.push(auth);
      if (meStatus === 500) {
        return route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ detail: 'identity provider unavailable' }),
        });
      }
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (pathname === '/api/audit') {
      auditRequests.push(url);
      if (method !== 'GET') {
        return route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ detail: 'no' }) });
      }
      if (auditMode === 'empty') {
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
      }
      if (auditMode === 'error') {
        return route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ detail: 'audit storage unavailable' }),
        });
      }
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(EVENTS),
      });
    }
    // Every other /api/** request is mocked with an empty list.
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // ------------------------------------------------------------------
  // Phase 1 — admin boot (roles: ["admin"]): GET /api/audit?limit=100
  // renders the filter row + events table inside the
  // data-requires-role="admin" element, newest first chronologically
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=audit');

  // the module is loaded and defines const AuditView with an init().
  // A top-level `const` is a global lexical binding, NOT a property of
  // window: the global is reachable by bare name, and nothing named
  // AuditView exists on window itself.
  expect(await page.locator('script[src="js/audit.js"]').count()).toBe(1);
  expect(
    await page.evaluate(
      () => typeof AuditView !== 'undefined' && typeof AuditView.init === 'function'
    )
  ).toBe(true);
  expect(await page.evaluate(() => window.AuditView === undefined)).toBe(true);

  const section = page.locator('[data-panel="audit"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Audit history');

  // the admin content is rendered inside a data-requires-role="admin"
  // element: filter row first, then the table, in document order
  const adminWrapper = section.locator('[data-requires-role="admin"]');
  await expect(adminWrapper).toHaveCount(1);
  await expect(adminWrapper.locator('[data-testid="audit-filter-row"]')).toBeVisible();
  await expect(adminWrapper.locator('[data-testid="audit-table"]')).toBeVisible();

  // the filter row is a block element holding the entity-type select
  const filterRowInfo = await page.evaluate(() => {
    const el = document.querySelector('[data-panel="audit"] [data-testid="audit-filter-row"]');
    return {
      tag: el.tagName,
      display: getComputedStyle(el).display,
      hasSelect: !!el.querySelector('select'),
    };
  });
  expect(filterRowInfo.tag).toBe('DIV');
  expect(filterRowInfo.display).toBe('block');
  expect(filterRowInfo.hasSelect).toBe(true);

  // the select lists "All entity types" plus each distinct entity type
  const select = page.locator('[data-testid="audit-entity-type-filter"]');
  await expect(select.locator('option')).toHaveText(['All entity types', 'dataset', 'source']);
  expect(
    await page.evaluate(() =>
      Array.from(document.querySelectorAll('[data-testid="audit-entity-type-filter"] option')).map((o) => o.value)
    )
  ).toEqual(['', 'dataset', 'source']);

  // the table has one row per event, newest first in TRUE chronological
  // order — the mocked server order and a lexicographic string order
  // both differ from this
  const rows = page.locator('[data-testid="audit-row"]');
  await expect(rows).toHaveCount(4);

  // the time cell shows a deterministic UTC-formatted time
  // ("YYYY-MM-DD HH:MM:SS UTC"): numeric epoch seconds and ISO strings
  // both format to the same human-readable moment, and the raw
  // timestamp value is never shown
  const rowTimes = [
    '2026-10-02 00:00:00 UTC',       // E_new:  1790899200 (numeric epoch seconds)
    '2026-10-01 08:00:00 UTC',       // E2:     '2026-10-01T08:00:00Z' (ISO string)
    '2026-09-20 12:30:00 UTC',       // E3:     '2026-09-20T12:30:00+00:00' (ISO string with offset)
    '2025-12-31 23:59:59 UTC',       // E_old:  1767225599 (numeric epoch seconds)
  ];
  for (let i = 0; i < 4; i++) {
    await expect(rows.nth(i).locator('[data-testid="audit-time"]')).toHaveText(rowTimes[i]);
  }
  // ...and no time cell carries the raw timestamp value
  expect(
    await page.evaluate(() =>
      Array.from(document.querySelectorAll('[data-testid="audit-time"]')).every(
        (td) =>
          !['1790899200', '2026-10-01T08:00:00Z', '2026-09-20T12:30:00+00:00', '1767225599'].includes(
            td.textContent
          )
      )
    )
  ).toBe(true);
  await expect(rows.nth(0).locator('[data-testid="audit-action"]')).toHaveText('update');
  await expect(rows.nth(0).locator('[data-testid="audit-entity-type"]')).toHaveText('dataset');
  await expect(rows.nth(0).locator('[data-testid="audit-entity-id"]')).toHaveText('ds-payments');
  await expect(rows.nth(0).locator('[data-testid="audit-actor"]')).toHaveText('admin');
  await expect(rows.nth(0).locator('[data-testid="audit-details"]')).toHaveText('field: amount; reason: manual fix');

  await expect(rows.nth(1).locator('[data-testid="audit-action"]')).toHaveText('create');
  await expect(rows.nth(1).locator('[data-testid="audit-entity-type"]')).toHaveText('source');
  await expect(rows.nth(1).locator('[data-testid="audit-entity-id"]')).toHaveText('src-orders');
  // the no-username event shows its actor_sub (never the email)
  await expect(rows.nth(1).locator('[data-testid="audit-actor"]')).toHaveText('sub-svc-42');
  await expect(rows.nth(1).locator('[data-testid="audit-details"]')).toHaveText(
    'endpoint: https://orders.acme.internal/v2'
  );

  await expect(rows.nth(2).locator('[data-testid="audit-action"]')).toHaveText('delete');
  await expect(rows.nth(2).locator('[data-testid="audit-entity-id"]')).toHaveText('ds-orders');
  expect(await rows.nth(2).locator('[data-testid="audit-details"]').innerText()).toBe('');

  await expect(rows.nth(3).locator('[data-testid="audit-action"]')).toHaveText('create');
  await expect(rows.nth(3).locator('[data-testid="audit-entity-id"]')).toHaveText('src-legacy');
  // the XSS payload in details renders as inert "key: value" text
  await expect(rows.nth(3).locator('[data-testid="audit-details"]')).toHaveText(
    'note: ' + XSS_PAYLOAD
  );

  // the admin read went through the API client with limit=100
  expect(auditRequests).toHaveLength(1);
  expect(auditRequests[0]).toContain('/api/audit?limit=100');

  // no actor email appears in the page text or the serialized DOM
  expect(await page.evaluate(() => document.body.innerText.includes('example.com'))).toBe(false);
  expect(await page.evaluate(() => document.documentElement.outerHTML.includes('example.com'))).toBe(false);

  // the <img> payload appears only as text: no <img> element exists and
  // the serialized DOM carries it escaped, not as markup
  expect(await page.evaluate(() => document.querySelectorAll('img').length)).toBe(0);
  expect(await page.evaluate((payload) => document.body.innerText.includes(payload), XSS_PAYLOAD)).toBe(true);
  expect(
    await page.evaluate(
      (payload) =>
        document.documentElement.outerHTML.includes(
          'note: &lt;img src=x onerror=alert(1)&gt;'
        ) && !document.documentElement.outerHTML.includes(payload),
      XSS_PAYLOAD
    )
  ).toBe(true);

  // the filter row precedes the table in document order (not by pixels);
  // Node.DOCUMENT_POSITION_PRECEDING is 0x02
  expect(
    await page.evaluate(() => {
      const filterRow = document.querySelector('[data-testid="audit-filter-row"]');
      const table = document.querySelector('[data-testid="audit-table"]');
      return {
        preceding: table.compareDocumentPosition(filterRow) & 0x02,
        following: filterRow.compareDocumentPosition(table) & 0x04,
      };
    })
  ).toEqual({ preceding: 0x02, following: 0x04 });

  // the select filters to one entity type ...
  await select.selectOption('source');
  await expect(rows).toHaveCount(2);
  expect(await rows.nth(0).locator('[data-testid="audit-entity-id"]').innerText()).toBe('src-orders');
  expect(await rows.nth(1).locator('[data-testid="audit-entity-id"]').innerText()).toBe('src-legacy');
  await select.selectOption('dataset');
  await expect(rows).toHaveCount(2);
  expect(await rows.nth(0).locator('[data-testid="audit-entity-id"]').innerText()).toBe('ds-payments');
  expect(await rows.nth(1).locator('[data-testid="audit-entity-id"]').innerText()).toBe('ds-orders');
  // ... and "All entity types" shows them all again, in the same order
  await select.selectOption('');
  await expect(rows).toHaveCount(4);
  await expect(rows.nth(0).locator('[data-testid="audit-time"]')).toHaveText('2026-10-02 00:00:00 UTC');
  await expect(rows.nth(3).locator('[data-testid="audit-time"]')).toHaveText('2025-12-31 23:59:59 UTC');

  // nothing in the section changes data: no interactive controls beyond
  // the read-only filter select
  expect(await section.locator('form, button, input, a[href]').count()).toBe(0);

  // ------------------------------------------------------------------
  // Phase 2 — identity: a user with roles: ["user"] booted the
  // production way (token in the URL hash, /api/auth/config and
  // /api/auth/me mocked for that user) sees the administrators-only
  // text, no data-requires-role="admin" element, and no /api/audit
  // request — while the page still renders
  // ------------------------------------------------------------------
  meBody = USER_ME;
  meAuthorization.length = 0;
  auditRequests.length = 0;
  // A fragment-only URL change would be a same-document navigation and
  // Auth.init() would not re-run; go through about:blank so this boot is
  // a full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit#access_token=user-token-754');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer user-token-754');
  // the page still renders its other panels ...
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policies-empty"]')).toHaveText(
    'No retention policies yet.'
  );
  // ... the audit section shows only the administrators-only text ...
  await expect(section).toBeVisible();
  await expect(section.locator('[data-testid="audit-admin-only-note"]')).toHaveText(
    'Audit history is available to administrators.'
  );
  await expect(section.locator('[data-requires-role="admin"]')).toHaveCount(0);
  await expect(section.locator('[data-testid="audit-table"]')).toHaveCount(0);
  // ... and no request reached /api/audit
  expect(auditRequests).toHaveLength(0);

  // ------------------------------------------------------------------
  // Phase 3 — /api/auth/me answers 500 so Auth.init() fails: the same
  // fail-closed state (administrators-only text, no admin element, no
  // /api/audit request)
  // ------------------------------------------------------------------
  meStatus = 500;
  auditRequests.length = 0;
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit');
  await expect(section).toBeVisible();
  await expect(section.locator('[data-testid="audit-admin-only-note"]')).toHaveText(
    'Audit history is available to administrators.'
  );
  await expect(section.locator('[data-requires-role="admin"]')).toHaveCount(0);
  await expect(section.locator('[data-testid="audit-table"]')).toHaveCount(0);
  expect(auditRequests).toHaveLength(0);

  // ------------------------------------------------------------------
  // Phase 4 — Auth.init() itself throws: the section's static
  // fail-closed note remains (init never runs), no admin element is
  // rendered and no /api/audit request is made
  // ------------------------------------------------------------------
  meStatus = 200;
  meBody = ADMIN_ME;
  auditRequests.length = 0;
  // Init scripts run before the page's own scripts, so the
  // DOMContentLoaded listener below is registered first and installs
  // the throwing stub before Studio boot ever runs.  The stub is armed
  // through a sessionStorage flag: Playwright has no API to remove an
  // added init script, so the flag scopes the stub to exactly this
  // boot (it is cleared again before the next navigation).
  const throwAuthInit = () => {
    let armed = false;
    try { armed = sessionStorage.getItem('audit-throw-init') === '1'; } catch (e) {}
    if (!armed) return;
    const apply = () => {
      // auth.js declares `const Auth` at the top level: a global lexical
      // binding, not a property of window, so the stub must patch the
      // object through the global name.  The first pass (before auth.js
      // has parsed) is a no-op; the DOMContentLoaded pass runs after
      // every classic script, so the stub is installed before Studio
      // boot.
      if (typeof Auth !== 'undefined' && !window.__auditAuthStubbed) {
        window.__auditAuthStubbed = true;
        Auth.init = function () {
          throw new Error('stubbed auth failure');
        };
      }
    };
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', apply, { once: true });
    }
    apply();
  };
  await page.addInitScript(throwAuthInit);
  await page.evaluate(() => { sessionStorage.setItem('audit-throw-init', '1'); });
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit');
  await page.evaluate(() => { sessionStorage.removeItem('audit-throw-init'); });
  // Auth.init() threw, so Studio boot never reached any module init ...
  await expect(page.locator('[data-testid="auth-status"]')).toHaveText(
    'Authentication failed: stubbed auth failure'
  );
  // ... the audit section still renders (other panels render too) ...
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  await expect(section).toBeVisible();
  // ... and shows only the static fail-closed note with no admin
  // element, and no request reached /api/audit
  await expect(section.locator('[data-testid="audit-admin-only-note"]')).toHaveText(
    'Audit history is available to administrators.'
  );
  await expect(section.locator('[data-requires-role="admin"]')).toHaveCount(0);
  await expect(section.locator('[data-testid="audit-table"]')).toHaveCount(0);
  expect(auditRequests).toHaveLength(0);

  // ------------------------------------------------------------------
  // Phase 5 — admin boot with an empty list: "No audit events yet."
  // ------------------------------------------------------------------
  auditMode = 'empty';
  auditRequests.length = 0;
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit');
  await expect(section.locator('[data-testid="audit-empty"]')).toHaveText('No audit events yet.');
  await expect(section.locator('[data-testid="audit-table"]')).toHaveCount(0);
  expect(auditRequests).toHaveLength(1);

  // ------------------------------------------------------------------
  // Phase 6 — admin boot with a 500: "Could not load audit history."
  // ------------------------------------------------------------------
  auditMode = 'error';
  auditRequests.length = 0;
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit');
  await expect(section.locator('[data-testid="audit-error"]')).toHaveText('Could not load audit history.');
  await expect(section.locator('[data-testid="audit-table"]')).toHaveCount(0);
  expect(auditRequests).toHaveLength(1);

  // the section never wrote data in any phase
  expect(writeRequests).toEqual([]);
});
