'use strict';

// Proof for issue #729 — admin add/delete controls on the Data retention
// panel (app/js/retention.js).
//
// Boots /studio.html?panel=retention as an admin with /api/auth/config,
// /api/auth/me, /api/datasets (two datasets) and /api/retention-policies
// mocked, and records every POST and DELETE, proving:
//   AC-1  the section shows an "Add policy" button carrying
//         data-requires-role="admin"; clicking it shows the form
//         data-testid="retention-policy-form" with a required text name, a
//         table-class select (connection_tests, runs, discovery_runs,
//         ingested_records, field_profiles), an action select (purge,
//         anonymize), a required number period with minimum 1, a scope
//         select (class, dataset), a dataset select filled from
//         GET /api/datasets (each name as label, its id as value) shown
//         only when scope is dataset, and an Enabled checkbox checked by
//         default; saving posts POST /api/retention-policies with exactly
//         { name, table_class, action, retention_period_days (a number),
//         scope, dataset_id, is_enabled } — the chosen dataset's id when
//         dataset-scoped, null when class-scoped; an empty name or a period
//         below 1 shows data-testid="retention-form-error" without sending
//         a request; a 422 with a detail shows that detail (as inert text)
//         and keeps the form open; a failed GET /api/datasets keeps the
//         form available for scope=class, disables the dataset select for
//         scope=dataset, and saving then shows "Could not load datasets."
//         without sending a request; on success the form closes and the
//         policies table reloads
//   AC-2  each policy row has a "Delete" button carrying
//         data-requires-role="admin"; clicking it replaces the button with
//         the text "Delete <policy name>?" and the "Confirm delete" and
//         "Cancel" buttons; Confirm sends exactly one
//         DELETE /api/retention-policies/<id> and reloads the table; Cancel
//         restores the row unchanged without sending a request; a failed
//         delete shows "Could not delete the policy." in the row; clicking
//         Delete or its confirmation never selects the row
//   AC-3  booting as a user with roles: ["viewer"] renders neither the
//         "Add policy" button nor any "Delete" button
//   Identity  the viewer boot is the production way: the token in the URL
//         hash (#access_token=...), /api/auth/config and /api/auth/me
//         mocked for that user, and the hash token reaching /api/auth/me
//         as a Bearer header while the page still renders

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const VIEWER_ME = {
  authenticated: true,
  user: { id: 7, username: 'viewer', roles: ['viewer'] },
};

const DATASETS = [
  {
    id: 'ds-orders',
    name: 'Orders',
    object_type: 'table',
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
  {
    id: 'ds-payments',
    name: 'Payments',
    object_type: 'table',
    created_at: '2026-09-02T00:00:00',
    updated_at: '2026-09-02T00:00:00',
  },
];

// In-memory policy store: the mocked POST appends and the mocked DELETE
// removes, so the table reloads after each mutation are observable.
let policies = [
  {
    id: 'pol-1',
    name: 'Purge stale audit rows',
    dataset_id: 'ds-orders',
    table_class: 'runs',
    action: 'purge',
    retention_period_days: 30,
    scope: 'dataset',
    is_enabled: true,
  },
  {
    id: 'pol-2',
    name: 'Anonymize export PII',
    dataset_id: null,
    table_class: 'ingested_records',
    action: 'anonymize',
    retention_period_days: 90,
    scope: 'class',
    is_enabled: false,
  },
];

// Phase switches for the single mock.
let meBody = ADMIN_ME;
let datasetsFail = false;
let postResponse = null; // { status, body } override for POSTs
let deleteFail = false;
let createdCount = 0;

test('issue729 freeform', async ({ page }) => {
  // Every POST and DELETE the page sends is recorded here.
  const postRequests = [];
  const deleteRequests = [];
  const meAuthorization = [];
  const retentionPosts = () =>
    postRequests.filter((r) => r.url.includes('/api/retention-policies'));
  const retentionDeletes = () =>
    deleteRequests.filter((r) => r.url.includes('/api/retention-policies'));

  await page.route('**/api/**', async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    if (method === 'POST') {
      postRequests.push({ url, body: request.postData() || null });
    }
    if (method === 'DELETE') {
      deleteRequests.push({ url });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorization.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (url.includes('/api/datasets')) {
      if (datasetsFail) {
        return route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ detail: 'datasets unavailable' }),
        });
      }
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(DATASETS),
      });
    }
    if (url.includes('/api/retention-policies')) {
      if (method === 'GET') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(policies),
        });
      }
      if (method === 'POST') {
        if (postResponse) {
          return route.fulfill({
            status: postResponse.status,
            contentType: 'application/json',
            body: JSON.stringify(postResponse.body),
          });
        }
        const created = JSON.parse(request.postData());
        created.id = 'pol-new-' + (createdCount += 1);
        policies.push(created);
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(created),
        });
      }
      if (method === 'DELETE') {
        if (deleteFail) {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 'delete blew up' }),
          });
        }
        const id = decodeURIComponent(
          url.split('/api/retention-policies/')[1].split(/[?#]/)[0]
        );
        policies = policies.filter((p) => String(p.id) !== id);
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: '{}',
        });
      }
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // ------------------------------------------------------------------
  // Phase 1 — admin boot: the section shows the "Add policy" button and
  // every policy row a "Delete" button, both admin-marked
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=retention');
  const addBtn = page.locator('[data-testid="retention-add-policy"]');
  await expect(addBtn).toBeVisible();
  await expect(addBtn).toHaveText('Add policy');
  await expect(addBtn).toHaveAttribute('data-requires-role', 'admin');
  await expect(page.locator('[data-testid="retention-policy-table"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policy-row"]')).toHaveCount(2);
  const deleteButtons = page.locator('[data-testid="retention-policy-delete"]');
  await expect(deleteButtons).toHaveCount(2);
  await expect(deleteButtons.first()).toHaveAttribute('data-requires-role', 'admin');

  // ------------------------------------------------------------------
  // Phase 2 — adding a dataset-scoped policy posts exactly the mandated
  // fields with the chosen dataset's id; the form closes and the table
  // reloads with the new row
  // ------------------------------------------------------------------
  await addBtn.click();
  const form = page.locator('[data-testid="retention-policy-form"]');
  await expect(form).toBeVisible();

  // Field contract: name is a required text input ...
  expect(await form.locator('[data-testid="retention-form-name"]').getAttribute('type')).toBe('text');
  expect(await form.locator('[data-testid="retention-form-name"]').getAttribute('required')).not.toBeNull();
  // ... table class, action and scope are fixed selects ...
  expect(await form.locator('[data-testid="retention-form-table-class"] option').allTextContents()).toEqual(
    ['connection_tests', 'runs', 'discovery_runs', 'ingested_records', 'field_profiles']
  );
  expect(await form.locator('[data-testid="retention-form-action"] option').allTextContents()).toEqual([
    'purge',
    'anonymize',
  ]);
  expect(await form.locator('[data-testid="retention-form-scope"] option').allTextContents()).toEqual([
    'class',
    'dataset',
  ]);
  // ... the period is a required number with minimum 1 ...
  expect(await form.locator('[data-testid="retention-form-period"]').getAttribute('type')).toBe('number');
  expect(await form.locator('[data-testid="retention-form-period"]').getAttribute('required')).not.toBeNull();
  expect(await form.locator('[data-testid="retention-form-period"]').getAttribute('min')).toBe('1');
  // ... Enabled is checked by default ...
  await expect(form.locator('[data-testid="retention-form-enabled"]')).toBeChecked();
  // ... and the dataset select is hidden while scope is class.
  await expect(form.locator('[data-testid="retention-form-dataset"]')).toBeHidden();

  await form.locator('[data-testid="retention-form-name"]').fill('Purge connection tests');
  await form.locator('[data-testid="retention-form-table-class"]').selectOption('runs');
  await form.locator('[data-testid="retention-form-action"]').selectOption('purge');
  await form.locator('[data-testid="retention-form-period"]').fill('30');
  await form.locator('[data-testid="retention-form-scope"]').selectOption('dataset');
  // scope=dataset reveals the dataset select, filled from GET /api/datasets:
  // each dataset's name as label with its id as value.
  await expect(form.locator('[data-testid="retention-form-dataset"]')).toBeVisible();
  expect(
    await form
      .locator('[data-testid="retention-form-dataset"] option')
      .evaluateAll((options) =>
        options.map((option) => ({ label: option.textContent, value: option.value }))
      )
  ).toEqual([
    { label: 'Orders', value: 'ds-orders' },
    { label: 'Payments', value: 'ds-payments' },
  ]);
  await form.locator('[data-testid="retention-form-dataset"]').selectOption('ds-payments');
  await form.locator('[data-testid="retention-form-save"]').click();

  await expect.poll(() => retentionPosts()).toHaveLength(1);
  expect(retentionPosts()[0].url.endsWith('/api/retention-policies')).toBe(true);
  expect(JSON.parse(retentionPosts()[0].body)).toEqual({
    name: 'Purge connection tests',
    table_class: 'runs',
    action: 'purge',
    retention_period_days: 30,
    scope: 'dataset',
    dataset_id: 'ds-payments',
    is_enabled: true,
  });
  // retention_period_days went over the wire as a JSON number, not a string
  expect(retentionPosts()[0].body).toContain('"retention_period_days":30');
  // the form closed and the policies table reloaded with the new row
  await expect(page.locator('[data-testid="retention-policy-form"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-form-error"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-row"][data-id="pol-new-1"]')).toBeVisible();

  // ------------------------------------------------------------------
  // Phase 3 — a class-scoped policy posts dataset_id null (and is_enabled
  // follows the checkbox)
  // ------------------------------------------------------------------
  await page.locator('[data-testid="retention-add-policy"]').click();
  const classForm = page.locator('[data-testid="retention-policy-form"]');
  await classForm.locator('[data-testid="retention-form-name"]').fill('Anonymize field profiles');
  await classForm.locator('[data-testid="retention-form-table-class"]').selectOption('field_profiles');
  await classForm.locator('[data-testid="retention-form-action"]').selectOption('anonymize');
  await classForm.locator('[data-testid="retention-form-period"]').fill('14');
  await classForm.locator('[data-testid="retention-form-enabled"]').uncheck();
  await classForm.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => retentionPosts()).toHaveLength(2);
  expect(JSON.parse(retentionPosts()[1].body)).toEqual({
    name: 'Anonymize field profiles',
    table_class: 'field_profiles',
    action: 'anonymize',
    retention_period_days: 14,
    scope: 'class',
    dataset_id: null,
    is_enabled: false,
  });
  await expect(page.locator('[data-testid="retention-policy-row"][data-id="pol-new-2"]')).toBeVisible();

  // ------------------------------------------------------------------
  // Phase 4 — an empty name (and a period below 1) shows the form error
  // without sending a request
  // ------------------------------------------------------------------
  await page.locator('[data-testid="retention-add-policy"]').click();
  const badForm = page.locator('[data-testid="retention-policy-form"]');
  const formError = page.locator('[data-testid="retention-form-error"]');
  await expect(formError).toBeHidden();
  await badForm.locator('[data-testid="retention-form-period"]').fill('7');
  // name left empty
  await badForm.locator('[data-testid="retention-form-save"]').click();
  expect(retentionPosts()).toHaveLength(2); // no new POST
  await expect(formError).toBeVisible();
  await expect(formError).toHaveText('Name is required.');
  await expect(badForm).toBeVisible(); // the form stayed open
  // a period below 1 is blocked the same way
  await badForm.locator('[data-testid="retention-form-name"]').fill('Some policy');
  await badForm.locator('[data-testid="retention-form-period"]').fill('0');
  await badForm.locator('[data-testid="retention-form-save"]').click();
  expect(retentionPosts()).toHaveLength(2); // still no POST
  await expect(formError).toHaveText('Retention period must be at least 1 day.');
  await expect(badForm).toBeVisible();

  // ------------------------------------------------------------------
  // Phase 5 — a 422 with a detail shows that detail in the (still open)
  // form, rendered as inert text
  // ------------------------------------------------------------------
  const hostileDetail = 'Policy <script>window.__retPwned=1<\/script> name taken';
  postResponse = { status: 422, body: { detail: hostileDetail } };
  await badForm.locator('[data-testid="retention-form-name"]').fill('Conflict policy');
  await badForm.locator('[data-testid="retention-form-period"]').fill('3');
  await badForm.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => retentionPosts()).toHaveLength(3);
  await expect(formError).toHaveText(hostileDetail);
  await expect(badForm).toBeVisible(); // the form stayed open
  expect(await page.evaluate(() => window.__retPwned === 1)).toBe(false);
  expect(
    await page.evaluate(
      () => document.querySelectorAll('[data-testid="retention-form-error"] script').length
    )
  ).toBe(0);
  // a subsequent valid save from the same open form succeeds and closes it
  postResponse = null;
  await badForm.locator('[data-testid="retention-form-name"]').fill('Kept policy');
  await badForm.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => retentionPosts()).toHaveLength(4);
  await expect(page.locator('[data-testid="retention-policy-form"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-row"][data-id="pol-new-3"]')).toBeVisible();

  // ------------------------------------------------------------------
  // Phase 6 — delete: Confirm sends exactly one DELETE for the policy id
  // and reloads the table; Cancel restores the row unchanged without
  // sending; a failed delete shows the row error; neither the Delete click
  // nor its confirmation selects the row
  // ------------------------------------------------------------------
  const rowPol1 = page.locator('[data-testid="retention-policy-row"][data-id="pol-1"]');
  await rowPol1.locator('[data-testid="retention-policy-delete"]').click();
  // the button was replaced by the confirmation text plus two buttons
  await expect(rowPol1.locator('[data-testid="retention-policy-delete"]')).toHaveCount(0);
  await expect(rowPol1.locator('[data-testid="retention-policy-delete-text"]')).toHaveText(
    'Delete Purge stale audit rows?'
  );
  await expect(rowPol1.locator('[data-testid="retention-policy-delete-confirm"]')).toHaveText('Confirm delete');
  await expect(rowPol1.locator('[data-testid="retention-policy-delete-cancel"]')).toHaveText('Cancel');
  // clicking Delete did not select the row and sent nothing
  await expect(rowPol1).not.toHaveClass(/wh-retention-row-selected/);
  expect(await rowPol1.getAttribute('data-selected')).toBeNull();
  expect(retentionDeletes()).toHaveLength(0);

  await rowPol1.locator('[data-testid="retention-policy-delete-confirm"]').click();
  await expect.poll(() => retentionDeletes()).toHaveLength(1); // exactly one DELETE ...
  expect(retentionDeletes()[0].url.endsWith('/api/retention-policies/pol-1')).toBe(true);
  // ... for the right id, and the table reloaded without pol-1
  await expect(page.locator('[data-testid="retention-policy-row"][data-id="pol-1"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-row"]')).toHaveCount(4);

  // Cancel restores the row unchanged without sending a request
  const rowPol2 = page.locator('[data-testid="retention-policy-row"][data-id="pol-2"]');
  await rowPol2.locator('[data-testid="retention-policy-delete"]').click();
  await expect(rowPol2.locator('[data-testid="retention-policy-delete-text"]')).toHaveText(
    'Delete Anonymize export PII?'
  );
  await rowPol2.locator('[data-testid="retention-policy-delete-cancel"]').click();
  await expect(rowPol2.locator('[data-testid="retention-policy-delete"]')).toHaveCount(1);
  await expect(rowPol2.locator('[data-testid="retention-policy-delete-text"]')).toHaveCount(0);
  expect(retentionDeletes()).toHaveLength(1); // Cancel sent nothing
  await expect(rowPol2).not.toHaveClass(/wh-retention-row-selected/);

  // a failed delete shows the error in the row (and the confirm click did
  // not select it)
  deleteFail = true;
  const rowNew1 = page.locator('[data-testid="retention-policy-row"][data-id="pol-new-1"]');
  await rowNew1.locator('[data-testid="retention-policy-delete"]').click();
  await rowNew1.locator('[data-testid="retention-policy-delete-confirm"]').click();
  await expect.poll(() => retentionDeletes()).toHaveLength(2);
  expect(retentionDeletes()[1].url.endsWith('/api/retention-policies/pol-new-1')).toBe(true);
  await expect(rowNew1.locator('[data-testid="retention-policy-delete-error"]')).toHaveText(
    'Could not delete the policy.'
  );
  // the row is still there with a fresh Delete button
  await expect(rowNew1.locator('[data-testid="retention-policy-delete"]')).toHaveCount(1);
  await expect(rowNew1).not.toHaveClass(/wh-retention-row-selected/);
  deleteFail = false;

  // ------------------------------------------------------------------
  // Phase 7 — failed GET /api/datasets: the form stays available for
  // scope=class; for scope=dataset the select is disabled and saving
  // shows "Could not load datasets." without sending a request
  // ------------------------------------------------------------------
  datasetsFail = true;
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=retention');
  await expect(page.locator('[data-testid="retention-policy-table"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policy-row"]')).toHaveCount(4);

  await page.locator('[data-testid="retention-add-policy"]').click();
  const dsForm = page.locator('[data-testid="retention-policy-form"]');
  await dsForm.locator('[data-testid="retention-form-name"]').fill('Class scope still works');
  await dsForm.locator('[data-testid="retention-form-period"]').fill('45');
  await dsForm.locator('[data-testid="retention-form-save"]').click(); // scope defaults to class
  await expect.poll(() => retentionPosts()).toHaveLength(5);
  expect(JSON.parse(retentionPosts()[4].body)).toMatchObject({
    name: 'Class scope still works',
    scope: 'class',
    dataset_id: null,
  });
  await expect(page.locator('[data-testid="retention-policy-row"][data-id="pol-new-4"]')).toBeVisible();

  await page.locator('[data-testid="retention-add-policy"]').click();
  const dsForm2 = page.locator('[data-testid="retention-policy-form"]');
  await dsForm2.locator('[data-testid="retention-form-name"]').fill('Dataset scope blocked');
  await dsForm2.locator('[data-testid="retention-form-period"]').fill('10');
  await dsForm2.locator('[data-testid="retention-form-scope"]').selectOption('dataset');
  await expect(dsForm2.locator('[data-testid="retention-form-dataset"]')).toBeVisible();
  await expect(dsForm2.locator('[data-testid="retention-form-dataset"]')).toBeDisabled();
  await dsForm2.locator('[data-testid="retention-form-save"]').click();
  expect(retentionPosts()).toHaveLength(5); // no request was sent
  await expect(page.locator('[data-testid="retention-form-error"]')).toHaveText('Could not load datasets.');
  await expect(dsForm2).toBeVisible(); // the form stayed open
  datasetsFail = false;

  // ------------------------------------------------------------------
  // Phase 8 — identity: a user with roles: ["viewer"] booted the
  // production way (token in the URL hash, /api/auth/config and
  // /api/auth/me mocked for that user) sees the page render with neither
  // the "Add policy" button nor any "Delete" button
  // ------------------------------------------------------------------
  meBody = VIEWER_ME;
  meAuthorization.length = 0;
  // A fragment-only URL change would be a same-document navigation and
  // Auth.init() would not re-run; go through about:blank so this boot is a
  // full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=retention#access_token=viewer-token-729');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer viewer-token-729');
  // the page still renders its policies ...
  await expect(page.locator('[data-testid="retention-policy-table"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policy-row"]')).toHaveCount(5);
  await expect(page.locator('[data-testid="retention-policy-row"][data-id="pol-2"]')).toBeVisible();
  // ... but neither admin-only control exists for the viewer
  await expect(page.locator('[data-testid="retention-add-policy"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-delete"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="retention"] [data-requires-role="admin"]')).toHaveCount(0);
  // no other module sent a single POST or DELETE during the whole proof
  expect(
    postRequests.filter((r) => !r.url.includes('/api/retention-policies'))
  ).toHaveLength(0);
  expect(
    deleteRequests.filter((r) => !r.url.includes('/api/retention-policies'))
  ).toHaveLength(0);
});
