'use strict';

// Proof for issue #703 — "Run sweep now" for retention policies in
// app/studio.html (app/js/retention.js).
//
// Boots /studio.html?panel=retention the production way (the token in the
// URL hash as #access_token=..., /api/auth/config and /api/auth/me mocked)
// as an admin with every /api/** request mocked — one enabled purge
// policy, one enabled anonymize policy, one disabled policy — and records
// every POST the page sends. It proves:
//   AC-1  each enabled row (admin) has a "Run sweep now" button carrying
//         data-requires-role="admin" (none for the disabled policy, none
//         for a non-admin); clicking it opens the row's confirmation area
//         data-testid="retention-sweep-confirm" reading "This permanently
//         deletes <table class> records older than <n> days. Type the
//         policy name to confirm." (purge) / "This anonymizes ..."
//         (anonymize), with the name input, the "Run sweep" button
//         (disabled until the input equals the policy name exactly) and
//         the "Cancel" button below; clicking the button does not change
//         the selected row
//   AC-2  "Run sweep" POSTs /api/retention-policies/<id>/sweep with no
//         body; on a 200 the area is replaced by "Sweep <status>: <n>
//         purged, <n> anonymized" from the returned run and the policy is
//         selected with its runs reloaded (the new run shows); a 409
//         shows "A sweep for this policy is already running."
//   AC-3  the disabled policy has no "Run sweep now" button; a wrong
//         name keeps "Run sweep" disabled and sends nothing; the exact
//         name sends exactly one POST to that policy's /sweep and the
//         result shows "Sweep succeeded: 12 purged, 0 anonymized" for a
//         mocked run with those values; "Cancel" sends nothing
//   ID    non-admin passes (issue #750 identity: the criteria concern
//         roles): after full reloads, a user with roles ["viewer"] (AC-3)
//         and a user with roles ["user"] each boot the page the
//         production way for their token and see no "Run sweep now"
//         button while the panel still renders

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { auth_mode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const VIEWER_ME = {
  authenticated: true,
  user: { id: 9, username: 'viewer', roles: ['viewer'] },
};
const USER_ME = {
  authenticated: true,
  user: { id: 10, username: 'user', roles: ['user'] },
};

const ADMIN_TOKEN = 'admin-token-703';
const VIEWER_TOKEN = 'viewer-token-703';
const USER_TOKEN = 'user-token-703';

// One enabled purge policy, one enabled anonymize policy, one disabled
// policy (AC-3 fixture).
const POLICIES = [
  {
    id: 'pol-purge',
    name: 'Purge stale audit rows',
    dataset_id: 'ds-audit',
    table_class: 'audit',
    action: 'purge',
    retention_period_days: 30,
    scope: 'rows',
    is_enabled: true,
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
  {
    id: 'pol-anon',
    name: 'Anonymize export PII',
    dataset_id: 'ds-exports',
    table_class: 'exports',
    action: 'anonymize',
    retention_period_days: 90,
    scope: 'columns',
    is_enabled: true,
    created_at: '2026-09-02T00:00:00',
    updated_at: '2026-09-02T00:00:00',
  },
  {
    id: 'pol-off',
    name: 'Disabled sweep policy',
    dataset_id: 'ds-logs',
    table_class: 'logs',
    action: 'purge',
    retention_period_days: 7,
    scope: 'rows',
    is_enabled: false,
    created_at: '2026-09-03T00:00:00',
    updated_at: '2026-09-03T00:00:00',
  },
];

// The run the mocked sweep returns for pol-purge: the result line must be
// built from ITS status, records_purged and records_anonymized.
const SWEEP_RUN = {
  id: 'run-sweep-703',
  policy_id: 'pol-purge',
  name: 'Manual sweep (issue703)',
  trigger: 'manual',
  status: 'succeeded',
  records_purged: 12,
  records_anonymized: 0,
  error_detail: null,
  created_at: '2026-10-07T00:00:00',
  updated_at: '2026-10-07T00:00:00',
};

// The 409 body deliberately differs from the UI text: a 409 must show the
// fixed "already running" line regardless of the response's detail.
const SWEEP_CONFLICT_BODY = { detail: 'another worker holds the sweep lock' };

test('issue703 freeform', async ({ page }) => {
  // ------------------------------------------------------------------
  // Mock every /api/** request and record every POST the page sends.
  // ------------------------------------------------------------------
  const posts = [];
  const meAuthorizations = [];
  let meBody = ADMIN_ME;
  let purgeSwept = false; // the runs list gains SWEEP_RUN after the POST

  await page.route('**/api/**', (route) => {
    const request = route.request();
    const url = request.url();
    if (request.method() === 'POST') {
      posts.push({ url: url, body: request.postData() });
    }
    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorizations.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (
      url.includes('/api/retention-policies') &&
      request.method() === 'POST' &&
      url.includes('/sweep')
    ) {
      if (url.includes('/api/retention-policies/pol-purge/sweep')) {
        purgeSwept = true;
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(SWEEP_RUN),
        });
      }
      if (url.includes('/api/retention-policies/pol-anon/sweep')) {
        return route.fulfill({
          status: 409,
          contentType: 'application/json',
          body: JSON.stringify(SWEEP_CONFLICT_BODY),
        });
      }
      return route.fulfill({
        status: 404,
        contentType: 'application/json',
        body: JSON.stringify({ detail: 'Not Found' }),
      });
    }
    if (url.includes('/api/retention-policies')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(POLICIES),
      });
    }
    if (url.includes('/api/retention-runs')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(purgeSwept ? [SWEEP_RUN] : []),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // ------------------------------------------------------------------
  // Phase A — admin boot (production way: the token in the URL hash),
  // three policies: purge enabled, anonymize enabled, one disabled.
  // ------------------------------------------------------------------
  await page.goto(
    '/studio.html?panel=retention&pass=admin#access_token=' + encodeURIComponent(ADMIN_TOKEN)
  );
  // The boot proves the hash token was picked up the production way:
  // Auth.init() migrates it and it arrives on /api/auth/me.
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + ADMIN_TOKEN);

  const section = page.locator('section[data-panel="retention"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Data retention');
  const rows = page.locator('[data-testid="retention-policy-row"]');
  await expect(rows).toHaveCount(3);
  const purgeRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-purge"]');
  const anonRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-anon"]');
  const offRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-off"]');

  // AC-3: the disabled policy has no "Run sweep now" button; AC-1: each
  // enabled row has exactly one, carrying the admin role marker.
  await expect(offRow.locator('[data-testid="retention-policy-sweep-now"]')).toHaveCount(0);
  const sweepNowButtons = page.locator('[data-testid="retention-policy-sweep-now"]');
  await expect(sweepNowButtons).toHaveCount(2);
  await expect(purgeRow.locator('[data-testid="retention-policy-sweep-now"]')).toHaveCount(1);
  await expect(anonRow.locator('[data-testid="retention-policy-sweep-now"]')).toHaveCount(1);
  await expect(
    purgeRow.locator('[data-testid="retention-policy-sweep-now"]')
  ).toHaveAttribute('data-requires-role', 'admin');
  await expect(
    anonRow.locator('[data-testid="retention-policy-sweep-now"]')
  ).toHaveAttribute('data-requires-role', 'admin');

  // Nothing is selected yet; clicking "Run sweep now" must not select.
  await expect(page.locator('[data-selected="true"]')).toHaveCount(0);
  await purgeRow.locator('[data-testid="retention-policy-sweep-now"]').click();
  const purgeConfirm = purgeRow.locator('[data-testid="retention-sweep-confirm"]');
  await expect(purgeConfirm).toBeVisible();
  // AC-1/AC-3: the purge policy's confirmation shows the
  // "permanently deletes" text with the table class and the period.
  await expect(
    purgeConfirm.locator('[data-testid="retention-sweep-confirm-text"]')
  ).toHaveText(
    'This permanently deletes audit records older than 30 days. Type the policy name to confirm.'
  );
  // AC-1: the confirm area sits in the row with the input, the disabled
  // "Run sweep" button and the "Cancel" button below the sentence.
  const purgeInput = purgeConfirm.locator('[data-testid="retention-sweep-name"]');
  const purgeRunBtn = purgeConfirm.locator('[data-testid="retention-sweep-run"]');
  const purgeCancelBtn = purgeConfirm.locator('[data-testid="retention-sweep-cancel"]');
  await expect(purgeInput).toBeVisible();
  await expect(purgeRunBtn).toBeVisible();
  await expect(purgeRunBtn).toBeDisabled();
  await expect(purgeCancelBtn).toBeVisible();
  // AC-1: clicking the button did not change the selected row.
  await expect(page.locator('[data-selected="true"]')).toHaveCount(0);
  await expect(purgeRow).not.toHaveClass(/wh-retention-row-selected/);

  // AC-3: a wrong name keeps "Run sweep" disabled and sends nothing.
  await purgeInput.fill('wrong name');
  await expect(purgeInput).toHaveValue('wrong name');
  await expect(purgeRunBtn).toBeDisabled();
  expect(posts).toHaveLength(0);

  // AC-3: "Cancel" closes the area without a request and restores the
  // row's actions (the "Run sweep now" button is back).
  await purgeCancelBtn.click();
  await expect(purgeRow.locator('[data-testid="retention-sweep-confirm"]')).toHaveCount(0);
  await expect(purgeRow.locator('[data-testid="retention-policy-sweep-now"]')).toHaveCount(1);
  expect(posts).toHaveLength(0);

  // AC-2/AC-3: the exact name enables "Run sweep" and sends exactly one
  // POST (no body) to that policy's /sweep.
  await purgeRow.locator('[data-testid="retention-policy-sweep-now"]').click();
  const purgeConfirm2 = purgeRow.locator('[data-testid="retention-sweep-confirm"]');
  await expect(purgeConfirm2).toBeVisible();
  await purgeConfirm2.locator('[data-testid="retention-sweep-name"]').fill('Purge stale audit rows');
  await expect(purgeConfirm2.locator('[data-testid="retention-sweep-run"]')).toBeEnabled();
  await purgeConfirm2.locator('[data-testid="retention-sweep-run"]').click();

  await expect.poll(() => posts).toHaveLength(1);
  expect(posts[0].url.endsWith('/api/retention-policies/pol-purge/sweep')).toBe(true);
  expect(posts[0].body).toBeNull();

  // AC-2: on 200 the area is replaced by "Sweep <status>: <n> purged,
  // <n> anonymized" built from the returned run's fields.
  const purgeResult = purgeRow.locator('[data-testid="retention-sweep-result"]');
  await expect(purgeResult).toHaveText('Sweep succeeded: 12 purged, 0 anonymized');
  await expect(purgeRow.locator('[data-testid="retention-sweep-confirm"]')).toHaveCount(0);

  // AC-2: the policy is selected and its runs reloaded, so the new run
  // is shown.
  await expect(purgeRow).toHaveClass(/wh-retention-row-selected/);
  await expect(purgeRow).toHaveAttribute('data-selected', 'true');
  await expect(anonRow).not.toHaveClass(/wh-retention-row-selected/);
  await expect(offRow).not.toHaveClass(/wh-retention-row-selected/);
  const runsArea = page.locator('[data-testid="retention-runs"]');
  await expect(runsArea.locator('[data-testid="retention-run-row"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="retention-run-name"]')).toHaveText('Manual sweep (issue703)');
  await expect(runsArea.locator('[data-testid="retention-run-status"]')).toHaveText('succeeded');
  await expect(runsArea.locator('[data-testid="retention-run-purged"]')).toHaveText('Purged: 12');
  await expect(runsArea.locator('[data-testid="retention-run-anonymized"]')).toHaveText('Anonymized: 0');

  // AC-1/AC-2: the anonymize policy's confirmation reads "This
  // anonymizes ..."; its sweep is refused with a 409, which shows the
  // fixed already-running text (the response's detail is ignored).
  await anonRow.locator('[data-testid="retention-policy-sweep-now"]').click();
  const anonConfirm = anonRow.locator('[data-testid="retention-sweep-confirm"]');
  await expect(anonConfirm).toBeVisible();
  await expect(
    anonConfirm.locator('[data-testid="retention-sweep-confirm-text"]')
  ).toHaveText(
    'This anonymizes exports records older than 90 days. Type the policy name to confirm.'
  );
  await anonConfirm.locator('[data-testid="retention-sweep-name"]').fill('Anonymize export PII');
  await expect(anonConfirm.locator('[data-testid="retention-sweep-run"]')).toBeEnabled();
  await anonConfirm.locator('[data-testid="retention-sweep-run"]').click();

  await expect.poll(() => posts).toHaveLength(2);
  expect(posts[1].url.endsWith('/api/retention-policies/pol-anon/sweep')).toBe(true);
  expect(posts[1].body).toBeNull();
  // AC-3: a 409 shows the already-running text.
  await expect(anonConfirm.locator('[data-testid="retention-sweep-error"]')).toHaveText(
    'A sweep for this policy is already running.'
  );
  // The failed sweep keeps the confirmation open (the name still
  // matches, so "Run sweep" is re-enabled) and never selects the row.
  await expect(anonConfirm).toBeVisible();
  await expect(anonConfirm.locator('[data-testid="retention-sweep-run"]')).toBeEnabled();
  await expect(anonRow).not.toHaveClass(/wh-retention-row-selected/);

  // AC-3: "Cancel" sends nothing.
  await anonConfirm.locator('[data-testid="retention-sweep-cancel"]').click();
  await expect(anonRow.locator('[data-testid="retention-sweep-confirm"]')).toHaveCount(0);
  expect(posts).toHaveLength(2);

  // ------------------------------------------------------------------
  // Phase B — AC-3: a user with roles ["viewer"] (full reload,
  // production way: the viewer's token in the URL hash) sees no
  // "Run sweep now" button while the panel still renders.
  // ------------------------------------------------------------------
  meBody = VIEWER_ME;
  await page.goto(
    '/studio.html?panel=retention&pass=viewer#access_token=' + encodeURIComponent(VIEWER_TOKEN)
  );
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + VIEWER_TOKEN);
  await expect(page.locator('section[data-panel="retention"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policy-table"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policy-row"]')).toHaveCount(3);
  await expect(page.locator('[data-testid="retention-policy-sweep-now"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="retention"] [data-requires-role="admin"]')).toHaveCount(0);
  expect(posts).toHaveLength(2);

  // ------------------------------------------------------------------
  // Phase C — non-admin role 'user' pass (full reload, the user's
  // token in the URL hash): the page still renders and no admin-only
  // control exists.
  // ------------------------------------------------------------------
  meBody = USER_ME;
  await page.goto(
    '/studio.html?panel=retention&pass=user#access_token=' + encodeURIComponent(USER_TOKEN)
  );
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + USER_TOKEN);
  await expect(page.locator('section[data-panel="retention"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policy-row"]')).toHaveCount(3);
  await expect(page.locator('[data-testid="retention-policy-sweep-now"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="retention"] [data-requires-role="admin"]')).toHaveCount(0);
  expect(posts).toHaveLength(2);
});
