const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue571 surgical', async ({ page }) => {
  await page.goto('/');

  const classes = {
    srcFlow: 'src-flow',
    srcFlowRow: 'src-flow-row',
    srcNode: 'src-node',
    srcNodeLabel: 'src-node-label',
    srcArrow: 'src-arrow',
    srcDiscover: 'src-discover',
    srcIngest: 'src-ingest',
    srcTransform: 'src-transform',
    srcLoad: 'src-load'
  };

  const results = await page.evaluate((cls) => {
    const out = {};
    for (const [key, className] of Object.entries(cls)) {
      const el = document.createElement('div');
      el.className = className;
      document.body.appendChild(el);
      const cs = window.getComputedStyle(el);
      out[key] = {
        display: cs.display,
        paddingTop: cs.paddingTop,
        backgroundColor: cs.backgroundColor,
        borderTopWidth: cs.borderTopWidth,
        borderTopStyle: cs.borderTopStyle,
        marginTop: cs.marginTop
      };
      el.remove();
    }
    return out;
  }, classes);

  for (const [key, s] of Object.entries(results)) {
    const differs =
      s.display !== 'block' ||
      s.paddingTop !== '0px' ||
      s.backgroundColor !== 'rgba(0, 0, 0, 0)' ||
      s.borderTopWidth !== '0px' ||
      s.borderTopStyle !== 'none' ||
      s.marginTop !== '0px';
    expect(
      differs,
      `class "${key}" must differ from browser default in at least one declared property`
    ).toBe(true);
  }
});
