const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue355 surgical', async ({ page }) => {
    // Establish an admin identity via mocked HTTP responses BEFORE the page boots.
    // The catch-all is registered FIRST so it never shadows the specific mocks below
    // (Playwright checks the most recently registered route first).
    await page.route('**/api/**', async (route) => {
        return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({}) });
    });

    await page.route('/api/auth/config', async (route) => {
        return route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
        });
    });

    await page.route('/api/auth/me', async (route) => {
        return route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                authenticated: true,
                user: { username: 'admin', sub: 'admin', roles: ['admin'] },
            }),
        });
    });

    await page.goto('/');

    // The page's own boot-time Auth.init() (via Warehouse._ensureAuth) consumes the mocked
    // /api/auth/me. Wait for that to resolve into an admin state before rendering anything.
    await page.waitForFunction(() => Auth.isAdmin() === true);

    const result = await page.evaluate(async () => {
        const captures = [];
        const origPost = ApiClient.post;
        const origPut = ApiClient.put;
        // Temporary method-level swap: intercepts only the layout write calls, never
        // /api/auth/me (already consumed at boot) and never replaces the Auth module.
        ApiClient.post = (...a) => { captures.push({ method: 'post', args: a }); return Promise.resolve({ ok: true, data: {} }); };
        ApiClient.put = (...a) => { captures.push({ method: 'put', args: a }); return Promise.resolve({ ok: true, data: {} }); };

        const host = document.createElement('div');
        Object.assign(host.style, { position: 'absolute', width: '1200px', height: '600px', top: '0', left: '0', zIndex: 9999, background: '#fff' });
        document.body.appendChild(host);

        const d1 = { id: 'D1', name: 'Test Dash', grid_columns: 8 };
        const i1 = { id: 'i1', dashboard_id: 'D1', title: 'Item 1', item_type: 'kpi', position: 0 };
        const i2 = { id: 'i2', dashboard_id: 'D1', title: 'Item 2', item_type: 'bar', position: 1 };
        const items = [i1, i2];
        const layouts = [{ id: 'L1', dashboard_item_id: 'i1', grid_col_span: 4 }];

        host.innerHTML = Warehouse.renderDashboards([d1], items, layouts);
        Warehouse.bindLayoutEditor(host, [d1], items, layouts);

        await new Promise(r => setTimeout(r, 0));

        const tile1 = host.querySelector('[data-id="i1"]');
        const preWidth = tile1.getBoundingClientRect().width;

        // Edit then cancel — no API write expected for cancel.
        tile1.querySelector('[data-action="edit-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));

        const inputsCount = host.querySelectorAll('input[data-testid^="layout-"]').length;
        const colSpanVal = host.querySelector('input[data-testid="layout-col-span"]').value;

        host.querySelector('[data-action="cancel-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));

        const postCancelInputsCount = host.querySelectorAll('input[data-testid^="layout-"]').length;
        const postCancelWidth = host.querySelector('[data-id="i1"]').getBoundingClientRect().width;

        // Edit then save — an API write (PUT for existing layout) IS expected.
        host.querySelector('[data-action="edit-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));
        host.querySelector('[data-action="save-layout"]').dispatchEvent(new MouseEvent('click', { bubbles: true }));
        await new Promise(r => setTimeout(r, 0));

        const postSaveInputsCount = host.querySelectorAll('input[data-testid^="layout-"]').length;

        const drilldown = document.getElementById('drilldown');
        const drillVisible = !!(drilldown && !drilldown.hidden);

        ApiClient.post = origPost; ApiClient.put = origPut; document.body.removeChild(host);

        return { inputsCount, colSpanVal, postCancelInputsCount, widthDiff: Math.abs(postCancelWidth - preWidth), postSaveInputsCount, captures, drillVisible };
    });

    // Editor appears with 3 layout inputs on edit.
    expect(result.inputsCount).toBe(3);
    expect(result.colSpanVal).toBe('4');

    // Cancel hides the editor and restores width.
    expect(result.postCancelInputsCount).toBe(0);
    expect(result.widthDiff).toBeLessThanOrEqual(20);

    // Save persists via ApiClient.put (existing layout L1) and closes the editor.
    expect(result.captures.length).toBe(1);
    expect(result.captures[0].method).toBe('put');
    expect(result.captures[0].args[0]).toBe('/dashboard-item-layouts/L1');
    expect(result.postSaveInputsCount).toBe(0);

    // Drilldown panel is not triggered by layout editing.
    expect(result.drillVisible).toBe(false);
});
