'use strict';

// Proof for issue #689 — Data retention panel in app/studio.html.
//
// Boots /studio.html?panel=retention with /api/auth/config and /api/auth/me
// mocked and every other /api/** request mocked (two policies, three runs
// across them), and proves:
//   AC-1  both policies render in a table with name, dataset, table class,
//         action, "<n> days" period, scope and Enabled/Disabled
//   AC-2  selecting a policy row marks it selected and shows only that
//         policy's runs, newest created_at first, with name, trigger,
//         status, records purged, records anonymized, error detail and
//         created time; placeholder / no-runs / failed-runs texts
//   AC-3  the empty-policies, failed-policies and no-runs texts appear for
//         their mocked responses, and the panel=retention deep link scrolls
//         the section into view
//   AC-4  null/missing policy and run fields render without throwing
//   AC-5/6 hostile free text (markup, script tags) renders as inert text
//   RD    review defects: truthy non-boolean is_enabled renders Enabled;
//         numeric created_at values sort newest created_at first; null
//         fields render empty OR a neutral placeholder (never the literal
//         strings "null"/"undefined"); numeric created_at renders with any
//         non-empty representation; the window.Retention global is NOT
//         required (the AC mandates only the module + init() on boot)
//   V     non-admin pass (issue #699 supersedes this spec and its criteria
//         concern roles): a role 'user' identity booted the production way
//         (the token in the URL hash as #access_token=...) still renders the
//         panel, but with no admin-only control -- no "Add policy", no
//         per-row Edit/toggle/Delete buttons, and the Enabled/Disabled cell
//         holds only the "Enabled"/"Disabled" text

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});



const AUTH_CONFIG = { auth_mode: 'development' };
const AUTH_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const USER_ME = {
  authenticated: true,
  user: { id: 9, username: 'user', roles: ['user'] },
};

const POLICIES = [
  {
    id: 'pol-1',
    name: 'Purge stale audit rows',
    dataset_id: 'ds-audit',
    table_class: 'audit',
    action: 'purge',
    retention_period_days: 30,
    scope: 'rows',
    is_enabled: true,
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
  {
    id: 'pol-2',
    name: 'Anonymize export PII',
    dataset_id: 'ds-exports',
    table_class: 'exports',
    action: 'anonymize',
    retention_period_days: 90,
    scope: 'columns',
    is_enabled: false,
    created_at: '2026-09-02T00:00:00',
    updated_at: '2026-09-02T00:00:00',
  },
];

// Three runs across the two policies; deliberately NOT newest-first so the
// sort assertion is meaningful (run-2 is newer than run-1).
const RUNS = [
  {
    id: 'run-1',
    policy_id: 'pol-1',
    name: 'Nightly purge',
    trigger: 'schedule',
    status: 'completed',
    records_purged: 1200,
    records_anonymized: 0,
    error_detail: null,
    created_at: '2026-09-10T02:00:00',
    updated_at: '2026-09-10T02:05:00',
  },
  {
    id: 'run-2',
    policy_id: 'pol-1',
    name: 'Manual purge',
    trigger: 'manual',
    status: 'failed',
    records_purged: 0,
    records_anonymized: 0,
    error_detail: 'Timeout connecting to warehouse',
    created_at: '2026-09-20T02:00:00',
    updated_at: '2026-09-20T02:05:00',
  },
  {
    id: 'run-3',
    policy_id: 'pol-2',
    name: 'Weekly anonymize',
    trigger: 'schedule',
    status: 'completed',
    records_purged: 0,
    records_anonymized: 42,
    error_detail: null,
    created_at: '2026-10-01T02:00:00',
    updated_at: '2026-10-01T02:05:00',
  },
];

const API_ERROR = { detail: 'simulated backend failure' };

// AC-4: a null/missing field may render as empty text OR a neutral
// placeholder (e.g. an em dash, a hyphen, "N/A"). The proof accepts both
// (review defect: the earlier assertions rejected allowed neutral
// placeholders); the literal strings "null"/"undefined" stay rejected by
// the per-cell checks at each use site.
const PLACEHOLDER_RE = /^(?:|\u2026|-|\u2013|\u2014|n\/a|none)$/i;

/**
 * Mock every /api/** request for upcoming page loads: auth endpoints fixed,
 * the retention endpoints per arguments, and every other API call an empty
 * JSON array (the Studio boot fetches many lists on startup).
 */
async function mockApi(page, policies, policiesStatus, runs, runsStatus) {
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_ME),
      });
    }
    if (url.includes('/api/retention-policies')) {
      return route.fulfill({
        status: policiesStatus,
        contentType: 'application/json',
        body: JSON.stringify(policies),
      });
    }
    if (url.includes('/api/retention-runs')) {
      return route.fulfill({
        status: runsStatus,
        contentType: 'application/json',
        body: JSON.stringify(runs),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
}

test('issue689 freeform', async ({ page }) => {
  // ------------------------------------------------------------------
  // Phase 1 — two policies, three runs; deep link ?panel=retention
  // ------------------------------------------------------------------
  await mockApi(page, POLICIES, 200, RUNS, 200);
  await page.goto('/studio.html?panel=retention');

  // AC-1: the module is loaded from js/retention.js and its init() runs on
  // Studio boot. The AC mandates "a module that defines const Retention
  // with an init() called on Studio boot" -- it does NOT mandate a
  // window.Retention global, so the proof must not require one (review
  // defect). The script tag proves the module is loaded; the rendered
  // table below proves init() fired on boot, because the proof never calls
  // it itself.
  const scriptSrcs = await page.evaluate(() =>
    Array.from(document.scripts).map((script) => script.getAttribute('src'))
  );
  expect(
    scriptSrcs.some((src) => /(^|\/)(js\/retention\.js)$/.test(src || ''))
  ).toBe(true);
  const section = page.locator('section[data-panel="retention"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Data retention');
  const policyTable = page.locator('[data-testid="retention-policy-table"]');
  await expect(policyTable).toBeVisible();

  const row1 = page.locator('[data-testid="retention-policy-row"][data-id="pol-1"]');
  const row2 = page.locator('[data-testid="retention-policy-row"][data-id="pol-2"]');
  await expect(row1).toBeVisible();
  await expect(row2).toBeVisible();

  // AC-1: both policies render with their fields.
  await expect(row1.locator('td[data-testid="retention-policy-name"]')).toHaveText('Purge stale audit rows');
  await expect(row1.locator('td[data-testid="retention-policy-dataset"]')).toHaveText('ds-audit');
  await expect(row1.locator('td[data-testid="retention-policy-table-class"]')).toHaveText('audit');
  await expect(row1.locator('td[data-testid="retention-policy-action"]')).toHaveText('purge');
  await expect(row1.locator('td[data-testid="retention-policy-period"]')).toHaveText('30 days');
  await expect(row1.locator('td[data-testid="retention-policy-scope"]')).toHaveText('rows');
  // The Enabled/Disabled text renders in the label span: for this admin
  // boot the cell also carries the issue #699 toggle button.
  await expect(row1.locator('td[data-testid="retention-policy-enabled"] [data-testid="retention-policy-enabled-label"]')).toHaveText('Enabled');

  await expect(row2.locator('td[data-testid="retention-policy-name"]')).toHaveText('Anonymize export PII');
  await expect(row2.locator('td[data-testid="retention-policy-dataset"]')).toHaveText('ds-exports');
  await expect(row2.locator('td[data-testid="retention-policy-table-class"]')).toHaveText('exports');
  await expect(row2.locator('td[data-testid="retention-policy-action"]')).toHaveText('anonymize');
  await expect(row2.locator('td[data-testid="retention-policy-period"]')).toHaveText('90 days');
  await expect(row2.locator('td[data-testid="retention-policy-scope"]')).toHaveText('columns');
  await expect(row2.locator('td[data-testid="retention-policy-enabled"] [data-testid="retention-policy-enabled-label"]')).toHaveText('Disabled');

  // AC-2: nothing selected yet -> runs area shows the placeholder.
  const runsArea = page.locator('[data-testid="retention-runs"]');
  await expect(runsArea).toHaveText('Select a policy to see its runs.');

  // Select pol-2: row is marked selected, only its run is shown.
  await row2.click();
  await expect(row2).toHaveClass(/wh-retention-row-selected/);
  await expect(row2).toHaveAttribute('data-selected', 'true');
  await expect(row1).not.toHaveClass(/wh-retention-row-selected/);
  await expect(runsArea.locator('[data-testid="retention-run-row"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="retention-run-name"]')).toHaveText('Weekly anonymize');
  await expect(runsArea.locator('[data-testid="retention-run-trigger"]')).toHaveText('schedule');
  await expect(runsArea.locator('[data-testid="retention-run-status"]')).toHaveText('completed');
  await expect(runsArea.locator('[data-testid="retention-run-purged"]')).toHaveText('Purged: 0');
  await expect(runsArea.locator('[data-testid="retention-run-anonymized"]')).toHaveText('Anonymized: 42');
  await expect(runsArea.locator('[data-testid="retention-run-created"]')).toHaveText('2026-10-01T02:00:00');
  await expect(runsArea.locator('[data-testid="retention-run-error"]')).toHaveCount(0);
  await expect(runsArea).not.toContainText('Nightly purge');
  await expect(runsArea).not.toContainText('Manual purge');

  // Select pol-1: its two runs, newest created_at first, error detail shown.
  await row1.click();
  await expect(row1).toHaveClass(/wh-retention-row-selected/);
  await expect(row2).not.toHaveClass(/wh-retention-row-selected/);
  await expect(runsArea.locator('[data-testid="retention-run-row"]')).toHaveCount(2);
  const runNames = await runsArea.locator('[data-testid="retention-run-name"]').allTextContents();
  expect(runNames).toEqual(['Manual purge', 'Nightly purge']);
  await expect(runsArea.locator('[data-testid="retention-run-error"]')).toHaveCount(1);
  await expect(runsArea.locator('[data-testid="retention-run-error"]')).toHaveText('Timeout connecting to warehouse');
  await expect(runsArea.locator('[data-testid="retention-run-purged"]')).toHaveText(['Purged: 0', 'Purged: 1200']);
  await expect(runsArea).not.toContainText('Weekly anonymize');

  // AC-3: the panel=retention deep link shows the retention tool in the
  // main region — one tool at a time, so it sits at the top of the
  // region and no scroll is needed.
  await expect(section).toBeVisible();
  expect(await page.evaluate(() => document.querySelector('[data-testid="main-content"]').scrollTop)).toBe(0);

  // ------------------------------------------------------------------
  // Phase 2 — empty policy list
  // ------------------------------------------------------------------
  await mockApi(page, [], 200, RUNS, 200);
  await page.goto('/studio.html?panel=retention');
  await expect(page.locator('[data-testid="retention-policies-empty"]')).toHaveText('No retention policies yet.');
  // The shown tool fits the region: nothing scrolls.
  expect(await page.evaluate(() => document.querySelector('[data-testid="main-content"]').scrollTop)).toBe(0);

  // ------------------------------------------------------------------
  // Phase 3 — failed policies request
  // ------------------------------------------------------------------
  await mockApi(page, API_ERROR, 500, RUNS, 200);
  await page.goto('/studio.html?panel=retention');
  await expect(page.locator('[data-testid="retention-policies-error"]')).toHaveText('Could not load retention policies.');

  // ------------------------------------------------------------------
  // Phase 4 — selected policy with no runs
  // ------------------------------------------------------------------
  await mockApi(page, [POLICIES[0]], 200, [], 200);
  await page.goto('/studio.html?panel=retention');
  const loneRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-1"]');
  await expect(loneRow).toBeVisible();
  await loneRow.click();
  await expect(page.locator('[data-testid="retention-runs-empty"]')).toHaveText('No runs for this policy yet.');

  // ------------------------------------------------------------------
  // Phase 5 — failed runs request
  // ------------------------------------------------------------------
  await mockApi(page, [POLICIES[0]], 200, API_ERROR, 500);
  await page.goto('/studio.html?panel=retention');
  const loneRow2 = page.locator('[data-testid="retention-policy-row"][data-id="pol-1"]');
  await expect(loneRow2).toBeVisible();
  await loneRow2.click();
  await expect(page.locator('[data-testid="retention-runs-error"]')).toHaveText('Could not load retention runs.');

  // ------------------------------------------------------------------
  // Phase 6 — null/missing fields and hostile text never break the panel
  // ------------------------------------------------------------------
  const nullPolicy = {
    id: 'pol-null',
    name: '<img src=x onerror=window.__pwned=1> & "quoted"',
    dataset_id: null,
    table_class: null,
    action: null,
    retention_period_days: null,
    scope: null,
    is_enabled: null,
  };
  const nullRun = {
    id: 'run-null',
    policy_id: 'pol-null',
    name: '<script>window.__runPwned=1<\/script>',
    trigger: null,
    status: null,
    records_purged: null,
    records_anonymized: null,
    error_detail: '<b onclick=window.__errPwned=1>bold</b>',
    created_at: null,
  };
  await mockApi(page, [nullPolicy], 200, [nullRun], 200);
  await page.goto('/studio.html?panel=retention');

  const nullRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-null"]');
  await expect(nullRow).toBeVisible();
  await expect(nullRow.locator('td[data-testid="retention-policy-name"]')).toHaveText('<img src=x onerror=window.__pwned=1> & "quoted"');
  // AC-4: null fields render empty OR a neutral placeholder (review defect:
  // the proof accepts both, not only the empty string).
  await expect(nullRow.locator('td[data-testid="retention-policy-dataset"]')).toHaveText(PLACEHOLDER_RE);
  await expect(nullRow.locator('td[data-testid="retention-policy-table-class"]')).toHaveText(PLACEHOLDER_RE);
  await expect(nullRow.locator('td[data-testid="retention-policy-period"]')).toHaveText(PLACEHOLDER_RE);

  await nullRow.click();
  const nullRunsArea = page.locator('[data-testid="retention-runs"]');
  await expect(nullRunsArea.locator('[data-testid="retention-run-row"]')).toHaveCount(1);
  await expect(nullRunsArea.locator('[data-testid="retention-run-name"]')).toHaveText('<script>window.__runPwned=1<\/script>');
  await expect(nullRunsArea.locator('[data-testid="retention-run-purged"]')).toHaveText(PLACEHOLDER_RE);
  await expect(nullRunsArea.locator('[data-testid="retention-run-created"]')).toHaveText(PLACEHOLDER_RE);
  await expect(nullRunsArea.locator('[data-testid="retention-run-error"]')).toHaveText('<b onclick=window.__errPwned=1>bold</b>');

  // Proof assertion (review defect: null-field assertions must accept
  // allowed neutral placeholders): every null-field cell -- the policy's
  // dataset, table class and retention period plus the run's purged count,
  // anonymized count and created time -- renders empty or a neutral
  // placeholder, never the literal strings "null"/"undefined".
  const nullCellTexts = [
    ...(await nullRow
      .locator(
        'td[data-testid="retention-policy-dataset"], ' +
          'td[data-testid="retention-policy-table-class"], ' +
          'td[data-testid="retention-policy-period"]'
      )
      .allTextContents()),
    ...(await nullRunsArea
      .locator(
        '[data-testid="retention-run-purged"], ' +
          '[data-testid="retention-run-anonymized"], ' +
          '[data-testid="retention-run-created"]'
      )
      .allTextContents()),
  ];
  expect(nullCellTexts.length).toBe(6);
  for (const text of nullCellTexts) {
    expect(text).toMatch(PLACEHOLDER_RE);
    expect(text.toLowerCase()).not.toBe('null');
    expect(text.toLowerCase()).not.toBe('undefined');
  }

  // AC-5/6: nothing executable was injected — the payloads render as text.
  expect(
    await page.evaluate(() => {
      const pwned = window.__pwned === 1 || window.__runPwned === 1 || window.__errPwned === 1;
      const injected = document.querySelector(
        '[data-panel="retention"] img, [data-panel="retention"] script, [data-panel="retention"] b[onclick]'
      );
      return pwned || injected !== null;
    })
  ).toBe(false);

  // ------------------------------------------------------------------
  // Phase 7 — numeric policy ids: row.dataset.id is coerced to a string,
  // so the run filter must normalize types or numeric ids never match
  // (review defect: "string coercion in dataset.id")
  // ------------------------------------------------------------------
  const numPolicy = {
    id: 7,
    name: 'Numeric purge policy',
    dataset_id: 'ds-num',
    table_class: 'num',
    action: 'purge',
    retention_period_days: 7,
    scope: 'rows',
    is_enabled: true,
    created_at: '2026-09-03T00:00:00',
    updated_at: '2026-09-03T00:00:00',
  };
  const numRuns = [
    {
      id: 101,
      policy_id: 7,
      name: 'Newer numeric run',
      trigger: 'schedule',
      status: 'completed',
      records_purged: 5,
      records_anonymized: 0,
      error_detail: null,
      created_at: '2026-09-25T02:00:00',
      updated_at: '2026-09-25T02:05:00',
    },
    {
      id: 102,
      policy_id: 7,
      name: 'Older numeric run',
      trigger: 'manual',
      status: 'completed',
      records_purged: 9,
      records_anonymized: 0,
      error_detail: null,
      created_at: '2026-09-05T02:00:00',
      updated_at: '2026-09-05T02:05:00',
    },
    {
      id: 103,
      policy_id: 8,
      name: 'Other numeric policy run',
      trigger: 'schedule',
      status: 'completed',
      records_purged: 1,
      records_anonymized: 0,
      error_detail: null,
      created_at: '2026-09-30T02:00:00',
      updated_at: '2026-09-30T02:05:00',
    },
  ];
  await mockApi(page, [numPolicy], 200, numRuns, 200);
  await page.goto('/studio.html?panel=retention');
  const numRow = page.locator('[data-testid="retention-policy-row"][data-id="7"]');
  await expect(numRow).toBeVisible();
  await numRow.click();
  const numRunsArea = page.locator('[data-testid="retention-runs"]');
  // Numeric policy_id 7 must match the string dataset.id "7"; the old
  // strict === filter would leave this area showing the no-runs text.
  await expect(numRunsArea.locator('[data-testid="retention-run-row"]')).toHaveCount(2);
  const numRunNames = await numRunsArea.locator('[data-testid="retention-run-name"]').allTextContents();
  expect(numRunNames).toEqual(['Newer numeric run', 'Older numeric run']);
  await expect(numRunsArea).not.toContainText('Other numeric policy run');

  // ------------------------------------------------------------------
  // Phase 8 — review defect: truthy non-boolean is_enabled values (1,
  // "true") must render "Enabled"; falsy/missing values stay "Disabled"
  // ------------------------------------------------------------------
  const enabledPolicies = [
    {
      id: 'pol-eb1', name: 'Numeric enabled', dataset_id: 'ds-eb', table_class: 'eb',
      action: 'purge', retention_period_days: 30, scope: 'rows', is_enabled: 1,
    },
    {
      id: 'pol-eb2', name: 'String enabled', dataset_id: 'ds-eb', table_class: 'eb',
      action: 'purge', retention_period_days: 30, scope: 'rows', is_enabled: 'true',
    },
    {
      id: 'pol-eb3', name: 'String disabled', dataset_id: 'ds-eb', table_class: 'eb',
      action: 'purge', retention_period_days: 30, scope: 'rows', is_enabled: 'false',
    },
    {
      id: 'pol-eb4', name: 'Zero disabled', dataset_id: 'ds-eb', table_class: 'eb',
      action: 'purge', retention_period_days: 30, scope: 'rows', is_enabled: 0,
    },
    {
      id: 'pol-eb5', name: 'Null disabled', dataset_id: 'ds-eb', table_class: 'eb',
      action: 'purge', retention_period_days: 30, scope: 'rows', is_enabled: null,
    },
  ];
  await mockApi(page, enabledPolicies, 200, [], 200);
  await page.goto('/studio.html?panel=retention');
  const ebRows = page.locator('[data-testid="retention-policy-row"]');
  await expect(ebRows).toHaveCount(5);
  const ebEnabledTexts = await ebRows
    .locator(
      'td[data-testid="retention-policy-enabled"] [data-testid="retention-policy-enabled-label"]'
    )
    .allTextContents();
  expect(ebEnabledTexts).toEqual([
    'Enabled', 'Enabled', 'Disabled', 'Disabled', 'Disabled',
  ]);

  // ------------------------------------------------------------------
  // Phase 9 — review defect: numeric created_at values must sort
  // newest-first (a missing created_at sorts last without throwing)
  // ------------------------------------------------------------------
  const tsPolicy = {
    id: 'pol-ts', name: 'Timestamp policy', dataset_id: 'ds-ts', table_class: 'ts',
    action: 'purge', retention_period_days: 14, scope: 'rows', is_enabled: true,
  };
  const tsRuns = [
    {
      id: 'ts-run-old', policy_id: 'pol-ts', name: 'Old numeric run',
      trigger: 'schedule', status: 'completed', records_purged: 1,
      records_anonymized: 0, error_detail: null, created_at: 1758000000,
    },
    {
      id: 'ts-run-nots', policy_id: 'pol-ts', name: 'No timestamp run',
      trigger: 'manual', status: 'completed', records_purged: 2,
      records_anonymized: 0, error_detail: null, created_at: null,
    },
    {
      id: 'ts-run-mid', policy_id: 'pol-ts', name: 'Mid numeric run',
      trigger: 'schedule', status: 'completed', records_purged: 3,
      records_anonymized: 0, error_detail: null, created_at: 1758500000,
    },
    {
      id: 'ts-run-new', policy_id: 'pol-ts', name: 'New numeric run',
      trigger: 'schedule', status: 'completed', records_purged: 4,
      records_anonymized: 0, error_detail: null, created_at: 1759000000,
    },
  ];
  await mockApi(page, [tsPolicy], 200, tsRuns, 200);
  await page.goto('/studio.html?panel=retention');
  const tsRow = page.locator('[data-testid="retention-policy-row"][data-id="pol-ts"]');
  await expect(tsRow).toBeVisible();
  await tsRow.click();
  const tsRunsArea = page.locator('[data-testid="retention-runs"]');
  await expect(tsRunsArea.locator('[data-testid="retention-run-row"]')).toHaveCount(4);
  const tsRunNames = await tsRunsArea
    .locator('[data-testid="retention-run-name"]')
    .allTextContents();
  expect(tsRunNames).toEqual([
    'New numeric run', 'Mid numeric run', 'Old numeric run', 'No timestamp run',
  ]);
  const tsCreatedTexts = await tsRunsArea
    .locator('[data-testid="retention-run-created"]')
    .allTextContents();
  // Proof assertion (review defect: numeric created_at rendering was
  // over-constrained): a numeric created_at may render as the raw number,
  // an ISO string, or a formatted date -- AC-2 only requires the created
  // time to be shown, so any non-empty rendering is accepted. The run with
  // created_at: null renders empty or a neutral placeholder (AC-4) and
  // sorts last, after the three timestamped runs (newest created_at first).
  expect(tsCreatedTexts.length).toBe(4);
  expect(tsCreatedTexts[0]).toMatch(/\S/);
  expect(tsCreatedTexts[1]).toMatch(/\S/);
  expect(tsCreatedTexts[2]).toMatch(/\S/);
  expect(tsCreatedTexts[3]).toMatch(PLACEHOLDER_RE);
  expect(tsCreatedTexts[3].toLowerCase()).not.toBe('null');
  expect(tsCreatedTexts[3].toLowerCase()).not.toBe('undefined');
});

// Boot the page the production way for a given identity: the auth
// endpoints are mocked for `me`, the retention endpoints for POLICIES
// and RUNS (every other /api/** an empty list), and the token rides the
// URL hash fragment (#access_token=...).  The boot proves the token was
// picked up the production way: Auth.init() migrates it into
// sessionStorage and it arrives as the Authorization header on
// /api/auth/me.
async function bootAs(page, me, token, url = '/studio.html?panel=retention') {
  const meAuthorizations = [];
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const url = request.url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorizations.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(me),
      });
    }
    if (url.includes('/api/retention-policies')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(POLICIES),
      });
    }
    if (url.includes('/api/retention-runs')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(RUNS),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
  await page.goto(url + '#access_token=' + encodeURIComponent(token));
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

test('issue689 freeform (viewer)', async ({ page }) => {
  // Non-admin pass (issue #699 supersedes this spec and its criteria
  // concern roles): boot the production way for a role 'user' identity --
  // the token in the URL hash, /api/auth/config and /api/auth/me mocked
  // for that user -- and prove the panel still renders while no
  // admin-only control exists.
  await bootAs(page, USER_ME, 'user-token-689');

  const section = page.locator('section[data-panel="retention"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Data retention');
  const policyTable = page.locator('[data-testid="retention-policy-table"]');
  await expect(policyTable).toBeVisible();
  const rows = page.locator('[data-testid="retention-policy-row"]');
  await expect(rows).toHaveCount(2);
  await expect(rows.nth(0).locator('td[data-testid="retention-policy-name"]')).toHaveText('Purge stale audit rows');
  await expect(rows.nth(1).locator('td[data-testid="retention-policy-name"]')).toHaveText('Anonymize export PII');

  // No admin-only control is rendered for a non-admin: no "Add policy"
  // toolbar button, no per-row Edit/toggle/Delete buttons, and nothing in
  // the panel carries the admin role marker.
  await expect(page.locator('[data-testid="retention-add-policy"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-edit"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-toggle"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-delete"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="retention"] [data-requires-role="admin"]')).toHaveCount(0);

  // The Enabled/Disabled cell holds only the text -- no button in the cell.
  const enabledCell0 = rows.nth(0).locator('td[data-testid="retention-policy-enabled"]');
  await expect(enabledCell0).toHaveText('Enabled');
  await expect(enabledCell0.locator('button')).toHaveCount(0);
  const enabledCell1 = rows.nth(1).locator('td[data-testid="retention-policy-enabled"]');
  await expect(enabledCell1).toHaveText('Disabled');
  await expect(enabledCell1.locator('button')).toHaveCount(0);
});
