const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue389 surgical', async ({ page }) => {
    await page.goto('/studio.html?panel=sequences');

    // Assert the text 'Load sequences' is visible
    await expect(page.getByRole('heading', {name: 'Load sequences', exact: true})).toBeVisible();

    // Assert via waitForFunction that window.Sequences is defined
    await page.waitForFunction(() => typeof window.Sequences !== 'undefined');

    // Wait for error div inside container with state: 'attached' (empty element has no bounding box)
    const container = page.locator('[data-panel="sequences"]');
    await container.locator('[data-testid="sequences-error"]').waitFor({ state: 'attached' });
});

// Non-admin identity for the viewer pass (the criteria concern roles): a
// role 'user' identity booted the production way — the token in the URL
// hash as #access_token=..., /api/auth/config and /api/auth/me mocked for
// that user — proves the tool still renders while the admin-only control
// is absent.
const AUTH_CONFIG = { auth_mode: 'development' };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-389';

// Boot the page the production way for a given identity: /api/auth/config
// and /api/auth/me mocked for `me`, every other /api/** an empty list, and
// the token riding the URL hash fragment (#access_token=...).  The boot
// proves the token was picked up the production way: Auth.init() migrates
// it into sessionStorage and it arrives as the Authorization header on
// /api/auth/me.
async function bootAs(page, me, token, url) {
    const meAuthorizations = [];
    await page.unrouteAll();
    await page.route('**/api/**', (route) => {
        const request = route.request();
        const reqUrl = request.url();
        if (reqUrl.includes('/api/auth/config')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
        }
        if (reqUrl.includes('/api/auth/me')) {
            const auth = request.headers()['authorization'];
            if (auth) meAuthorizations.push(auth);
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    });
    await page.goto(url + '#access_token=' + encodeURIComponent(token));
    await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

test('issue389 surgical (viewer)', async ({ page }) => {
    // Non-admin pass: boot the production way as a role 'user' identity
    // (the token in the URL hash) and prove the tool still renders while
    // the admin-only control is absent.
    await bootAs(page, VIEWER_ME, VIEWER_TOKEN, '/studio.html?panel=sequences');

    // The page renders for a non-admin: the Load sequences tool shows its
    // read-only list in a terminal state...
    await expect(page.getByRole('heading', { name: 'Load sequences', exact: true })).toBeVisible();
    await expect(page.locator('[data-testid="sequences-empty"]')).toBeVisible();
    await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

    // ...with the admin-only control absent: the create button is not
    // rendered for a non-admin, the role-gated Feed keys nav item leaves
    // the DOM, the Feed keys section is removed by its module, and the
    // admin-only source form is gone.
    await expect(page.locator('[data-testid="sequence-create"]')).toHaveCount(0);
    await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
    await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('#source-form')).toHaveCount(0);
});
