'use strict';

// Proof for issue #767 — the application shell: app/css/tokens.css + the
// fixed-height two-column shell (dark sidebar + main area) on Dashboards
// (app/index.html) and Studio (app/studio.html).
//
// Boots both pages against mocked /api/** responses (no backend) and proves:
//   AC-1  both pages load css/tokens.css and --color-sidebar resolves to
//         #16212C; the sidebar shows, top to bottom, the AIDW mark and
//         name, the "Dashboards" nav item (href index.html) and one nav
//         item per Studio panel in the AC order (hrefs
//         studio.html?panel=<name>), the Feed keys item carrying
//         data-requires-role="admin", and the existing #auth-status at
//         the bottom; the main area has the page title ("Dashboards" or
//         "Studio") and a one-line subtitle; the old "Configure" and
//         "← Dashboard" header links are replaced by the sidebar
//   AC-2  the Feed keys nav item is hidden for a non-admin and shown for
//         an admin; aria-current="page" is on Dashboards on index.html
//         and, on studio.html, on the panel last navigated to (or the
//         first panel when there is none); a Studio nav click rewrites
//         ?panel= and brings the panel into the main region's view
//         WITHOUT a page load (a window marker survives); at 1440x900
//         the document itself does not scroll on either page while the
//         main content region scrolls on Studio; at 900 px and below the
//         sidebar becomes a top bar; at 390x844 there is no horizontal
//         page scroll
//   Identity  the criteria concern roles, so the proof also runs a
//         non-admin pass (role 'user') booted the production way: the
//         token in the URL hash (#access_token=...), /api/auth/config
//         and /api/auth/me mocked for that user, and the hash token
//         reaching /api/auth/me as a Bearer header while the page still
//         renders with the admin-only control absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { auth_mode: 'development' };
const ADMIN_ME = { authenticated: true, user: { id: 1, username: 'admin', roles: ['admin'] } };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-767';

// The sidebar's navigation, in the AC's order, with its hrefs.
const NAV = [
  { label: 'Dashboards', href: 'index.html', panel: null },
  { label: 'Data sources', href: 'studio.html?panel=sources', panel: 'sources' },
  { label: 'Suggestions', href: 'studio.html?panel=suggestions', panel: 'suggestions' },
  { label: 'PII flags', href: 'studio.html?panel=pii', panel: 'pii' },
  { label: 'Process wizard', href: 'studio.html?panel=wizard', panel: 'wizard' },
  { label: 'Load sequences', href: 'studio.html?panel=sequences', panel: 'sequences' },
  { label: 'Data retention', href: 'studio.html?panel=retention', panel: 'retention' },
  { label: 'Ingestion', href: 'studio.html?panel=ingestion', panel: 'ingestion' },
  { label: 'Feed keys', href: 'studio.html?panel=feedkeys', panel: 'feedkeys' },
  { label: 'Audit history', href: 'studio.html?panel=audit', panel: 'audit' },
];

// Mock every /api/** request for upcoming page loads: auth endpoints for
// `me`, every other API call an empty JSON array (both pages' boot
// fetches many lists on startup).
async function mockApi(page, me) {
  await page.unrouteAll();
  await page.route('**/api/**', (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
}

async function sidebarItems(page) {
  return page.evaluate(() =>
    Array.from(document.querySelectorAll('[data-testid="sidebar-nav"] > .aidw-nav-item')).map((a) => ({
      label: a.textContent.trim(),
      href: a.getAttribute('href'),
      role: a.getAttribute('data-requires-role'),
      current: a.getAttribute('aria-current'),
    })));
}

// AC-1: the fixed-height shell — the document itself must not scroll.
async function expectNoDocumentScroll(page) {
  const m = await page.evaluate(() => ({
    doc: document.scrollingElement.scrollHeight - document.scrollingElement.clientHeight,
    body: document.body.scrollHeight - document.body.clientHeight,
    win: window.scrollY,
  }));
  expect(m.doc).toBeLessThanOrEqual(0);
  expect(m.body).toBeLessThanOrEqual(0);
  expect(m.win).toBe(0);
}

// AC-2: no sideways page scroll (the sidebar's own top-bar nav may scroll
// internally; the document must not).
async function expectNoHorizontalScroll(page) {
  const m = await page.evaluate(() => {
    // Behavioural: the viewport must not move sideways (its horizontal
    // overflow is hidden, so a horizontal scrollTo is a no-op)...
    window.scrollTo(100, 0);
    // ...and neither the document nor the body carries any horizontal
    // scrollable overflow.
    const doc = document.documentElement;
    return {
      scrollX: window.scrollX,
      doc: doc.scrollWidth - doc.clientWidth,
      body: document.body.scrollWidth - document.body.clientWidth,
    };
  });
  expect(m.scrollX).toBe(0);
  expect(m.doc).toBeLessThanOrEqual(0);
  expect(m.body).toBeLessThanOrEqual(0);
}

// The sidebar's rendered shape: brand on top, then the ordered nav.
async function expectSidebar(page, { feedkeysVisible }) {
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  // Mark and name at the top of the sidebar.
  const brand = page.locator('[data-testid="sidebar-brand"]');
  await expect(brand).toBeVisible();
  expect((await brand.textContent()).trim()).toBe('AIDW');

  const feedkeys = page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]');
  if (feedkeysVisible) {
    // The role gate puts the item back once auth settles; wait for it so
    // the item list read below is the full ten.
    await expect(feedkeys).toBeVisible();
  } else {
    // Fail-closed: for a non-admin the item leaves the DOM.
    await expect(feedkeys).toHaveCount(0);
  }

  const expected = feedkeysVisible ? NAV : NAV.filter((n) => n.panel !== 'feedkeys');
  const items = await sidebarItems(page);
  expect(items.map((i) => i.label)).toEqual(expected.map((n) => n.label));
  expect(items.map((i) => i.href)).toEqual(expected.map((n) => n.href));
  // Feed keys is the only role-gated item, marked for admins.
  expect(items.map((i) => i.role)).toEqual(
    expected.map((n) => (n.panel === 'feedkeys' ? 'admin' : null))
  );

  // The existing #auth-status element sits at the bottom of the sidebar.
  const auth = page.locator('[data-testid="sidebar"] [data-testid="auth-status"]');
  await expect(auth).toBeVisible();
  const authBox = await auth.boundingBox();
  const navBox = await page.locator('[data-testid="sidebar-nav"]').boundingBox();
  expect(authBox.y).toBeGreaterThan(navBox.y + navBox.height - 10);
}

test('issue767 freeform', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await mockApi(page, ADMIN_ME);

  // ------------------------------------------------------------------
  // Dashboards (index.html) at 1440x900
  // ------------------------------------------------------------------
  await page.goto('/index.html');

  // Both pages load tokens.css; --color-sidebar resolves to #16212C.
  const sheets = await page.evaluate(() =>
    Array.from(document.querySelectorAll('link[rel="stylesheet"]')).map((l) => l.getAttribute('href')));
  expect(sheets).toContain('css/tokens.css');
  const sidebarColor = (await page.evaluate(() =>
    getComputedStyle(document.documentElement).getPropertyValue('--color-sidebar'))).trim().toLowerCase();
  expect(sidebarColor.replace(/\s+/g, '')).toBe('#16212c');

  await expectSidebar(page, { feedkeysVisible: true });

  // aria-current="page" is on the Dashboards nav item (and only it).
  const dashItems = await sidebarItems(page);
  expect(dashItems.map((i) => i.current)).toEqual([
    'page', null, null, null, null, null, null, null, null, null,
  ]);

  // Main area header: the page title + a one-line subtitle.
  await expect(page.locator('.aidw-page-title')).toHaveText('Dashboards');
  const subtitle = (await page.locator('.aidw-page-subtitle').textContent()).trim();
  expect(subtitle.length).toBeGreaterThan(0);
  expect(subtitle).not.toMatch(/\n/);

  // The old "Configure" header link is replaced by the sidebar.
  expect(await page.locator('a[data-testid="nav-studio"]').count()).toBe(0);
  // The existing dashboard content is intact inside the shell.
  await expect(page.locator('[data-testid="dashboards"]')).toBeVisible();

  // At 1440x900 the document itself does not scroll.
  await expectNoDocumentScroll(page);

  // ------------------------------------------------------------------
  // Studio nav on the Dashboards page: the links are live — a Studio
  // item does a genuine page load to its own href
  // (studio.html?panel=<name>), and Studio arrives focused on that
  // panel via the deep link.
  // ------------------------------------------------------------------
  await page.evaluate(() => { window.__issue767DashMarker = 'dash'; });
  await page.click('.aidw-nav-item[data-nav-panel="ingestion"]');
  await page.waitForURL((url) =>
    url.pathname === '/studio.html' && url.searchParams.get('panel') === 'ingestion');
  // A real page load happened: the Dashboards document's window state
  // is gone...
  expect(await page.evaluate(() => window.__issue767DashMarker)).toBeFalsy();
  // ...and Studio renders with the nav item current (not Dashboards)...
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio');
  await expect(page.locator('.aidw-nav-item[data-nav-panel="ingestion"]')).toHaveAttribute('aria-current', 'page');
  await expect(page.locator('.aidw-nav-item[data-nav="dashboards"]')).not.toHaveAttribute('aria-current');
  // ...with the deep-linked panel in the main region's view.
  await expect.poll(async () => page.evaluate(() => {
    const rr = document.querySelector('[data-testid="main-content"]').getBoundingClientRect();
    const r = document.querySelector('[data-panel="ingestion"]').getBoundingClientRect();
    return r.top < rr.bottom && r.bottom > rr.top;
  })).toBeTruthy();

  // ------------------------------------------------------------------
  // Studio (studio.html) at 1440x900
  // ------------------------------------------------------------------
  await page.goto('/studio.html');

  const studioSheets = await page.evaluate(() =>
    Array.from(document.querySelectorAll('link[rel="stylesheet"]')).map((l) => l.getAttribute('href')));
  expect(studioSheets).toContain('css/tokens.css');
  const studioSidebarColor = (await page.evaluate(() =>
    getComputedStyle(document.documentElement).getPropertyValue('--color-sidebar'))).trim().toLowerCase();
  expect(studioSidebarColor.replace(/\s+/g, '')).toBe('#16212c');

  await expectSidebar(page, { feedkeysVisible: true });

  // No deep link: aria-current="page" is on the first panel.
  const studioItems = await sidebarItems(page);
  expect(studioItems.map((i) => i.current)).toEqual([
    null, 'page', null, null, null, null, null, null, null, null,
  ]);

  // Main area header: the Studio title + subtitle.
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio');
  // The old "← Dashboard" header link is replaced by the sidebar.
  expect(await page.locator('a[data-testid="nav-dashboard"]').count()).toBe(0);

  // The main content region scrolls (the Studio's panels overflow it)...
  const region = await page.evaluate(() => {
    const el = document.querySelector('[data-testid="main-content"]');
    return { scrollHeight: el.scrollHeight, clientHeight: el.clientHeight };
  });
  expect(region.scrollHeight).toBeGreaterThan(region.clientHeight);
  // ...while the document itself does not scroll.
  await expectNoDocumentScroll(page);

  // ------------------------------------------------------------------
  // Studio navigation: no page load, ?panel= deep link, aria-current
  // ------------------------------------------------------------------
  await page.evaluate(() => { window.__issue767Marker = 'alive'; });

  // Click "Data retention": the panel comes into the main region's view.
  await page.click('.aidw-nav-item[data-nav-panel="retention"]');
  // The window marker survived: no page load happened.
  expect(await page.evaluate(() => window.__issue767Marker)).toBe('alive');
  // The ?panel= deep link is in the URL (a reload re-focuses the panel).
  expect(new URL(page.url()).searchParams.get('panel')).toBe('retention');
  // aria-current="page" moved to the panel last navigated to.
  await expect(page.locator('.aidw-nav-item[data-nav-panel="retention"]')).toHaveAttribute('aria-current', 'page');
  await expect(page.locator('.aidw-nav-item[data-nav-panel="sources"]')).not.toHaveAttribute('aria-current');
  await expect(page.locator('.aidw-nav-item[data-nav="dashboards"]')).not.toHaveAttribute('aria-current');
  // The panel is inside the main region's view.
  await expect.poll(async () => page.evaluate(() => {
    const rr = document.querySelector('[data-testid="main-content"]').getBoundingClientRect();
    const r = document.querySelector('[data-panel="retention"]').getBoundingClientRect();
    return r.top < rr.bottom && r.bottom > rr.top;
  })).toBeTruthy();

  // Click "Audit history": same contract for the last panel.
  await page.click('.aidw-nav-item[data-nav-panel="audit"]');
  expect(await page.evaluate(() => window.__issue767Marker)).toBe('alive');
  expect(new URL(page.url()).searchParams.get('panel')).toBe('audit');
  await expect(page.locator('.aidw-nav-item[data-nav-panel="audit"]')).toHaveAttribute('aria-current', 'page');
  await expect(page.locator('.aidw-nav-item[data-nav-panel="retention"]')).not.toHaveAttribute('aria-current');
  await expect.poll(async () => page.evaluate(() => {
    const rr = document.querySelector('[data-testid="main-content"]').getBoundingClientRect();
    const r = document.querySelector('[data-panel="audit"]').getBoundingClientRect();
    return r.top < rr.bottom && r.bottom > rr.top;
  })).toBeTruthy();

  // Click "Load sequences": its data-panel element is a div inside its
  // section — the same navigation contract holds.
  await page.click('.aidw-nav-item[data-nav-panel="sequences"]');
  expect(await page.evaluate(() => window.__issue767Marker)).toBe('alive');
  await expect(page.locator('.aidw-nav-item[data-nav-panel="sequences"]')).toHaveAttribute('aria-current', 'page');
  await expect.poll(async () => page.evaluate(() => {
    const rr = document.querySelector('[data-testid="main-content"]').getBoundingClientRect();
    const r = document.querySelector('[data-panel="sequences"]').getBoundingClientRect();
    return r.top < rr.bottom && r.bottom > rr.top;
  })).toBeTruthy();

  // ------------------------------------------------------------------
  // The settling guard must not fight the user: with a fresh nav click
  // the guard is running (its window is 2.5 s); scrolling the main
  // region away is not reversed — the region stays where the user left
  // it, both shortly after and after the window expires.
  // ------------------------------------------------------------------
  await page.click('.aidw-nav-item[data-nav-panel="sequences"]');
  await expect.poll(async () => page.evaluate(() => {
    const rr = document.querySelector('[data-testid="main-content"]').getBoundingClientRect();
    const r = document.querySelector('[data-panel="sequences"]').getBoundingClientRect();
    return r.top < rr.bottom && r.bottom > rr.top;
  })).toBeTruthy();
  // The user scrolls the region away...
  await page.evaluate(() => {
    document.querySelector('[data-testid="main-content"]').scrollTop = 0;
  });
  // ...and the guard does not pull the view back to the panel — not
  // quickly (its tick is every 100 ms)...
  await page.waitForTimeout(400);
  expect(await page.evaluate(() =>
    document.querySelector('[data-testid="main-content"]').scrollTop)).toBe(0);
  // ...and not after the settling window has expired.
  await page.waitForTimeout(2400);
  expect(await page.evaluate(() =>
    document.querySelector('[data-testid="main-content"]').scrollTop)).toBe(0);

  // ------------------------------------------------------------------
  // Narrow screens: top-bar sidebar, no sideways scroll
  // ------------------------------------------------------------------
  // At 900 px and below the sidebar becomes a top bar.
  await page.setViewportSize({ width: 900, height: 900 });
  // The viewport width, read where `window` exists (the Node side).
  const narrowViewport = page.viewportSize() || { width: 900, height: 900 };
  let bar = await page.evaluate(() => {
    const s = document.querySelector('[data-testid="sidebar"]').getBoundingClientRect();
    return { width: s.width, height: s.height };
  });
  expect(bar.width).toBeGreaterThan(narrowViewport.width - 2);
  expect(bar.height).toBeLessThan(160);

  // At 390x844: the top bar holds and there is no horizontal page scroll
  // on either page.
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/studio.html');
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  bar = await page.evaluate(() => {
    const s = document.querySelector('[data-testid="sidebar"]').getBoundingClientRect();
    const n = document.querySelector('[data-testid="sidebar-nav"]').getBoundingClientRect();
    return { width: s.width, height: s.height, navHeight: n.height };
  });
  expect(bar.width).toBeGreaterThan(390 - 2);
  expect(bar.height).toBeLessThan(160);
  expect(bar.navHeight).toBeLessThanOrEqual(bar.height);
  await expectNoHorizontalScroll(page);

  await page.goto('/index.html');
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-page-title')).toHaveText('Dashboards');
  await expectNoHorizontalScroll(page);
});

test('issue767 freeform (viewer)', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });

  // Boot the production way for a role 'user' identity: the token rides
  // the URL hash (#access_token=...), /api/auth/config and /api/auth/me
  // are mocked for that user, and the hash token must reach /api/auth/me
  // as a Bearer header.
  const meAuthorizations = [];
  await page.route('**/api/**', (route) => {
    const request = route.request();
    const url = request.url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorizations.push(auth);
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(VIEWER_ME) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });
  await page.goto('/studio.html#access_token=' + encodeURIComponent(VIEWER_TOKEN));
  await expect.poll(() => meAuthorizations).toContain('Bearer ' + VIEWER_TOKEN);

  // The page renders for a non-admin...
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-page-title')).toHaveText('Studio');
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  // ...with the signed-in user at the sidebar bottom...
  await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');
  // ...and the admin-only Feed keys control is absent: fail-closed
  // gating removes it from the DOM, so no role-gated nav item survives
  // for a non-admin.
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
  // The remaining nav items are all still shown.
  for (const panel of NAV.filter((n) => n.panel !== 'feedkeys')) {
    const item = panel.panel
      ? page.locator('.aidw-nav-item[data-nav-panel="' + panel.panel + '"]')
      : page.locator('.aidw-nav-item[data-nav="dashboards"]');
    await expect(item).toBeVisible();
  }

  // A full reload on the other page: still renders, still gated.
  await page.goto('/index.html#access_token=' + encodeURIComponent(VIEWER_TOKEN));
  await expect(page.locator('[data-testid="sidebar"]')).toBeVisible();
  await expect(page.locator('.aidw-page-title')).toHaveText('Dashboards');
  await expect(page.locator('[data-testid="dashboards"]')).toBeVisible();
  await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');
  await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
  await expect(page.locator('.aidw-nav-item[data-nav="dashboards"]')).toHaveAttribute('aria-current', 'page');
});
