const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


// Issue #610 — proving spec for the rewritten surgical auth proof.
//
// Drives ONLY the DOM and the network against the served app (no module is replaced:
// window.Auth / window.ApiClient / js/auth.js are left untouched). A single
// page.route('**/api/**') handler branches on the URL before any navigation, so every
// request the real modules make is intercepted.
//
// Proven here:
//   • The token seeded via the URL hash `#access_token=<token>` is migrated by auth.js
//     into sessionStorage['aicrm_token'] (NOT localStorage['auth_token']).
//   • Every module's first /api request carries the Authorization header and no protected
//     request returns 401.
//   • Protected route mocks return 401 when Authorization is missing or invalid — they do
//     not blindly succeed (verified by a raw, unauthenticated probe that must receive 401).
//   • A second pass with /api/auth/config unreachable still lets the modules start and
//     performs no navigation away from studio.html.
//   • No rejection/redirect path is asserted: auth.js resolves (undefined or a user object),
//     never rejects, so the rejecting-init scenario is dropped as unreachable.

test('issue610 freeform', async ({ page }) => {
    const TOKEN1 = 'issue610-pass-one-token';
    const TOKEN2 = 'issue610-pass-two-token';

    let apiCalls = [];
    let configUnreachable = false;
    let expectedToken = '';
    // Exact-token validation: only the precise Bearer token for this pass is accepted.
    const isValidAuth = (h) => !!h && h === `Bearer ${expectedToken}`;

    await page.route('**/api/**', async (route) => {
        const url = route.request().url();
        const authHeader = route.request().headers()['authorization'];
        let status, body;

        if (url.includes('/api/auth/config')) {
            if (configUnreachable) {
                status = 503;
                body = { detail: 'Service Unavailable' };
            } else {
                status = 200;
                body = { authEnabled: true, authMode: 'development', issuer: '', clientId: '' };
            }
        } else if (url.includes('/api/auth/me')) {
            if (isValidAuth(authHeader)) {
                status = 200;
                body = { authenticated: true, user: { username: 'proofuser', roles: ['admin'] } };
            } else {
                status = 401;
                body = { detail: 'Not authenticated' };
            }
        } else {
            // Protected panel endpoints — missing or invalid Authorization → 401.
            if (isValidAuth(authHeader)) {
                status = 200;
                body = [];
            } else {
                status = 401;
                body = { detail: 'Not authenticated' };
            }
        }

        apiCalls.push({ url, authorization: authHeader || null, status });
        await route.fulfill({
            status,
            contentType: 'application/json',
            body: JSON.stringify(body),
        });
    });

    // ------------------------------------------------------------------
    // Pass 1 — token seeded via URL hash; migrated to sessionStorage (not localStorage);
    // every module's first request carries Authorization and none returns 401.
    // ------------------------------------------------------------------
    {
        apiCalls = [];
        configUnreachable = false;
        expectedToken = TOKEN1;

        await page.goto(`/studio.html#access_token=${TOKEN1}`);

        await expect(page.locator('[data-testid="sequences-empty"]'))
            .toHaveText(/No load sequences yet/);
        await expect.poll(() => apiCalls.some((c) => c.url.includes('/api/process-definitions')))
            .toBe(true);

        const stored = await page.evaluate(() => sessionStorage.getItem('aicrm_token'));
        expect(stored).toBe(TOKEN1);
        const local = await page.evaluate(() => localStorage.getItem('auth_token'));
        expect(local).toBeNull();

        const initCalls = apiCalls.slice();
        const byPath = (frag) => initCalls.filter((c) => c.url.includes(frag));

        for (const frag of ['/api/auth/me', '/api/load-sequences', '/api/process-definitions']) {
            const calls = byPath(frag);
            expect(calls.length, `no ${frag} request recorded`).toBeGreaterThan(0);
            for (const c of calls) {
                expect(c.authorization, `${frag} missing Authorization on ${c.url}`).toBe(`Bearer ${TOKEN1}`);
                expect(c.status, `${frag} returned 401`).not.toBe(401);
            }
        }

        // Universal: no captured request returned 401 → every module's requests were authenticated.
        for (const c of initCalls) {
            expect(c.status, `unexpected 401 on ${c.url}`).not.toBe(401);
        }

        // Prove the mock enforces auth rather than blindly succeeding: a raw, unauthenticated
        // request to a protected panel endpoint must receive 401.
        const probe = await page.evaluate(async () => (await fetch('/api/sources')).status);
        expect(probe).toBe(401);

        // Authenticated user resolved (undefined, not null) → no redirect away from studio.html.
        expect(page.url()).toContain('studio.html');
    }

    // ------------------------------------------------------------------
    // Pass 2 — /api/auth/config unreachable; modules still start and no navigation happens.
    // A full document reload is forced (about:blank hop) so auth.js re-runs and re-migrates
    // the token from a fresh hash, with a distinct token proving it is not leftover state.
    // ------------------------------------------------------------------
    {
        apiCalls = [];
        configUnreachable = true;
        expectedToken = TOKEN2;

        await page.goto('about:blank'); // cross-document hop so the next goto is a full load
        await page.goto(`/studio.html#access_token=${TOKEN2}`);

        await expect(page.locator('[data-testid="sequences-empty"]'))
            .toHaveText(/No load sequences yet/);
        await expect.poll(() => apiCalls.some((c) => c.url.includes('/api/process-definitions')))
            .toBe(true);

        // Fresh migration in this pass — a distinct token proves it is not leftover.
        const stored = await page.evaluate(() => sessionStorage.getItem('aicrm_token'));
        expect(stored).toBe(TOKEN2);

        const initCalls = apiCalls.slice();
        const byPath = (frag) => initCalls.filter((c) => c.url.includes(frag));

        // The unreachable config mock was actually exercised and returned 503.
        const configCalls = byPath('/api/auth/config');
        expect(configCalls.length, 'no /api/auth/config request recorded').toBeGreaterThan(0);
        for (const c of configCalls) {
            expect(c.status, `config expected 503 but got ${c.status}`).toBe(503);
        }

        // Identity still resolved via the migrated token despite the config outage.
        const meCalls = byPath('/api/auth/me');
        expect(meCalls.length).toBeGreaterThan(0);
        for (const c of meCalls) {
            expect(c.authorization, `auth/me missing Authorization on ${c.url}`).toBe(`Bearer ${TOKEN2}`);
            expect(c.status, 'auth/me returned 401').not.toBe(401);
        }

        const seqCalls = byPath('/api/load-sequences');
        expect(seqCalls.length).toBeGreaterThan(0);
        for (const c of seqCalls) {
            expect(c.authorization, `load-sequences missing Authorization on ${c.url}`).toBe(`Bearer ${TOKEN2}`);
            expect(c.status, 'load-sequences returned 401').not.toBe(401);
        }

        // No 401s anywhere in this pass (config is 503, not 401).
        for (const c of initCalls) {
            expect(c.status, `unexpected 401 on ${c.url}`).not.toBe(401);
        }

        // Modules started; no navigation to index.html.
        expect(page.url()).toContain('studio.html');
    }
});
