// Issue #572 proof: the two specs drive the suggestion loop on /studio.html (open the studio,
// act on the inbox, assert the accepted item lands on a dashboard by opening /), and both pass
// in the served-app Playwright run with no backend. Every /api/** endpoint is mocked with
// page.route BEFORE page.goto; the mocked GET /api/suggestions is stateful so the inbox
// re-renders from the (now empty) list after accept/dismiss. The dashboard-items list is also
// stateful: the item only appears after a genuine accept, so a mis-wired button that hits the
// dismiss URL cannot fake the assertion.
const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


const BASE = (process.env.BASE_URL || 'http://localhost:8080').replace(/\/+$/, '');
const TOKEN = 'dev-secret-token:admin';
const MARK = `FE-572-${Date.now()}`;

const SUG_ID = 'sug-572-proof';
const DASH_ID = 'dash-572-proof';
const ITEM_ID = 'item-572-proof';
const TITLE = `${MARK} Orders by Region`;

// Non-admin identity for the viewer pass (the criteria concern roles): a
// role 'user' identity booted the production way — the token in the URL
// hash as #access_token=..., /api/auth/config and /api/auth/me mocked for
// that user — proves the studio inbox still renders while the admin-only
// controls are absent.
const AUTH_CONFIG = { auth_mode: 'development' };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-572';

// Boot the page the production way for a given identity: /api/auth/config
// and /api/auth/me mocked for `me`, every other /api/** an empty list, and
// the token riding the URL hash fragment (#access_token=...).  The boot
// proves the token was picked up the production way: Auth.init() migrates
// it into sessionStorage and it arrives as the Authorization header on
// /api/auth/me.
async function bootAs(page, me, token, url) {
    const meAuthorizations = [];
    await page.unrouteAll();
    await page.route('**/api/**', (route) => {
        const request = route.request();
        const reqUrl = request.url();
        if (reqUrl.includes('/api/auth/config')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
        }
        if (reqUrl.includes('/api/auth/me')) {
            const auth = request.headers()['authorization'];
            if (auth) meAuthorizations.push(auth);
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    });
    await page.goto(url + '#access_token=' + encodeURIComponent(token));
    await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

async function installRoutes(page) {
    const inbox = new Set([SUG_ID]);
    // Stateful dashboard-items: the item only appears after a genuine accept.
    const dashboardItems = [];

    await page.route(`${BASE}/api/suggestions`, (route) => {
        const body = [...inbox].map((id) => ({
            id,
            name: TITLE,
            title: TITLE,
            item_type: 'bar',
            aggregation: 'count',
            status: 'suggested',
            strategy: 'schema-only',
            score: 0.55,
        }));
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
    });

    await page.route(`${BASE}/api/suggestions/${SUG_ID}/accept`, (route) => {
        inbox.delete(SUG_ID);
        dashboardItems.push({
            id: ITEM_ID,
            dashboard_id: DASH_ID,
            suggestion_id: SUG_ID,
            name: TITLE,
            title: TITLE,
            item_type: 'bar',
            aggregation: 'count',
        });
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ id: SUG_ID, status: 'accepted' }),
        });
    });

    await page.route(`${BASE}/api/suggestions/${SUG_ID}/dismiss`, (route) => {
        inbox.delete(SUG_ID);
        // Dismiss does NOT add the item to any dashboard.
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ id: SUG_ID, status: 'dismissed' }),
        });
    });

    await page.route(`${BASE}/api/dashboards`, (route) => {
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify([{ id: DASH_ID, name: 'Operations', title: 'Operations' }]),
        });
    });

    await page.route(`${BASE}/api/dashboard-items`, (route) => {
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(dashboardItems) });
    });

    await page.route(`${BASE}/api/dashboard-items/${ITEM_ID}/data`, (route) => {
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ value: 42, label: 'Orders' }),
        });
    });
}

test('issue572 freeform', async ({ page }) => {
    await installRoutes(page);
    await page.addInitScript((t) => { window.sessionStorage.setItem('aicrm_token', t); }, TOKEN);

    // Open the studio and act on the inbox there.
    await page.goto('/studio.html?panel=suggestions');
    const card = page.locator(`[data-testid="suggestion"][data-id="${SUG_ID}"]`);
    await expect(card).toBeVisible();
    await expect(card.getByText(TITLE)).toBeVisible();

    await card.locator('[data-action="accept"]').click();

    // The inbox re-renders from the (now empty) mocked list, so the card leaves the screen.
    await expect(page.locator(`[data-testid="suggestion"][data-id="${SUG_ID}"]`)).toHaveCount(0);

    // Assert the accepted item lands on a dashboard by opening /.
    await page.goto('/');
    const item = page.locator('[data-testid="dashboard-item"]', { hasText: TITLE });
    await expect(item).toBeVisible();
    const chart = item.getByTestId('chart');
    await expect(chart).toBeVisible();

    // The fill must terminate: a rendered chart (svg / kpi / value list) or a non-empty
    // explanatory note — never left on the transient "Loading data…" placeholder.
    await expect
        .poll(async () => {
            if (await chart.locator('[data-testid="chart-svg"], [data-testid="chart-kpi"]').count()) {
                return 'rendered';
            }
            const notes = await chart.locator('[data-testid="chart-note"]').allTextContents();
            if (notes.length && notes[0].trim() && !notes[0].startsWith('Loading')) return 'note';
            return 'pending';
        }, { timeout: 10000 })
        .not.toBe('pending');
});

test('issue572 freeform (viewer)', async ({ page }) => {
    // Non-admin pass: boot the production way as a role 'user' identity
    // (the token in the URL hash) and prove the studio inbox still renders
    // while the admin-only controls are absent.
    await bootAs(page, VIEWER_ME, VIEWER_TOKEN, '/studio.html?panel=suggestions');

    // The page renders for a non-admin: the Suggestions tool shows its
    // inbox in a terminal state (the mocked list is empty)...
    await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Suggestions');
    await expect(page.locator('[data-testid="inbox"]')).toContainText('No pending suggestions.');
    await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

    // ...with the admin-only controls absent: the role-gated Feed keys nav
    // item leaves the DOM, the Feed keys section is removed by its module,
    // and the admin-only source form is gone.
    await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
    await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('#source-form')).toHaveCount(0);
});
