const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue588 surgical', async ({ browser }) => {
    // Scenario 1: production auth + unauthenticated → navigates to index.html
    const ctx1 = await browser.newContext();
    const page1 = await ctx1.newPage();

    await page1.route('**/api/**', async (route) => {
        const url = route.request().url();
        if (url.includes('/auth/config')) {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ authEnabled: true, authMode: 'production' }),
            });
        } else if (url.includes('/auth/me')) {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ authenticated: false, user: null }),
            });
        } else {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify([]),
            });
        }
    });

    await page1.goto('/studio.html');
    await page1.waitForURL('**/index.html', { timeout: 8000 });
    expect(page1.url()).toContain('index.html');
    await ctx1.close();

    // Scenario 2: /api/auth/config unreachable → modules start, no navigation
    const ctx2 = await browser.newContext();
    const page2 = await ctx2.newPage();

    await page2.route('**/api/**', async (route) => {
        const url = route.request().url();
        if (url.includes('/auth/config')) {
            await route.abort();
        } else if (url.includes('/auth/me')) {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ authenticated: false, user: null }),
            });
        } else {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify([]),
            });
        }
    });

    await page2.goto('/studio.html');
    await page2.waitForLoadState('networkidle', { timeout: 8000 });
    expect(page2.url()).toContain('studio.html');
    await ctx2.close();
});
