const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue607 surgical', async ({ page }) => {
  const mockApi = (roles) => {
    return async (route) => {
      const url = route.request().url();

      if (url.includes('/api/auth/config')) {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
        });
      }

      if (url.includes('/api/auth/me')) {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({ authenticated: true, user: { username: 'testuser', roles } }),
        });
      }

      if (url.includes('/api/load-sequences')) {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify([{ id: 'seq-1', name: 'Seq' }]),
        });
      }

      if (url.includes('/api/sequence-runs')) {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify([{ id: 'run-1', name: 'Run 1', sequence_id: 'seq-1', status: 'completed' }]),
        });
      }

      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([]),
      });
    };
  };

  // --- Pass 1: viewer (non-admin) — execute button must be ABSENT ---
  await page.route('**/api/**', mockApi(['viewer']));
  await page.goto('/studio.html');

  const seqRowViewer = page.locator('[data-testid="sequence-row"]');
  await expect(seqRowViewer).toBeVisible();
  await seqRowViewer.click();

  const runRowViewer = page.locator('[data-testid="run-row"]');
  await expect(runRowViewer.first()).toBeVisible();

  // Run history is rendered (read-only, unchanged)
  await expect(page.locator('[data-panel="sequence-runs"]')).toContainText('Run 1');

  // Execute button must be absent for non-admin
  const executeBtnViewer = page.locator('[data-testid="sequence-execute"]');
  await expect(executeBtnViewer).toHaveCount(0);

  // --- Pass 2: admin — execute button must be PRESENT ---
  await page.route('**/api/**', mockApi(['admin']));
  await page.goto('/studio.html');

  const seqRowAdmin = page.locator('[data-testid="sequence-row"]');
  await expect(seqRowAdmin).toBeVisible();
  await seqRowAdmin.click();

  const runRowAdmin = page.locator('[data-testid="run-row"]');
  await expect(runRowAdmin.first()).toBeVisible();

  // Run history is rendered (read-only, unchanged)
  await expect(page.locator('[data-panel="sequence-runs"]')).toContainText('Run 1');

  // Execute button must be present for admin
  const executeBtnAdmin = page.locator('[data-testid="sequence-execute"]');
  await expect(executeBtnAdmin).toHaveCount(1);
  await expect(executeBtnAdmin).toBeVisible();
});
