const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue578 surgical', async ({ page }) => {
    let meFetchCount = 0;

    await page.route('**/api/**', async (route) => {
        const url = route.request().url();
        if (url.includes('/auth/config')) {
            return route.fulfill({ json: { authEnabled: true, authMode: 'development' } });
        }
        if (url.includes('/auth/me')) {
            meFetchCount++;
            return route.fulfill({ json: { authenticated: true, user: { username: 'testuser', roles: ['admin'] } } });
        }
        return route.fulfill({ json: { ok: true, data: [] } });
    });

    await page.goto('/studio.html');

    // Wait for the initial Auth.init() to fully resolve (user object set)
    await page.waitForFunction(() => Auth._user !== null);

    const meCountAfterBoot = meFetchCount;

    // Second call: must resolve with the same user object and NOT re-fetch /auth/me
    const result = await page.evaluate(() => Auth.init());

    expect(result).not.toBeNull();
    expect(typeof result).toBe('object');
    expect(result.username).toBe('testuser');
    expect(meFetchCount).toBe(meCountAfterBoot);
});
