'use strict';

// Proof for issue #702 — revoking and deleting feed keys in the Studio
// "Feed keys" panel (app/js/feed_keys.js).
//
// Boots /studio.html?panel=feedkeys as an admin (roles: ["admin"]) with
// every /api/** request mocked — one active and one revoked credential —
// and records every PUT and DELETE the page sends.  It proves:
//   AC-1  for an admin each credential that is not revoked has a
//         "Revoke" button carrying data-requires-role="admin"; clicking
//         it shows "Revoke <name>? Tools using this key will stop
//         working." with "Confirm revoke" and "Cancel"; "Confirm revoke"
//         sends PUT /api/feed-credentials/<id> with only
//         {"revoked": true} and reloads the table (the row turns
//         "Revoked" and loses its Revoke button); "Cancel" sends
//         nothing; a failed PUT shows "Could not revoke the key." in
//         the row
//   AC-2  for an admin every credential row has a "Delete" button
//         carrying data-requires-role="admin"; clicking it shows
//         "Delete <name>?" with "Confirm delete" and "Cancel";
//         "Confirm delete" sends DELETE /api/feed-credentials/<id> and
//         reloads the table (the row is gone); "Cancel" sends nothing;
//         a failed DELETE shows "Could not delete the key." in the row;
//         for a non-admin neither Revoke nor Delete is rendered
//   AC-3  this spec: records every PUT and DELETE and proves that the
//         revoked credential has no "Revoke" button, that Revoke
//         followed by Confirm sends exactly {"revoked": true} to the
//         active credential's id, that Delete followed by Confirm sends
//         one DELETE for that id, that Cancel sends nothing in either
//         flow, and that a user with roles: ["viewer"] sees no Revoke
//         or Delete buttons
//   Identity  the criteria concern roles, so the proof also runs a
//         non-admin pass (roles: ["viewer"]) booted the production way:
//         the token in the URL hash (#access_token=...), /api/auth/
//         config and /api/auth/me mocked for that user, and the hash
//         token reaching /api/auth/me as a Bearer header while the page
//         still renders with the admin-only controls absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const VIEWER_ME = {
  authenticated: true,
  user: { id: 9, username: 'viewer', roles: ['viewer'] },
};

const ACTIVE_ID = 'fc-active';
const REVOKED_ID = 'fc-revoked';

// One active and one revoked credential; the in-memory list the mock
// serves and mutates for successful PUT/DELETE.
let credentials = [
  {
    id: ACTIVE_ID,
    name: 'BI export',
    principal: 'svc-bi',
    key_prefix: 'abcd1234',
    revoked: false,
    created_at: '2026-09-15T10:30:00',
    updated_at: '2026-09-15T10:30:00',
  },
  {
    id: REVOKED_ID,
    name: 'Legacy ETL',
    principal: null,
    key_prefix: null,
    revoked: true,
    created_at: '2026-07-01T08:00:00',
    updated_at: '2026-08-20T12:00:00',
  },
];

let meBody = ADMIN_ME;
let meAuthorization = [];
let writeRequests = []; // every PUT/DELETE the page sends: { method, url, body }
let listGets = []; // every GET /api/feed-credentials url
let revokeMode = 'ok'; // 'ok' | 'fail'
let deleteMode = 'ok'; // 'ok' | 'fail'

test('issue702 freeform', async ({ page }) => {
  await page.route('**/api/**', async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    if (method === 'PUT' || method === 'DELETE') {
      writeRequests.push({ method, url, body: request.postData() || '' });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorization.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (url.includes('/api/feed-credentials')) {
      if (method === 'GET') {
        listGets.push(url);
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(credentials),
        });
      }
      const idMatch = url.match(/\/api\/feed-credentials\/([^/?#]+)$/);
      const id = idMatch ? decodeURIComponent(idMatch[1]) : '';
      if (method === 'PUT' && id) {
        if (revokeMode === 'fail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 'revoke blew up' }),
          });
        }
        const cred = credentials.find((c) => c.id === id);
        if (!cred) {
          return route.fulfill({
            status: 404,
            contentType: 'application/json',
            body: JSON.stringify({ detail: "FeedCredential '" + id + "' not found." }),
          });
        }
        cred.revoked = true;
        cred.updated_at = '2026-10-07T13:00:00';
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(cred),
        });
      }
      if (method === 'DELETE' && id) {
        if (deleteMode === 'fail') {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 'delete blew up' }),
          });
        }
        const index = credentials.findIndex((c) => c.id === id);
        if (index === -1) {
          return route.fulfill({
            status: 404,
            contentType: 'application/json',
            body: JSON.stringify({ detail: "FeedCredential '" + id + "' not found." }),
          });
        }
        credentials.splice(index, 1);
        return route.fulfill({ status: 204, contentType: 'text/plain', body: '' });
      }
      return route.fulfill({
        status: 403,
        contentType: 'application/json',
        body: JSON.stringify({ detail: 'no' }),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // ------------------------------------------------------------------
  // Phase 1 — admin boot (roles: ["admin"]): the active row carries a
  // "Revoke" button, every row carries a "Delete" button, and the
  // revoked credential carries no "Revoke" button
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=feedkeys');

  const section = page.locator('[data-panel="feedkeys"]');
  await expect(section).toBeVisible();
  await expect(section).toHaveAttribute('data-requires-role', 'admin');

  const table = page.locator('[data-testid="feedkeys-table"]');
  await expect(table).toBeVisible();
  const rows = table.locator('[data-testid="feedkeys-row"]');
  await expect(rows).toHaveCount(2);

  const activeRow = rows.nth(0);
  const revokedRow = rows.nth(1);
  await expect(activeRow.locator('[data-testid="feedkeys-name"]')).toHaveText('BI export');
  await expect(activeRow.locator('[data-testid="feedkeys-status"]')).toHaveText('Active');
  await expect(revokedRow.locator('[data-testid="feedkeys-name"]')).toHaveText('Legacy ETL');
  await expect(revokedRow.locator('[data-testid="feedkeys-status"]')).toHaveText('Revoked');

  // AC-1: the active credential has a "Revoke" button carrying
  // data-requires-role="admin"
  const revokeBtn = activeRow.locator('[data-testid="feedkeys-revoke-btn"]');
  await expect(revokeBtn).toHaveCount(1);
  await expect(revokeBtn).toHaveText('Revoke');
  await expect(revokeBtn).toHaveAttribute('data-requires-role', 'admin');

  // AC-2: every credential row has a "Delete" button carrying
  // data-requires-role="admin"
  const deleteActiveBtn = activeRow.locator('[data-testid="feedkeys-delete-btn"]');
  await expect(deleteActiveBtn).toHaveCount(1);
  await expect(deleteActiveBtn).toHaveText('Delete');
  await expect(deleteActiveBtn).toHaveAttribute('data-requires-role', 'admin');
  const deleteRevokedBtn = revokedRow.locator('[data-testid="feedkeys-delete-btn"]');
  await expect(deleteRevokedBtn).toHaveCount(1);
  await expect(deleteRevokedBtn).toHaveText('Delete');
  await expect(deleteRevokedBtn).toHaveAttribute('data-requires-role', 'admin');

  // AC-3: the revoked credential has no "Revoke" button
  await expect(revokedRow.locator('[data-testid="feedkeys-revoke-btn"]')).toHaveCount(0);

  // ------------------------------------------------------------------
  // Phase 2 — AC-1: clicking "Revoke" shows the confirmation; "Cancel"
  // sends nothing
  // ------------------------------------------------------------------
  await revokeBtn.click();
  const revokeConfirm = page.locator('[data-testid="feedkeys-revoke-confirm"]');
  await expect(revokeConfirm).toBeVisible();
  await expect(revokeConfirm.locator('[data-testid="feedkeys-revoke-note"]')).toHaveText(
    'Revoke BI export? Tools using this key will stop working.'
  );
  await expect(page.locator('[data-testid="feedkeys-revoke-confirm-ok"]')).toHaveText(
    'Confirm revoke'
  );
  await expect(page.locator('[data-testid="feedkeys-revoke-confirm-cancel"]')).toHaveText(
    'Cancel'
  );

  await page.locator('[data-testid="feedkeys-revoke-confirm-cancel"]').click();
  await expect(revokeConfirm).toHaveCount(0);
  await expect(revokeBtn).toHaveCount(1);
  expect(writeRequests).toHaveLength(0);

  // ------------------------------------------------------------------
  // Phase 3 — AC-1: a failed "Confirm revoke" sends the PUT and shows
  // "Could not revoke the key." in the row
  // ------------------------------------------------------------------
  revokeMode = 'fail';
  await revokeBtn.click();
  await page.locator('[data-testid="feedkeys-revoke-confirm-ok"]').click();
  await expect.poll(() => writeRequests.length).toBe(1);
  expect(writeRequests[0].method).toBe('PUT');
  expect(writeRequests[0].url.endsWith('/api/feed-credentials/' + ACTIVE_ID)).toBe(true);
  await expect(
    activeRow.locator('[data-testid="feedkeys-revoke-error"]')
  ).toHaveText('Could not revoke the key.');
  // the row is still active and its buttons are back
  await expect(activeRow.locator('[data-testid="feedkeys-status"]')).toHaveText('Active');
  await expect(revokeBtn).toHaveCount(1);
  await expect(rows).toHaveCount(2);

  // ------------------------------------------------------------------
  // Phase 4 — AC-1/AC-3: "Confirm revoke" on the active credential
  // sends exactly {"revoked": true} to its id and reloads the table
  // ------------------------------------------------------------------
  revokeMode = 'ok';
  listGets.length = 0;
  await revokeBtn.click();
  await page.locator('[data-testid="feedkeys-revoke-confirm-ok"]').click();
  await expect.poll(() => writeRequests.length).toBe(2);
  const put = writeRequests[1];
  expect(put.method).toBe('PUT');
  expect(put.url.endsWith('/api/feed-credentials/' + ACTIVE_ID)).toBe(true);
  expect(JSON.parse(put.body)).toEqual({ revoked: true });
  // the table reloaded and the row is now revoked: "Revoked" status, no
  // Revoke button, still a Delete button
  await expect.poll(() => listGets.length).toBeGreaterThanOrEqual(1);
  await expect(rows).toHaveCount(2);
  const revokedActiveRow = rows.nth(0);
  await expect(revokedActiveRow.locator('[data-testid="feedkeys-name"]')).toHaveText(
    'BI export'
  );
  await expect(revokedActiveRow.locator('[data-testid="feedkeys-status"]')).toHaveText(
    'Revoked'
  );
  await expect(revokedActiveRow.locator('[data-testid="feedkeys-revoke-btn"]')).toHaveCount(0);
  await expect(revokedActiveRow.locator('[data-testid="feedkeys-delete-btn"]')).toHaveCount(1);

  // ------------------------------------------------------------------
  // Phase 5 — AC-2: clicking "Delete" shows "Delete <name>?" with
  // "Confirm delete" and "Cancel"; "Cancel" sends nothing
  // ------------------------------------------------------------------
  const deleteBtn = rows.nth(1).locator('[data-testid="feedkeys-delete-btn"]');
  await deleteBtn.click();
  const deleteConfirm = page.locator('[data-testid="feedkeys-delete-confirm"]');
  await expect(deleteConfirm).toBeVisible();
  await expect(deleteConfirm.locator('[data-testid="feedkeys-delete-note"]')).toHaveText(
    'Delete Legacy ETL?'
  );
  await expect(page.locator('[data-testid="feedkeys-delete-confirm-ok"]')).toHaveText(
    'Confirm delete'
  );
  await expect(page.locator('[data-testid="feedkeys-delete-confirm-cancel"]')).toHaveText(
    'Cancel'
  );

  await page.locator('[data-testid="feedkeys-delete-confirm-cancel"]').click();
  await expect(deleteConfirm).toHaveCount(0);
  await expect(deleteBtn).toHaveCount(1);
  // still exactly the two PUTs — the cancels sent nothing
  expect(writeRequests).toHaveLength(2);

  // ------------------------------------------------------------------
  // Phase 6 — AC-2: a failed "Confirm delete" sends the DELETE and
  // shows "Could not delete the key." in the row
  // ------------------------------------------------------------------
  deleteMode = 'fail';
  const deleteActiveAgain = rows.nth(0).locator('[data-testid="feedkeys-delete-btn"]');
  await deleteActiveAgain.click();
  await page.locator('[data-testid="feedkeys-delete-confirm-ok"]').click();
  await expect.poll(() => writeRequests.length).toBe(3);
  expect(writeRequests[2].method).toBe('DELETE');
  expect(writeRequests[2].url.endsWith('/api/feed-credentials/' + ACTIVE_ID)).toBe(true);
  await expect(
    rows.nth(0).locator('[data-testid="feedkeys-delete-error"]')
  ).toHaveText('Could not delete the key.');
  // the row is still there
  await expect(rows).toHaveCount(2);

  // ------------------------------------------------------------------
  // Phase 7 — AC-2/AC-3: "Confirm delete" sends one DELETE for the id
  // and reloads the table with the row gone
  // ------------------------------------------------------------------
  deleteMode = 'ok';
  listGets.length = 0;
  const writesBefore = writeRequests.length;
  await deleteActiveAgain.click();
  await page.locator('[data-testid="feedkeys-delete-confirm-ok"]').click();
  await expect.poll(() => writeRequests.length).toBe(writesBefore + 1);
  const del = writeRequests[writesBefore];
  expect(del.method).toBe('DELETE');
  expect(del.url.endsWith('/api/feed-credentials/' + ACTIVE_ID)).toBe(true);
  expect(del.body).toBe('');
  // the table reloaded and the deleted credential's row is gone
  await expect.poll(() => listGets.length).toBeGreaterThanOrEqual(1);
  await expect(rows).toHaveCount(1);
  await expect(rows.nth(0).locator('[data-testid="feedkeys-name"]')).toHaveText('Legacy ETL');

  // ------------------------------------------------------------------
  // AC-3 — the write log holds exactly two PUTs and two DELETEs, all
  // for the active credential's id, every PUT body exactly
  // {"revoked": true}, and nothing else was ever written
  // ------------------------------------------------------------------
  expect(writeRequests).toHaveLength(4);
  const puts = writeRequests.filter((r) => r.method === 'PUT');
  const dels = writeRequests.filter((r) => r.method === 'DELETE');
  expect(puts).toHaveLength(2);
  expect(dels).toHaveLength(2);
  for (const r of writeRequests) {
    expect(r.url.endsWith('/api/feed-credentials/' + ACTIVE_ID)).toBe(true);
  }
  for (const r of puts) {
    expect(JSON.parse(r.body)).toEqual({ revoked: true });
  }

  // ------------------------------------------------------------------
  // Phase 8 — identity: a user with roles: ["viewer"] booted the
  // production way (token in the URL hash, /api/auth/config and
  // /api/auth/me mocked for that user) sees the page render with no
  // Revoke or Delete buttons, and no request reaches
  // /api/feed-credentials
  // ------------------------------------------------------------------
  meBody = VIEWER_ME;
  meAuthorization = [];
  writeRequests = [];
  listGets = [];
  revokeMode = 'ok';
  deleteMode = 'ok';
  // A fragment-only URL change would be a same-document navigation and
  // Auth.init() would not re-run; go through about:blank so this boot is
  // a full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys#access_token=viewer-token-702');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer viewer-token-702');
  // the page still renders its other panels ...
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policies-empty"]')).toHaveText(
    'No retention policies yet.'
  );
  // ... but the admin-only Feed keys section (and with it the Revoke and
  // Delete buttons) is gone
  await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="feedkeys-revoke-btn"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="feedkeys-delete-btn"]')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Revoke', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Delete', exact: true })).toHaveCount(0);
  // and no request reached /api/feed-credentials
  expect(listGets).toHaveLength(0);
  expect(writeRequests).toHaveLength(0);
});
