const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue568 surgical', async ({ page }) => {
    // Scenario 1: Auth.init() rejects → error rendered, no protected API requests
    {
        const apiCalls = [];
        await page.route('**/api/**', async (route) => {
            apiCalls.push(route.request().url());
            await route.fulfill({ status: 200, contentType: 'application/json', body: '{}' });
        });
        await page.route('**/js/auth.js', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/javascript',
                body: 'window.Auth = { init: function() { return Promise.reject(new Error("token expired")); } };'
            });
        });
        await page.goto('/studio.html');
        const authStatus = page.locator('#auth-status');
        await expect(authStatus).toContainText('Authentication failed');
        expect(apiCalls.length).toBe(0);
    }

    // Scenario 2: Auth.init() resolves null → redirect to login flow
    {
        await page.route('**/js/auth.js', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/javascript',
                body: 'window.Auth = { init: function() { return Promise.resolve(null); } };'
            });
        });
        const redirect = page.waitForURL('**/index.html');
        await page.goto('/studio.html');
        await redirect;
        expect(page.url()).toContain('index.html');
    }

    // Scenario 3: Auth.init() resolves user → modules start, token stored, no error
    {
        await page.route('**/api/**', async (route) => {
            await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: [] }) });
        });
        await page.route('**/js/auth.js', async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/javascript',
                body: [
                    'window.Auth = { init: function() {',
                    '  var h = window.location.hash;',
                    '  var m = h.match(/token=([^&]+)/);',
                    '  var t = m ? m[1] : null;',
                    '  if (t) { localStorage.setItem("auth_token", t); }',
                    '  return Promise.resolve(t ? { id: 1, name: "user" } : null);',
                    '}};'
                ].join('\n')
            });
        });
        await page.goto('/studio.html#token=test-token-123');
        await page.waitForFunction(() => localStorage.getItem('auth_token') === 'test-token-123');
        expect(page.url()).toContain('studio.html');
        const authStatus = page.locator('#auth-status');
        await expect(authStatus).not.toContainText('Authentication failed');
        const token = await page.evaluate(() => localStorage.getItem('auth_token'));
        expect(token).toBe('test-token-123');
    }
});
