const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

test.setTimeout(90 * 1000); // generous ceiling: two full document loads + panel renders

test('issue681 freeform', async ({ page }) => {
    // Boot /studio.html?panel=sequences the way production does: the token rides
    // the URL hash, /api/auth/config and /api/auth/me are mocked, and every other
    // /api/** request answers with an empty list. The current identity is swapped
    // per pass (distinct tokens keep each pass's hash migration unambiguous).

    // Same origin the Playwright config serves (python http.server on app/).
    const base = process.env.BASE_URL || 'http://127.0.0.1:8080';

    let identity = null;

    const fulfill = (route, status, body) => route.fulfill({
        status,
        contentType: 'application/json',
        body: JSON.stringify(body),
    });

    await page.route('**/api/**', async (route) => {
        const url = route.request().url();
        if (url.includes('/api/auth/config')) {
            return fulfill(route, 200, { authEnabled: true, authMode: 'development' });
        }
        if (url.includes('/api/auth/me')) {
            return fulfill(route, 200, {
                authenticated: true,
                user: { username: identity.username, sub: identity.sub, roles: identity.roles },
            });
        }
        // Every other /api/** request: an empty list.
        return fulfill(route, 200, []);
    });

    const boot = async (token, user) => {
        identity = user;
        // Force a full document load per pass: going straight from the pass-1
        // URL to the pass-2 URL would differ only in the hash fragment, which
        // is a same-document navigation — no reload, Auth.init() never re-runs,
        // and the new hash token would never be migrated into sessionStorage.
        await page.goto('about:blank');
        await page.goto(`${base}/studio.html?panel=sequences#access_token=${token}`);

        // Production boot path: the hash token was migrated into sessionStorage
        // by Auth.init() before any /api request went out.
        const stored = await page.evaluate(() => sessionStorage.getItem('aicrm_token'));
        expect(stored).toBe(token);
        // The page stayed put (no unauthenticated redirect away from the studio).
        expect(page.url()).toContain('studio.html');
        // Terminal state of the sequences panel for this identity.
        await expect(page.locator('[data-testid="sequence-name-input"]')).toBeVisible();
    };

    // Pass 1 — admin: the Create sequence control is rendered and carries the
    // role attribute on the control element itself.
    await boot('issue681-admin-token', { username: 'admin', sub: 'admin', roles: ['admin'] });
    const createBtn = page.locator('[data-testid="sequence-create"]');
    await expect(createBtn).toBeVisible();
    await expect(createBtn).toHaveAttribute('data-requires-role', 'admin');

    // Pass 2 — non-admin (role "user"): the gating is unchanged — no element
    // carrying data-requires-role="admin" exists anywhere in the document —
    // and the sequences panel still renders.
    await boot('issue681-user-token', { username: 'jane', sub: 'jane', roles: ['user'] });

    // Race guard: every admin control in the studio lands through a delayed
    // render path, so a count of 0 read while those renders are still in
    // flight would race the render and pass on the first zero. Anchor on each
    // path's terminal state before the no-attribute check:
    //   sequences-empty -> the Sequences.init() list commit (where sequence-create would land)
    //   #sources note   -> Sources.init() has run the source-form/src-submit gate + refresh
    //   #inbox note     -> the Warehouse.init() refresh (layout-editor render path) has settled
    await expect(page.locator('[data-testid="sequences-empty"]')).toHaveText(/No load sequences yet/);
    await expect(page.locator('#sources')).toContainText(/No sources yet/);
    await expect(page.locator('#inbox')).toContainText(/No pending suggestions/);
    await expect(page.locator('[data-requires-role="admin"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="sequence-name-input"]')).toBeVisible();
});
