'use strict';

// Proof for issue #740 — the read-only "Feed keys" admin panel on
// /studio.html (app/js/feed_keys.js + the feedkeys section in
// app/studio.html).
//
// Boots /studio.html?panel=feedkeys as an admin (roles: ["admin"]) with
// /api/auth/config and /api/auth/me mocked and GET /api/feed-credentials
// mocked, and proves:
//   AC-1  the section <section class="wh-panel" data-panel="feedkeys"
//         data-requires-role="admin"> carries the "Feed keys" heading,
//         the module app/js/feed_keys.js defines const FeedKeys with an
//         init() called on Studio boot, and for an admin it calls
//         GET /api/feed-credentials through the API client and shows the
//         feed address /api/feed/v4 and the sentence
//         "Excel and BI tools read the feed with a key sent as the
//         X-Api-Key header." above a table with one row per credential:
//         name, principal, key prefix + "…" (or "no key issued" when
//         there is no prefix), "Revoked" or "Active", and created time —
//         values written with textContent; with no credentials it shows
//         "No feed keys yet."; a failed request shows "Could not load
//         feed keys."; when Auth.isAdmin() is false or throws the
//         section stays hidden and no request is made; nothing in the
//         section changes data (no forms or buttons, no POST/PUT/DELETE)
//   AC-2  with two mocked credentials — one active with prefix abcd1234
//         and one revoked with no prefix, whose response object also
//         carries a key_hash of deadbeefcafe — both rows render with
//         their fields and statuses, the "no key issued" text appears,
//         the feed path and the header sentence are shown, and
//         deadbeefcafe appears nowhere in the page's text or attributes;
//         a boot with an empty list shows "No feed keys yet."; a boot
//         with a 500 shows "Could not load feed keys."; a boot as a user
//         with roles: ["user"] shows no Feed keys section and sends no
//         request to /api/feed-credentials
//   AC-3  the feed-credentials read is admin-gated client-side for this
//         section: the section itself carries data-requires-role="admin"
//         and the only thing standing between the page and
//         GET /api/feed-credentials is Auth.isAdmin(); the API edge's
//         own role check is pre-existing (issue #741) and not re-proved
//         here
//   AC-4  this proof verifies only client-side admin gating and
//         rendering — it requires no new backend authorization code
//   Identity  the criteria concern roles, so the proof also runs a
//         non-admin pass (role 'user') booted the production way: the
//         token in the URL hash (#access_token=...), /api/auth/config
//         and /api/auth/me mocked for that user, and the hash token
//         reaching /api/auth/me as a Bearer header while the page still
//         renders with the admin-only control absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const USER_ME = {
  authenticated: true,
  user: { id: 9, username: 'user', roles: ['user'] },
};

// Two mocked credentials: one active with a key prefix, one revoked with
// no prefix.  The revoked one deliberately carries a key_hash in the
// response object to prove key material never reaches the page.
const CREDENTIALS = [
  {
    id: 'fc-1',
    name: 'BI export',
    principal: 'svc-bi',
    key_prefix: 'abcd1234',
    revoked: false,
    created_at: '2026-09-15T10:30:00',
    updated_at: '2026-09-15T10:30:00',
  },
  {
    id: 'fc-2',
    name: 'Legacy ETL',
    principal: null,
    key_prefix: null,
    revoked: true,
    key_hash: 'deadbeefcafe',
    created_at: '2026-07-01T08:00:00',
    updated_at: '2026-08-20T12:00:00',
  },
];

// Phase switches for the single mock.
let meBody = ADMIN_ME;
let credentialsMode = 'ok'; // 'ok' | 'empty' | 'error'
let meAuthorization = [];
let feedCredentialRequests = [];
let writeRequests = [];

test('issue740 freeform', async ({ page }) => {
  await page.route('**/api/**', async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    if (method !== 'GET' && method !== 'HEAD') {
      writeRequests.push({ method, url });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorization.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (url.includes('/api/feed-credentials')) {
      if (method !== 'GET') return route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ detail: 'no' }) });
      feedCredentialRequests.push(url);
      if (credentialsMode === 'empty') {
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
      }
      if (credentialsMode === 'error') {
        return route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ detail: 'credentials unavailable' }),
        });
      }
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(CREDENTIALS),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // ------------------------------------------------------------------
  // Phase 1 — admin boot (roles: ["admin"]): the section renders the
  // feed address, the header sentence and one row per credential
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=feedkeys');

  // the module is loaded and defines const FeedKeys with an init()
  expect(await page.locator('script[src="js/feed_keys.js"]').count()).toBe(1);
  expect(
    await page.evaluate(
      () => typeof window.FeedKeys !== 'undefined' && typeof window.FeedKeys.init === 'function'
    )
  ).toBe(true);

  const section = page.locator('[data-panel="feedkeys"]');
  await expect(section).toBeVisible();
  await expect(section).toHaveAttribute('data-requires-role', 'admin');
  await expect(section.locator('h2')).toHaveText('Feed keys');

  // the feed address and the header sentence, above the table
  expect(await page.locator('[data-testid="feedkeys-address"]').innerText()).toBe('/api/feed/v4');
  await expect(page.locator('[data-testid="feedkeys-note"]')).toHaveText(
    'Excel and BI tools read the feed with a key sent as the X-Api-Key header.'
  );

  // one row per credential, with its five fields and status
  const table = page.locator('[data-testid="feedkeys-table"]');
  await expect(table).toBeVisible();
  await expect(table.locator('[data-testid="feedkeys-row"]')).toHaveCount(2);

  const rowActive = table.locator('[data-testid="feedkeys-row"]').first();
  await expect(rowActive.locator('[data-testid="feedkeys-name"]')).toHaveText('BI export');
  await expect(rowActive.locator('[data-testid="feedkeys-principal"]')).toHaveText('svc-bi');
  await expect(rowActive.locator('[data-testid="feedkeys-key"]')).toHaveText('abcd1234\u2026');
  await expect(rowActive.locator('[data-testid="feedkeys-status"]')).toHaveText('Active');
  await expect(rowActive.locator('[data-testid="feedkeys-created"]')).toHaveText('2026-09-15T10:30:00');

  const rowRevoked = table.locator('[data-testid="feedkeys-row"]').last();
  await expect(rowRevoked.locator('[data-testid="feedkeys-name"]')).toHaveText('Legacy ETL');
  expect((await rowRevoked.locator('[data-testid="feedkeys-principal"]').innerText()).trim()).toBe('');
  // the no-prefix text appears
  await expect(rowRevoked.locator('[data-testid="feedkeys-key"]')).toHaveText('no key issued');
  await expect(rowRevoked.locator('[data-testid="feedkeys-status"]')).toHaveText('Revoked');
  await expect(rowRevoked.locator('[data-testid="feedkeys-created"]')).toHaveText('2026-07-01T08:00:00');

  // the key_hash of the revoked credential appears nowhere in the page:
  // not in any text — rendered or not (the document title, hidden
  // elements, <template> contents, even the source of <script>/<style>
  // tags; a rendered-text scan such as body.innerText would miss all of
  // that) — and not in any attribute.  outerHTML serializes the whole
  // document: every element, every attribute value, every text node.
  expect(
    await page.evaluate(() =>
      document.documentElement.outerHTML.includes('deadbeefcafe')
    )
  ).toBe(false);

  // nothing in the section changes data: no interactive controls at all
  expect(await section.locator('form, button, input, select, textarea, a[href]').count()).toBe(0);

  // ------------------------------------------------------------------
  // Phase 2 — Auth.isAdmin() throws: the section stays hidden and no
  // request to /api/feed-credentials is made
  // ------------------------------------------------------------------
  // Init scripts run before the page's own scripts, so the DOMContentLoaded
  // listener below is registered first and installs the throwing stub before
  // Studio boot (and therefore before FeedKeys.init()) ever runs.  The stub
  // is armed through a sessionStorage flag: Playwright has no API to remove
  // an added init script, so the flag scopes the stub to exactly this boot
  // (it is cleared again before the next navigation).
  const throwAdmin = () => {
    let armed = false;
    try { armed = sessionStorage.getItem('feedkeys-throw-admin') === '1'; } catch (e) {}
    if (!armed) return;
    const apply = () => {
      // auth.js declares `const Auth` at the top level: a global lexical
      // binding, not a property of window, so the stub must patch the
      // object through the global name.  The first pass (before auth.js
      // has parsed) is a no-op; the DOMContentLoaded pass runs after every
      // classic script, so the stub is installed before Studio boot.
      if (
        typeof Auth !== 'undefined' &&
        typeof Auth.isAdmin === 'function' &&
        !window.__feedkeysAuthStubbed
      ) {
        window.__feedkeysAuthStubbed = true;
        Auth.isAdmin = () => {
          throw new Error('stubbed throw');
        };
      }
    };
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', apply, { once: true });
    }
    apply();
  };
  await page.addInitScript(throwAdmin);
  await page.evaluate(() => { sessionStorage.setItem('feedkeys-throw-admin', '1'); });
  feedCredentialRequests.length = 0;
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys');
  await page.evaluate(() => { sessionStorage.removeItem('feedkeys-throw-admin'); });
  // the page loaded (the other static panels are present) ...
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  // ... the Feed keys section is gone (FeedKeys.init() ran to its
  // synchronous non-admin exit, which happens before any request) ...
  await expect(page.locator('[data-panel="feedkeys"]')).toBeHidden();
  await expect(page.locator('[data-testid="feedkeys-table"]')).toHaveCount(0);
  // ... and no request to /api/feed-credentials was made
  expect(feedCredentialRequests).toHaveLength(0);

  // ------------------------------------------------------------------
  // Phase 3 — admin boot with an empty list: "No feed keys yet."
  // ------------------------------------------------------------------
  credentialsMode = 'empty';
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys');
  await expect(page.locator('[data-testid="feedkeys-empty"]')).toHaveText('No feed keys yet.');
  await expect(page.locator('[data-testid="feedkeys-table"]')).toHaveCount(0);

  // ------------------------------------------------------------------
  // Phase 4 — admin boot with a 500: "Could not load feed keys."
  // ------------------------------------------------------------------
  credentialsMode = 'error';
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys');
  await expect(page.locator('[data-testid="feedkeys-error"]')).toHaveText('Could not load feed keys.');
  await expect(page.locator('[data-testid="feedkeys-table"]')).toHaveCount(0);

  // ------------------------------------------------------------------
  // Phase 5 — identity: a user with roles: ["user"] booted the
  // production way (token in the URL hash, /api/auth/config and
  // /api/auth/me mocked for that user) sees the page render with no
  // Feed keys section, and no request reaches /api/feed-credentials
  // ------------------------------------------------------------------
  credentialsMode = 'ok';
  meBody = USER_ME;
  meAuthorization.length = 0;
  feedCredentialRequests.length = 0;
  // A fragment-only URL change would be a same-document navigation and
  // Auth.init() would not re-run; go through about:blank so this boot is
  // a full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=feedkeys#access_token=user-token-740');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer user-token-740');
  // the page still renders its other panels ...
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();
  await expect(page.locator('[data-testid="retention-policies-empty"]')).toHaveText(
    'No retention policies yet.'
  );
  // ... but the admin-only Feed keys section is hidden ...
  await expect(page.locator('[data-panel="feedkeys"]')).toBeHidden();
  await expect(page.locator('[data-testid="feedkeys-table"]')).toHaveCount(0);
  // ... and no request reached /api/feed-credentials
  expect(feedCredentialRequests).toHaveLength(0);

  // the section never wrote data in any phase
  expect(writeRequests).toEqual([]);
});
