'use strict';

// Proof for issue #699 — admin "Edit" and "Enable"/"Disable" toggle on
// the Data retention panel (app/js/retention.js).
//
// Boots /studio.html?panel=retention the production way (the token in the
// URL hash as #access_token=..., /api/auth/config and /api/auth/me mocked
// for that user) first as an admin, with the policy and dataset routes
// mocked and every PUT recorded, and proves:
//   AC-1  each admin policy row has an "Edit" button carrying
//         data-requires-role="admin"; clicking it opens the same
//         data-testid="retention-policy-form" that "Add policy" uses,
//         pre-filled with the policy's current name, table class, action,
//         retention period, scope, dataset and enabled state; changing
//         the period to 30 and saving sends one PUT to that policy's id
//         with retention_period_days 30 and the other fields unchanged;
//         success closes the form and reloads the table; a failed PUT
//         keeps the form open and shows data-testid="retention-form-error"
//         exactly as on create; clicking Edit does not select the row
//   AC-2  each admin row's Enabled/Disabled cell holds a toggle carrying
//         data-requires-role="admin", labelled "Disable" for an enabled
//         policy and "Enable" for a disabled one; "Disable" on an enabled
//         policy sends exactly {"is_enabled": false} and reloads the
//         table; a failed toggle shows "Could not update the policy." in
//         the row
//   AC-3  a full reload booted the production way for a role 'user'
//         identity still renders the page, but with no Edit or toggle
//         buttons — the Enabled/Disabled cells hold only the text
//   RD    review defects: Cancel and a failed delete restore the row's
//         full actions (the Edit button is never lost from the row); a
//         policy whose table_class/action is not in the fixed option
//         list is pre-filled with its actual values (offered as options)
//         and a save preserves them

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});



const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const USER_ME = {
  authenticated: true,
  user: { id: 9, username: 'user', roles: ['user'] },
};

const DATASETS = [
  {
    id: 'ds-orders',
    name: 'Orders',
    object_type: 'table',
    created_at: '2026-09-01T00:00:00',
    updated_at: '2026-09-01T00:00:00',
  },
  {
    id: 'ds-payments',
    name: 'Payments',
    object_type: 'table',
    created_at: '2026-09-02T00:00:00',
    updated_at: '2026-09-02T00:00:00',
  },
];

// In-memory policy store: a successful mocked PUT applies the patch, so the
// table reloads after each mutation are observable.
let policies = [
  {
    id: 'pol-1',
    name: 'Purge stale audit rows',
    dataset_id: 'ds-orders',
    table_class: 'runs',
    action: 'purge',
    retention_period_days: 14,
    scope: 'dataset',
    is_enabled: true,
  },
  {
    id: 'pol-2',
    name: 'Anonymize export PII',
    dataset_id: null,
    table_class: 'ingested_records',
    action: 'anonymize',
    retention_period_days: 90,
    scope: 'class',
    is_enabled: false,
  },
  // Legacy policy: its table_class and action are NOT in the form's
  // fixed option lists (review defect: the prefill must stay consistent
  // with the policy instead of substituting the first option).
  {
    id: 'pol-3',
    name: 'Legacy audit mask',
    dataset_id: null,
    table_class: 'audit_legacy',
    action: 'mask',
    retention_period_days: 7,
    scope: 'class',
    is_enabled: true,
  },
];

// Phase switches for the single mock.
let meBody = ADMIN_ME;
let putFail = false;
let deleteFail = false;

test('issue699 freeform', async ({ page }) => {
  // Every PUT the page sends is recorded here.
  const putRequests = [];
  const meAuthorization = [];
  const retentionPuts = () =>
    putRequests.filter((r) => r.url.includes('/api/retention-policies'));

  await page.route('**/api/**', async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    if (method === 'PUT') {
      putRequests.push({ url, body: request.postData() || null });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorization.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (url.includes('/api/datasets')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(DATASETS),
      });
    }
    if (url.includes('/api/retention-policies')) {
      if (method === 'GET') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(policies),
        });
      }
      if (method === 'PUT') {
        const id = decodeURIComponent(
          url.split('/api/retention-policies/')[1].split(/[?#]/)[0]
        );
        if (putFail) {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 'update blew up' }),
          });
        }
        const index = policies.findIndex((p) => String(p.id) === id);
        if (index === -1) {
          return route.fulfill({
            status: 404,
            contentType: 'application/json',
            body: JSON.stringify({
              detail: `RetentionPolicy '${id}' not found.`,
            }),
          });
        }
        const patch = JSON.parse(request.postData());
        policies[index] = { ...policies[index], ...patch };
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(policies[index]),
        });
      }
      if (method === 'DELETE') {
        const id = decodeURIComponent(
          url.split('/api/retention-policies/')[1].split(/[?#]/)[0]
        );
        if (deleteFail) {
          return route.fulfill({
            status: 500,
            contentType: 'application/json',
            body: JSON.stringify({ detail: 'delete blew up' }),
          });
        }
        const index = policies.findIndex((p) => String(p.id) === id);
        if (index === -1) {
          return route.fulfill({
            status: 404,
            contentType: 'application/json',
            body: JSON.stringify({
              detail: `RetentionPolicy '${id}' not found.`,
            }),
          });
        }
        const removed = policies[index];
        policies.splice(index, 1);
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(removed),
        });
      }
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // ------------------------------------------------------------------
  // Phase 1 — admin boot, the production way (token in the URL hash):
  // every row carries an admin-marked Edit button and its Enabled/
  // Disabled cell carries an admin-marked toggle with the right label
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=retention#access_token=admin-token-699');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer admin-token-699');
  await expect(page.locator('[data-testid="retention-policy-table"]')).toBeVisible();
  const rows = page.locator('[data-testid="retention-policy-row"]');
  await expect(rows).toHaveCount(3);

  const row1 = page.locator('[data-testid="retention-policy-row"][data-id="pol-1"]');
  const row2 = page.locator('[data-testid="retention-policy-row"][data-id="pol-2"]');
  await expect(row1).toBeVisible();
  await expect(row2).toBeVisible();

  // AC-1: each policy row has an "Edit" button carrying data-requires-role
  // (alongside the existing Delete button).
  const editButtons = page.locator('[data-testid="retention-policy-edit"]');
  await expect(editButtons).toHaveCount(3);
  await expect(editButtons.first()).toHaveText('Edit');
  await expect(editButtons.first()).toHaveAttribute('data-requires-role', 'admin');

  // AC-2: the Enabled/Disabled cell holds the toggle, labelled "Disable"
  // for the enabled policy and "Enable" for the disabled one.
  await expect(row1.locator('[data-testid="retention-policy-enabled-label"]')).toHaveText('Enabled');
  const toggle1 = row1.locator('[data-testid="retention-policy-toggle"]');
  await expect(toggle1).toHaveText('Disable');
  await expect(toggle1).toHaveAttribute('data-requires-role', 'admin');

  await expect(row2.locator('[data-testid="retention-policy-enabled-label"]')).toHaveText('Disabled');
  const toggle2 = row2.locator('[data-testid="retention-policy-toggle"]');
  await expect(toggle2).toHaveText('Enable');
  await expect(toggle2).toHaveAttribute('data-requires-role', 'admin');

  // ------------------------------------------------------------------
  // Phase 2 — clicking Edit does not select the row and opens the same
  // form as "Add policy", pre-filled with the row's values
  // ------------------------------------------------------------------
  const runsArea = page.locator('[data-testid="retention-runs"]');
  await row1.locator('[data-testid="retention-policy-edit"]').click();
  // ... and did not select it: the runs area still shows its placeholder
  // (a selection would have replaced it with the policy's runs).
  await expect(runsArea).toHaveText('Select a policy to see its runs.');

  const editForm = page.locator('[data-testid="retention-policy-form"]');
  await expect(editForm).toBeVisible();
  // pre-filled with the policy's current values ...
  await expect(editForm.locator('[data-testid="retention-form-name"]')).toHaveValue('Purge stale audit rows');
  await expect(editForm.locator('[data-testid="retention-form-table-class"]')).toHaveValue('runs');
  await expect(editForm.locator('[data-testid="retention-form-action"]')).toHaveValue('purge');
  await expect(editForm.locator('[data-testid="retention-form-period"]')).toHaveValue('14');
  await expect(editForm.locator('[data-testid="retention-form-scope"]')).toHaveValue('dataset');
  // ... dataset scope revealed the dataset select, set to the policy's dataset
  await expect(editForm.locator('[data-testid="retention-form-dataset-wrap"]')).toBeVisible();
  await expect(editForm.locator('[data-testid="retention-form-dataset"]')).toHaveValue('ds-orders');
  await expect(editForm.locator('[data-testid="retention-form-enabled"]')).toBeChecked();

  // ------------------------------------------------------------------
  // Phase 3 — changing the period to 30 and saving sends one PUT to the
  // policy's id with retention_period_days 30 and the other fields
  // unchanged; the form closes and the table reloads
  // ------------------------------------------------------------------
  await editForm.locator('[data-testid="retention-form-period"]').fill('30');
  await editForm.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => retentionPuts()).toHaveLength(1);
  const editPut = retentionPuts()[0];
  expect(editPut.url.endsWith('/api/retention-policies/pol-1')).toBe(true);
  expect(JSON.parse(editPut.body)).toEqual({
    name: 'Purge stale audit rows',
    table_class: 'runs',
    action: 'purge',
    retention_period_days: 30,
    scope: 'dataset',
    dataset_id: 'ds-orders',
    is_enabled: true,
  });
  // success closed the form and reloaded the table with the new period
  await expect(page.locator('[data-testid="retention-policy-form"]')).toHaveCount(0);
  await expect(
    row1.locator('td[data-testid="retention-policy-period"]')
  ).toHaveText('30 days');
  // the Edit click still never selected the row after the reload
  expect(await row1.getAttribute('data-selected')).toBeNull();
  await expect(row1).not.toHaveClass(/wh-retention-row-selected/);

  // ------------------------------------------------------------------
  // Phase 4 — "Disable" on the enabled policy sends exactly
  // {"is_enabled": false} and reloads the table; the symmetric "Enable"
  // sends exactly {"is_enabled": true}
  // ------------------------------------------------------------------
  await expect(row1.locator('[data-testid="retention-policy-toggle"]')).toHaveText('Disable');
  await row1.locator('[data-testid="retention-policy-toggle"]').click();
  await expect.poll(() => retentionPuts()).toHaveLength(2);
  const disablePut = retentionPuts()[1];
  expect(disablePut.url.endsWith('/api/retention-policies/pol-1')).toBe(true);
  expect(JSON.parse(disablePut.body)).toEqual({ is_enabled: false });
  // the reload flipped the row: "Disabled" with an "Enable" toggle
  await expect(row1.locator('[data-testid="retention-policy-enabled-label"]')).toHaveText('Disabled');
  const reEnabledToggle = row1.locator('[data-testid="retention-policy-toggle"]');
  await expect(reEnabledToggle).toHaveText('Enable');
  await reEnabledToggle.click();
  await expect.poll(() => retentionPuts()).toHaveLength(3);
  expect(JSON.parse(retentionPuts()[2].body)).toEqual({ is_enabled: true });
  await expect(row1.locator('[data-testid="retention-policy-enabled-label"]')).toHaveText('Enabled');
  await expect(row1.locator('[data-testid="retention-policy-toggle"]')).toHaveText('Disable');

  // ------------------------------------------------------------------
  // Phase 5 — a failed edit PUT keeps the form open and shows
  // data-testid="retention-form-error" exactly as on create (the
  // response's detail); a subsequent valid save succeeds and closes it
  // ------------------------------------------------------------------
  putFail = true;
  await row2.locator('[data-testid="retention-policy-edit"]').click();
  const editForm2 = page.locator('[data-testid="retention-policy-form"]');
  await expect(editForm2).toBeVisible();
  // pre-filled with the disabled, class-scoped policy's values
  await expect(editForm2.locator('[data-testid="retention-form-name"]')).toHaveValue('Anonymize export PII');
  await expect(editForm2.locator('[data-testid="retention-form-scope"]')).toHaveValue('class');
  await expect(editForm2.locator('[data-testid="retention-form-dataset-wrap"]')).toBeHidden();
  await expect(editForm2.locator('[data-testid="retention-form-enabled"]')).not.toBeChecked();
  await editForm2.locator('[data-testid="retention-form-period"]').fill('45');
  await editForm2.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => retentionPuts()).toHaveLength(4);
  expect(retentionPuts()[3].url.endsWith('/api/retention-policies/pol-2')).toBe(true);
  const formError = page.locator('[data-testid="retention-form-error"]');
  await expect(formError).toBeVisible();
  await expect(formError).toHaveText('update blew up');
  await expect(editForm2).toBeVisible(); // the form stayed open
  // a subsequent valid save from the same open form succeeds and closes it
  putFail = false;
  await editForm2.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => retentionPuts()).toHaveLength(5);
  await expect(page.locator('[data-testid="retention-policy-form"]')).toHaveCount(0);
  await expect(
    row2.locator('td[data-testid="retention-policy-period"]')
  ).toHaveText('45 days');

  // ------------------------------------------------------------------
  // Phase 6 — a failed toggle shows "Could not update the policy." in
  // the row and neither selects it nor flips the label
  // ------------------------------------------------------------------
  putFail = true;
  await row1.locator('[data-testid="retention-policy-toggle"]').click();
  await expect.poll(() => retentionPuts()).toHaveLength(6);
  await expect(row1.locator('[data-testid="retention-policy-update-error"]')).toHaveText(
    'Could not update the policy.'
  );
  // the failed toggle neither selected the row nor flipped the state
  await expect(row1.locator('[data-testid="retention-policy-enabled-label"]')).toHaveText('Enabled');
  await expect(row1.locator('[data-testid="retention-policy-toggle"]')).toBeEnabled();
  await expect(row1).not.toHaveClass(/wh-retention-row-selected/);
  expect(await row1.getAttribute('data-selected')).toBeNull();
  putFail = false;

  // ------------------------------------------------------------------
  // Phase 7 — (review defect) Cancel and a failed delete restore the
  // row's full actions: the Edit button is never lost from the row
  // ------------------------------------------------------------------
  const row3 = page.locator('[data-testid="retention-policy-row"][data-id="pol-3"]');
  await expect(row3).toBeVisible();

  // Cancel: the confirm UI replaces the row's actions, and Cancel
  // restores BOTH the Edit and the Delete button.
  await row3.locator('[data-testid="retention-policy-delete"]').click();
  await expect(row3.locator('[data-testid="retention-policy-delete-text"]')).toHaveText(
    'Delete Legacy audit mask?'
  );
  await expect(row3.locator('[data-testid="retention-policy-edit"]')).toHaveCount(0);
  await row3.locator('[data-testid="retention-policy-delete-cancel"]').click();
  await expect(row3.locator('[data-testid="retention-policy-delete-text"]')).toHaveCount(0);
  await expect(row3.locator('[data-testid="retention-policy-delete"]')).toHaveCount(1);
  const editAfterCancel = row3.locator('[data-testid="retention-policy-edit"]');
  await expect(editAfterCancel).toHaveCount(1);
  await expect(editAfterCancel).toHaveText('Edit');
  await expect(editAfterCancel).toHaveAttribute('data-requires-role', 'admin');

  // A failed delete shows its row error and likewise keeps BOTH buttons.
  deleteFail = true;
  await row3.locator('[data-testid="retention-policy-delete"]').click();
  await row3.locator('[data-testid="retention-policy-delete-confirm"]').click();
  await expect(row3.locator('[data-testid="retention-policy-delete-error"]')).toHaveText(
    'Could not delete the policy.'
  );
  await expect(row3.locator('[data-testid="retention-policy-delete"]')).toHaveCount(1);
  const editAfterFailedDelete = row3.locator('[data-testid="retention-policy-edit"]');
  await expect(editAfterFailedDelete).toHaveCount(1);
  await expect(editAfterFailedDelete).toHaveAttribute('data-requires-role', 'admin');
  deleteFail = false;

  // ------------------------------------------------------------------
  // Phase 8 — (review defect) a policy whose table_class/action is not
  // in the fixed option list: the restored Edit opens the form pre-
  // filled with the policy's ACTUAL values (offered as options, not the
  // first option), and a save preserves them
  // ------------------------------------------------------------------
  await editAfterFailedDelete.click();
  const editForm3 = page.locator('[data-testid="retention-policy-form"]');
  await expect(editForm3).toBeVisible();
  await expect(editForm3.locator('[data-testid="retention-form-name"]')).toHaveValue('Legacy audit mask');
  // the out-of-list values are offered as options and selected ...
  const legacyClassSel = editForm3.locator('[data-testid="retention-form-table-class"]');
  await expect(legacyClassSel).toHaveValue('audit_legacy');
  await expect(legacyClassSel.locator('option[value="audit_legacy"]')).toHaveText('audit_legacy');
  const legacyActionSel = editForm3.locator('[data-testid="retention-form-action"]');
  await expect(legacyActionSel).toHaveValue('mask');
  await expect(legacyActionSel.locator('option[value="mask"]')).toHaveText('mask');
  // ... and the rest of the prefill is unchanged
  await expect(editForm3.locator('[data-testid="retention-form-period"]')).toHaveValue('7');
  await expect(editForm3.locator('[data-testid="retention-form-scope"]')).toHaveValue('class');
  await expect(editForm3.locator('[data-testid="retention-form-dataset-wrap"]')).toBeHidden();
  await expect(editForm3.locator('[data-testid="retention-form-enabled"]')).toBeChecked();
  // saving without changes sends one PUT preserving the actual values
  await editForm3.locator('[data-testid="retention-form-save"]').click();
  await expect.poll(() => retentionPuts()).toHaveLength(7);
  const legacyPut = retentionPuts()[6];
  expect(legacyPut.url.endsWith('/api/retention-policies/pol-3')).toBe(true);
  expect(JSON.parse(legacyPut.body)).toEqual({
    name: 'Legacy audit mask',
    table_class: 'audit_legacy',
    action: 'mask',
    retention_period_days: 7,
    scope: 'class',
    dataset_id: null,
    is_enabled: true,
  });
  // the form closed and the row reloaded with its values intact
  await expect(page.locator('[data-testid="retention-policy-form"]')).toHaveCount(0);
  await expect(row3.locator('td[data-testid="retention-policy-table-class"]')).toHaveText('audit_legacy');
  await expect(row3.locator('td[data-testid="retention-policy-action"]')).toHaveText('mask');

  // ------------------------------------------------------------------
  // Phase 9 — identity: a full reload booted the production way for a
  // role 'user' identity renders the page with no Edit or toggle
  // buttons — only the "Enabled"/"Disabled" text
  // ------------------------------------------------------------------
  meBody = USER_ME;
  meAuthorization.length = 0;
  // A fragment-only URL change would be a same-document navigation and
  // Auth.init() would not re-run; go through about:blank so this boot is a
  // full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=retention#access_token=user-token-699');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer user-token-699');
  // the page still renders its policies ...
  await expect(page.locator('[data-testid="retention-policy-table"]')).toBeVisible();
  const viewerRows = page.locator('[data-testid="retention-policy-row"]');
  await expect(viewerRows).toHaveCount(3);
  // ... but no admin-only control exists for the non-admin
  await expect(page.locator('[data-testid="retention-policy-edit"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-toggle"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-add-policy"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="retention-policy-delete"]')).toHaveCount(0);
  await expect(page.locator('[data-panel="retention"] [data-requires-role="admin"]')).toHaveCount(0);
  // ... and the Enabled/Disabled cell shows only the text
  await expect(
    viewerRows.nth(0).locator('td[data-testid="retention-policy-enabled"]')
  ).toHaveText('Enabled');
  await expect(
    viewerRows.nth(1).locator('td[data-testid="retention-policy-enabled"]')
  ).toHaveText('Disabled');
});
