const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue598 surgical', async ({ page }) => {
  let authRole = 'viewer';
  const postCalls = [];

  await page.route('**/api/**', async (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ json: { authEnabled: true, authMode: 'development' } });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({ json: { authenticated: true, user: { username: 'testuser', roles: [authRole] } } });
    }
    if (route.request().method() === 'POST' && url.includes('/api/load-sequences')) {
      postCalls.push(url);
      return route.fulfill({ json: { id: 2, name: 'New Seq' } });
    }
    if (url.includes('/api/load-sequences')) {
      return route.fulfill({ json: [{ id: 1, name: 'Test Seq' }] });
    }
    return route.fulfill({ status: 404, json: {} });
  });

  // --- Non-admin: create button absent from DOM, read-only content still renders ---
  await page.goto('/studio.html');
  await page.waitForSelector('[data-testid="sequence-row"]', { timeout: 5000 });

  const createBtnNonAdmin = await page.$('[data-testid="sequence-create"]');
  expect(createBtnNonAdmin).toBeNull();

  // Read-only row is still present for non-admin
  const rowNonAdmin = await page.$('[data-testid="sequence-row"]');
  expect(rowNonAdmin).not.toBeNull();

  // --- Admin: create button present and functional ---
  authRole = 'admin';
  await page.goto('/studio.html');
  await page.waitForSelector('[data-testid="sequence-row"]', { timeout: 5000 });

  const createBtnAdmin = await page.$('[data-testid="sequence-create"]');
  expect(createBtnAdmin).not.toBeNull();

  // Verify functional: type a name and click, assert POST to /load-sequences
  await page.fill('[data-testid="sequence-name-input"]', 'My New Seq');
  await createBtnAdmin.click();

  // After successful POST the app re-fetches and re-renders; wait for the row again
  await page.waitForSelector('[data-testid="sequence-row"]', { timeout: 5000 });

  expect(postCalls.length).toBe(1);
  expect(postCalls[0]).toContain('/api/load-sequences');
});
