const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue609 surgical', async ({ page }) => {
    let authRoles = ['viewer'];

    await page.route('**/api/**', async (route) => {
        const url = route.request().url();
        if (url.includes('/auth/config')) {
            return route.fulfill({ json: { authEnabled: true, authMode: 'development' } });
        }
        if (url.includes('/auth/me')) {
            return route.fulfill({ json: { authenticated: true, user: { username: 'testuser', roles: authRoles } } });
        }
        if (url.match(/\/api\/dashboard-items\/\d+\/data/)) {
            return route.fulfill({ json: { series: [{ label: 'x', value: 5 }], item_type: 'kpi' } });
        }
        if (url.includes('/api/dashboard-item-layouts')) {
            return route.fulfill({ json: [] });
        }
        if (url.includes('/api/dashboard-items')) {
            return route.fulfill({ json: [{ id: 10, dashboard_id: 1, title: 'Item A', item_type: 'kpi', position: 1 }] });
        }
        if (url.includes('/api/dashboards')) {
            return route.fulfill({ json: [{ id: 1, name: 'Test Dash', grid_columns: 12 }] });
        }
        if (url.includes('/api/suggestions')) {
            return route.fulfill({ json: [] });
        }
        if (url.includes('/api/pii-flags')) {
            return route.fulfill({ json: [] });
        }
        if (url.includes('/api/datasets')) {
            return route.fulfill({ json: [] });
        }
        if (url.includes('/api/discovered-fields')) {
            return route.fulfill({ json: [] });
        }
        return route.fulfill({ json: {} });
    });

    // --- Non-admin: layout controls must be absent from DOM ---
    authRoles = ['viewer'];
    await page.goto('/');
    await page.waitForSelector('[data-testid="chart-kpi"]');

    expect(await page.locator('[data-action="edit-layout"]').count()).toBe(0);
    expect(await page.locator('[data-action="save-layout"]').count()).toBe(0);
    expect(await page.locator('[data-action="cancel-layout"]').count()).toBe(0);

    // Read-only content still renders
    const itemTitle = await page.locator('[data-testid="dashboard-item"] .wh-title').first().textContent();
    expect(itemTitle).toBe('Item A');

    // --- Admin: edit-layout present, save/cancel appear in edit mode ---
    authRoles = ['admin'];
    await page.goto('/');
    await page.waitForSelector('[data-testid="chart-kpi"]');

    expect(await page.locator('[data-action="edit-layout"]').count()).toBe(1);
    expect(await page.locator('[data-action="save-layout"]').count()).toBe(0);
    expect(await page.locator('[data-action="cancel-layout"]').count()).toBe(0);

    // Enter edit mode — save/cancel appear as before
    await page.click('[data-action="edit-layout"]');
    await page.waitForSelector('[data-action="save-layout"]');

    expect(await page.locator('[data-action="save-layout"]').count()).toBe(1);
    expect(await page.locator('[data-action="cancel-layout"]').count()).toBe(1);

    // Cancel to restore terminal chart state (triggers _fillCharts)
    await page.click('[data-action="cancel-layout"]');
    await page.waitForSelector('[data-testid="chart-kpi"]');
});
