'use strict';

// Proof for issue #694 — the read-only "Audit history" admin panel on
// /studio.html (app/js/audit.js + the audit section in app/studio.html).
//
// Boots /studio.html?panel=audit with /api/auth/config and /api/auth/me
// mocked and every other /api/** request mocked (four events across two
// entity types, one with no actor username), and proves:
//   AC-1  the section <section class="wh-panel" data-panel="audit">
//         carries the "Audit history" heading and the module
//         app/js/audit.js defines const AuditView with an init() called
//         on Studio boot after Auth.init(); for an admin, init() calls
//         GET /api/audit?limit=100 through the existing API client and
//         renders, inside the element marked
//         data-requires-role="admin", a table of the events newest
//         timestamp first with the time, action, entity type, entity id,
//         the actor's username (the actor's actor_sub when there is no
//         username) and the details as compact "key: value" pairs; the
//         actor's email is never shown; with no events it shows "No
//         audit events yet."; a failed request shows "Could not load
//         audit history."
//   AC-2  for an admin, the select above the table lists "All entity
//         types" plus each distinct entity type in the loaded events;
//         choosing one shows only that type's events and choosing "All
//         entity types" shows them all again; nothing in the section
//         changes data (no write request in any phase)
//   AC-3  as an admin, the four mocked events render newest first with
//         their fields, no actor email appears anywhere in the page, the
//         no-username event shows its actor_sub, and the entity-type
//         select filters and resets; as a non-admin (role 'user') the
//         administrators-only text is shown, no element marked
//         data-requires-role="admin" is present and no request to
//         /api/audit was made; the empty and failed texts appear for
//         their mocked responses
//   AC-4  a crafted payload carrying script/img/svg markup in every
//         rendered field (details, actor_sub, entity type, entity id,
//         action, username) renders as inert literal text through
//         textContent — no injected script executes and no new <script>
//         element reaches the DOM
//   AC-5  the panel fails closed when the authentication state is
//         unavailable or the current user is not admin: the admin area
//         is not rendered, the section shows only the administrators-
//         only text, and no audit data is fetched or rendered
//   Identity  the criteria concern roles, so the proof also runs a
//         non-admin pass (role 'user') booted the production way: the
//         token in the URL hash (#access_token=...), /api/auth/config
//         and /api/auth/me mocked for that user, the hash token reaching
//         /api/auth/me as a Bearer header while the page still renders
//         with the admin-only control absent

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const AUTH_CONFIG = { authEnabled: true, authMode: 'development' };
const ADMIN_ME = {
  authenticated: true,
  user: { id: 1, username: 'admin', roles: ['admin'] },
};
const USER_ME = {
  authenticated: true,
  user: { id: 9, username: 'user', roles: ['user'] },
};

// Four audit events across two entity types, deliberately out of order in
// the mock payload (the panel must sort them newest-first).  The newest
// event (12:00) has no actor username — it must render its actor_sub.
// Every event carries an actor_email that must never reach the page.
const EVENTS = [
  {
    id: 1,
    entity_type: 'source',
    entity_id: 'src-1',
    action: 'update',
    actor_sub: 'sub-alice',
    actor_username: 'alice',
    actor_email: 'alice@example.com',
    actor_roles: '["admin"]',
    timestamp: '2026-10-01T10:00:00+00:00',
    details: { field: 'name', before: 'old', after: 'new' },
  },
  {
    id: 2,
    entity_type: 'retention_policy',
    entity_id: 'pol-7',
    action: 'create',
    actor_sub: 'sub-service-9',
    actor_username: null,
    actor_email: 'svc@example.com',
    actor_roles: null,
    timestamp: '2026-10-01T12:00:00+00:00',
    details: { name: 'purge-runs' },
  },
  {
    id: 3,
    entity_type: 'source',
    entity_id: 'src-2',
    action: 'delete',
    actor_sub: 'sub-bob',
    actor_username: 'bob',
    actor_email: 'bob@example.com',
    actor_roles: '["user"]',
    timestamp: '2026-10-01T09:00:00+00:00',
    details: {},
  },
  {
    id: 4,
    entity_type: 'retention_policy',
    entity_id: 'pol-3',
    action: 'delete',
    actor_sub: 'sub-carol',
    actor_username: 'carol',
    actor_email: 'carol@example.com',
    actor_roles: '["user"]',
    timestamp: '2026-10-01T11:00:00+00:00',
    details: { reason: 'duplicate' },
  },
];

// AC-4 — a crafted audit payload: markup in every rendered field.  Each
// marker (window.__auditXss) is set by exactly one injection vector; none
// of them may ever run.
const HOSTILE_EVENTS = [
  {
    id: 99,
    entity_type: '<script>window.__auditXss=1</script>evil-type',
    entity_id: '<img src=x onerror="window.__auditXss=2">',
    action: '<svg onload="window.__auditXss=3">update</svg>',
    actor_sub: 'sub-<b>bold</b>',
    actor_username: '<i>italic</i>',
    actor_email: 'evil@example.com',
    actor_roles: null,
    timestamp: '2026-10-02T00:00:00+00:00',
    details: { note: '<script>window.__auditXss=4</script>' },
  },
];

// Phase switches for the single mock.
let meBody = ADMIN_ME;
let auditMode = 'ok'; // 'ok' | 'empty' | 'error' | 'hostile'
let meAuthorization = [];
let auditRequests = [];
let writeRequests = [];

test('issue694 freeform', async ({ page }) => {
  await page.route('**/api/**', async (route) => {
    const request = route.request();
    const url = request.url();
    const method = request.method();
    if (method !== 'GET' && method !== 'HEAD') {
      writeRequests.push({ method, url });
    }

    if (url.includes('/api/auth/config')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(AUTH_CONFIG),
      });
    }
    if (url.includes('/api/auth/me')) {
      const auth = request.headers()['authorization'];
      if (auth) meAuthorization.push(auth);
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(meBody),
      });
    }
    if (new URL(url).pathname === '/api/audit') {
      if (method !== 'GET') {
        return route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ detail: 'no' }) });
      }
      auditRequests.push(url);
      if (auditMode === 'empty') {
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
      }
      if (auditMode === 'error') {
        return route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ detail: 'audit unavailable' }),
        });
      }
      if (auditMode === 'hostile') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(HOSTILE_EVENTS),
        });
      }
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(EVENTS),
      });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
  });

  // ------------------------------------------------------------------
  // Phase 1 — admin boot: the section carries the "Audit history"
  // heading, the module defines const AuditView with an init(), and the
  // events render newest first inside the admin-only area
  // ------------------------------------------------------------------
  await page.goto('/studio.html?panel=audit');

  // the module is loaded and defines const AuditView with an init()
  expect(await page.locator('script[src="js/audit.js"]').count()).toBe(1);
  expect(
    await page.evaluate(
      () => typeof AuditView !== 'undefined' && typeof AuditView.init === 'function'
    )
  ).toBe(true);

  const section = page.locator('[data-panel="audit"]');
  await expect(section).toBeVisible();
  await expect(section.locator('h2')).toHaveText('Audit history');

  // the table renders inside the element marked data-requires-role="admin"
  const adminArea = section.locator('[data-requires-role="admin"]');
  await expect(adminArea).toHaveCount(1);
  await expect(adminArea).toBeVisible();
  await expect(adminArea.locator('[data-testid="audit-table"]')).toHaveCount(1);

  // init() called GET /api/audit?limit=100 through the API client
  await expect.poll(() => auditRequests.length).toBe(1);
  expect(auditRequests[0]).toContain('/api/audit?limit=100');

  // one row per event, newest timestamp first (12:00, 11:00, 10:00, 09:00)
  const table = adminArea.locator('[data-testid="audit-table"]');
  await expect(table).toBeVisible();
  const rows = table.locator('[data-testid="audit-row"]');
  await expect(rows).toHaveCount(4);

  // newest first: the 12:00 create, which has no actor username, so its
  // actor_sub is shown
  const newest = rows.nth(0);
  await expect(newest.locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T12:00:00+00:00');
  await expect(newest.locator('[data-testid="audit-action"]')).toHaveText('create');
  await expect(newest.locator('[data-testid="audit-entity-type"]')).toHaveText('retention_policy');
  await expect(newest.locator('[data-testid="audit-entity-id"]')).toHaveText('pol-7');
  await expect(newest.locator('[data-testid="audit-actor"]')).toHaveText('sub-service-9');
  await expect(newest.locator('[data-testid="audit-details"]')).toHaveText('name: purge-runs');

  const second = rows.nth(1);
  await expect(second.locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T11:00:00+00:00');
  await expect(second.locator('[data-testid="audit-action"]')).toHaveText('delete');
  await expect(second.locator('[data-testid="audit-entity-type"]')).toHaveText('retention_policy');
  await expect(second.locator('[data-testid="audit-entity-id"]')).toHaveText('pol-3');
  await expect(second.locator('[data-testid="audit-actor"]')).toHaveText('carol');
  await expect(second.locator('[data-testid="audit-details"]')).toHaveText('reason: duplicate');

  const third = rows.nth(2);
  await expect(third.locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T10:00:00+00:00');
  await expect(third.locator('[data-testid="audit-action"]')).toHaveText('update');
  await expect(third.locator('[data-testid="audit-entity-type"]')).toHaveText('source');
  await expect(third.locator('[data-testid="audit-entity-id"]')).toHaveText('src-1');
  await expect(third.locator('[data-testid="audit-actor"]')).toHaveText('alice');
  await expect(third.locator('[data-testid="audit-details"]')).toHaveText('field: name, before: old, after: new');

  // oldest last: the 09:00 delete, empty details render empty
  const oldest = rows.nth(3);
  await expect(oldest.locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T09:00:00+00:00');
  await expect(oldest.locator('[data-testid="audit-action"]')).toHaveText('delete');
  await expect(oldest.locator('[data-testid="audit-entity-type"]')).toHaveText('source');
  await expect(oldest.locator('[data-testid="audit-entity-id"]')).toHaveText('src-2');
  await expect(oldest.locator('[data-testid="audit-actor"]')).toHaveText('bob');
  expect((await oldest.locator('[data-testid="audit-details"]').innerText()).trim()).toBe('');

  // the actor's email is never shown — not in the page text and not in
  // any attribute (the whole serialized DOM is checked)
  const bodyText = await page.locator('body').innerText();
  expect(bodyText).not.toContain('example.com');
  const dom = await page.evaluate(() => document.documentElement.outerHTML);
  expect(dom).not.toContain('example.com');

  const staticScriptCount = await page.evaluate(() => document.querySelectorAll('script').length);

  // ------------------------------------------------------------------
  // Phase 2 — AC-2: the select above the table lists "All entity types"
  // plus each distinct entity type; choosing one filters, choosing "All
  // entity types" resets
  // ------------------------------------------------------------------
  const select = adminArea.locator('[data-testid="audit-entity-type-filter"]');
  await expect(select).toBeVisible();
  const selectBox = await select.boundingBox();
  const tableBox = await table.boundingBox();
  expect(selectBox.y).toBeLessThan(tableBox.y);

  await expect(select.locator('option')).toHaveText([
    'All entity types',
    'retention_policy',
    'source',
  ]);

  await select.selectOption({ label: 'source' });
  await expect(rows).toHaveCount(2);
  await expect(rows.nth(0).locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T10:00:00+00:00');
  await expect(rows.nth(1).locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T09:00:00+00:00');

  await select.selectOption({ label: 'retention_policy' });
  await expect(rows).toHaveCount(2);
  await expect(rows.nth(0).locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T12:00:00+00:00');
  await expect(rows.nth(1).locator('[data-testid="audit-time"]')).toHaveText('2026-10-01T11:00:00+00:00');

  // "All entity types" shows them all again
  await select.selectOption({ index: 0 });
  await expect(rows).toHaveCount(4);

  // ------------------------------------------------------------------
  // Phase 3 — AC-1/AC-3: an admin boot with an empty list shows
  // "No audit events yet."
  // ------------------------------------------------------------------
  auditMode = 'empty';
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit');
  await expect(page.locator('[data-testid="audit-empty"]')).toHaveText('No audit events yet.');
  await expect(page.locator('[data-testid="audit-table"]')).toHaveCount(0);

  // ------------------------------------------------------------------
  // Phase 4 — AC-1/AC-3: an admin boot with a failed request shows
  // "Could not load audit history."
  // ------------------------------------------------------------------
  auditMode = 'error';
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit');
  await expect(page.locator('[data-testid="audit-error"]')).toHaveText('Could not load audit history.');
  await expect(page.locator('[data-testid="audit-table"]')).toHaveCount(0);

  // ------------------------------------------------------------------
  // Phase 5 — AC-4: a crafted payload renders as inert literal text —
  // no injected script executes and no new <script> element appears
  // ------------------------------------------------------------------
  auditMode = 'hostile';
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit');
  const hostileRows = page.locator('[data-testid="audit-row"]');
  await expect(hostileRows).toHaveCount(1);
  await expect(hostileRows.locator('[data-testid="audit-entity-type"]')).toHaveText(
    '<script>window.__auditXss=1</script>evil-type'
  );
  await expect(hostileRows.locator('[data-testid="audit-entity-id"]')).toHaveText(
    '<img src=x onerror="window.__auditXss=2">'
  );
  await expect(hostileRows.locator('[data-testid="audit-action"]')).toHaveText(
    '<svg onload="window.__auditXss=3">update</svg>'
  );
  await expect(hostileRows.locator('[data-testid="audit-actor"]')).toHaveText('<i>italic</i>');
  await expect(hostileRows.locator('[data-testid="audit-details"]')).toHaveText(
    'note: <script>window.__auditXss=4</script>'
  );
  // none of the injected payloads ran ...
  expect(await page.evaluate(() => window.__auditXss)).toBeUndefined();
  // ... and no new <script> element reached the DOM
  expect(await page.evaluate(() => document.querySelectorAll('script').length)).toBe(staticScriptCount);
  // the actor's email still never reaches the page
  expect(await page.evaluate(() => document.documentElement.outerHTML)).not.toContain('example.com');

  // ------------------------------------------------------------------
  // Phase 6 — identity / AC-5: a user with roles: ["user"] booted the
  // production way (token in the URL hash, /api/auth/config and
  // /api/auth/me mocked for that user) sees the page render with the
  // section showing only the administrators-only text, no
  // data-requires-role="admin" element present, and no request to
  // /api/audit made
  // ------------------------------------------------------------------
  auditMode = 'ok';
  meBody = USER_ME;
  meAuthorization.length = 0;
  auditRequests.length = 0;
  // A fragment-only URL change would be a same-document navigation and
  // Auth.init() would not re-run; go through about:blank so this boot is
  // a full page load, the production way.
  await page.goto('about:blank');
  await page.goto('/studio.html?panel=audit#access_token=user-token-694');
  // the hash token was picked up the production way and sent on /auth/me
  await expect.poll(() => meAuthorization).toContain('Bearer user-token-694');
  // the page still renders its other panels ...
  await expect(page.locator('[data-panel="sources"]')).toBeVisible();

  // ... the section shows only the administrators-only text ...
  const auditSection = page.locator('[data-panel="audit"]');
  await expect(auditSection).toBeVisible();
  await expect(auditSection.locator('[data-testid="audit-notice"]')).toHaveText(
    'Audit history is available to administrators.'
  );
  expect((await auditSection.innerText()).trim()).toBe(
    'Audit history is available to administrators.'
  );

  // ... no element marked data-requires-role="admin" is present (the
  // audit admin area left the DOM; every other Studio module hides its
  // admin controls for a non-admin too) ...
  await expect(auditSection.locator('[data-requires-role="admin"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="audit-admin"]')).toHaveCount(0);
  await expect(page.locator('[data-requires-role="admin"]')).toHaveCount(0);

  // ... nothing was fetched and nothing admin was rendered ...
  await expect(page.locator('[data-testid="audit-table"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="audit-entity-type-filter"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="audit-empty"]')).toHaveCount(0);
  await expect(page.locator('[data-testid="audit-error"]')).toHaveCount(0);
  expect(auditRequests).toHaveLength(0);

  // the section never wrote data in any phase
  expect(writeRequests).toHaveLength(0);
});
