const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue597 surgical', async ({ page }) => {
  const nonAdminMe = { authenticated: true, user: { username: 'viewer1', roles: ['viewer'] } };
  const adminMe = { authenticated: true, user: { username: 'admin1', roles: ['admin', 'viewer'] } };

  let currentMe = nonAdminMe;

  await page.route('**/api/**', async (route) => {
    const url = route.request().url();
    if (url.includes('/api/auth/config')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ authEnabled: true, authMode: 'development' }) });
    }
    if (url.includes('/api/auth/me')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(currentMe) });
    }
    if (url.includes('/api/process-definitions')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: '1', name: 'Test Proc', process_key: 'tp', version: 1, status: 'active' }]) });
    }
    if (url.includes('/api/process-steps')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
    }
    if (url.includes('/api/sequence-flows')) {
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([]) });
  });

  // --- Non-admin pass ---
  await page.goto('/studio.html');

  // Wait for wizard init to complete (definition cards rendered into container)
  await page.waitForSelector('#wizard-definitions .wizard-card', { timeout: 5000 });

  // Verify Auth state is an authenticated non-admin (not null / not failed auth)
  const viewerAuth = await page.evaluate(() => ({
    isAuthenticated: Auth.isAuthenticated(),
    isAdmin: Auth.isAdmin(),
    username: Auth.getCurrentUser() ? Auth.getCurrentUser().username : null,
  }));
  expect(viewerAuth.isAuthenticated).toBe(true);
  expect(viewerAuth.isAdmin).toBe(false);
  expect(viewerAuth.username).toBe('viewer1');

  // All three create buttons must be ABSENT from the DOM (not hidden, not disabled)
  await expect(page.locator('#wizard-create-def-btn')).toHaveCount(0);
  await expect(page.locator('#wizard-create-step-btn')).toHaveCount(0);
  await expect(page.locator('#wizard-create-flow-btn')).toHaveCount(0);

  // Read-only listing still rendered (the definition card is present)
  await expect(page.locator('#wizard-definitions .wizard-card')).toHaveCount(1);

  // --- Admin pass (fresh navigation re-initializes all JS modules) ---
  currentMe = adminMe;

  await page.goto('/studio.html');

  await page.waitForSelector('#wizard-definitions .wizard-card', { timeout: 5000 });

  // Verify Auth state is an authenticated admin
  const adminAuth = await page.evaluate(() => ({
    isAuthenticated: Auth.isAuthenticated(),
    isAdmin: Auth.isAdmin(),
    username: Auth.getCurrentUser() ? Auth.getCurrentUser().username : null,
  }));
  expect(adminAuth.isAuthenticated).toBe(true);
  expect(adminAuth.isAdmin).toBe(true);
  expect(adminAuth.username).toBe('admin1');

  // All three create buttons must be PRESENT and enabled in the DOM
  const defBtn = page.locator('#wizard-create-def-btn');
  const stepBtn = page.locator('#wizard-create-step-btn');
  const flowBtn = page.locator('#wizard-create-flow-btn');

  await expect(defBtn).toHaveCount(1);
  await expect(stepBtn).toHaveCount(1);
  await expect(flowBtn).toHaveCount(1);
  await expect(defBtn).toBeEnabled();
  await expect(stepBtn).toBeEnabled();
  await expect(flowBtn).toBeEnabled();
});
