const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue613 freeform', async ({ page }) => {
  // Prove the admin-identity-establishment pattern that all five surgical specs rely on:
  //   1. Mock /api/auth/config and /api/auth/me via page.route BEFORE page.goto,
  //      registered AFTER a catch-all (Playwright checks most-recently-registered first).
  //   2. The page's own boot-time Auth.init() consumes the mocked /api/auth/me.
  //   3. Wait for Auth.isAdmin() === true in page scope (bare name, not window.Auth).
  //   4. Verify admin state via page.evaluate — no post-load Auth.init() call needed.

  // Catch-all registered FIRST so it never shadows the specific mocks below.
  await page.route('**/api/**', async (route) => {
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({}) });
  });

  // Specific auth routes registered AFTER the catch-all (checked first by Playwright).
  await page.route('/api/auth/config', async (route) => {
    return route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ authEnabled: true, authMode: 'development' }),
    });
  });

  await page.route('/api/auth/me', async (route) => {
    return route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        authenticated: true,
        user: { username: 'admin', sub: 'admin', roles: ['admin'] },
      }),
    });
  });

  await page.goto('/');

  // The page's own boot-time Auth.init() (via Warehouse._ensureAuth) consumes the mocked
  // /api/auth/me. Wait for that to resolve into an admin state — no explicit Auth.init() call.
  await page.waitForFunction(() => Auth.isAdmin() === true);

  // Verify admin identity is established in page scope via bare-name access.
  const isAdmin = await page.evaluate(() => Auth.isAdmin());
  expect(isAdmin).toBe(true);

  // Verify the user object carries the admin role (not just a boolean shortcut).
  const userRoles = await page.evaluate(() => {
    const u = Auth.getCurrentUser();
    return u ? u.roles : null;
  });
  expect(userRoles).toContain('admin');

  // Prove that a temporary ApiClient.post swap does NOT intercept /api/auth/me or replace Auth.
  // The auth state was already established at boot; swapping post now must not disturb it.
  const swapResult = await page.evaluate(async () => {
    const origPost = ApiClient.post;
    let interceptedAuthMe = false;
    ApiClient.post = (path, body) => {
      if (String(path).includes('/auth/me')) interceptedAuthMe = true;
      return Promise.resolve({ ok: true, data: {} });
    };

    // Trigger a non-auth POST through the swapped method.
    await ApiClient.post('/dashboard-item-layouts', { dashboard_item_id: 'x' });

    const authStillAdmin = Auth.isAdmin();
    const authModuleIntact = typeof Auth.init === 'function' && typeof Auth.getCurrentUser === 'function';

    ApiClient.post = origPost;

    return { interceptedAuthMe, authStillAdmin, authModuleIntact };
  });

  expect(swapResult.interceptedAuthMe).toBe(false);
  expect(swapResult.authStillAdmin).toBe(true);
  expect(swapResult.authModuleIntact).toBe(true);
});
