// GENERATED by CodeAgent (frontend_recipe.build_pw_config) — the engine rewrites
// this file on every frontend build; change the generator, not this copy.
const base = process.env.BASE_URL || 'http://127.0.0.1:8080';
module.exports = {
    testDir: '.',
    reporter: [['junit', { outputFile: 'report.xml' }], ['list']],
    use: { baseURL: base },
    ...(process.env.BASE_URL ? {} : {
        webServer: {
            command: 'python3 -m http.server 8080 --bind 127.0.0.1 --directory ..',
            url: 'http://127.0.0.1:8080/',
            reuseExistingServer: true,
            timeout: 30000,
        },
    }),
};
