// Served-app Playwright spec (no backend): the schema-tier suggestion loop on /studio.html.
// Every /api/** endpoint the page needs is mocked with page.route BEFORE page.goto, so the spec
// never creates data through the request fixture or a live API — it drives only the DOM: the
// suggestion card on /studio.html, its accept and dismiss buttons, and the dashboard item on /
// rendered from the mocked dashboards and dashboard-items. The mocked GET /api/suggestions is
// stateful: after the POST to /api/suggestions/{id}/accept or /dismiss it no longer lists that id,
// because the inbox re-renders from that list after every action (Warehouse.accept calls refresh).
const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


const BASE = (process.env.BASE_URL || 'http://localhost:8080').replace(/\/+$/, '');
const TOKEN = 'dev-secret-token:admin';
const MARK = `FE-SUG-${Date.now()}`; // unique per run so assertions never collide

const ACCEPT_ID = 'sug-572-accept';
const DISMISS_ID = 'sug-572-dismiss';
const DASHBOARD_ID = 'dash-572';
const ITEM_ID = 'item-572-accept';
const ACCEPT_TITLE = `${MARK} Orders by ShipCountry`;
const DISMISS_TITLE = `${MARK} Total Freight`;

// Non-admin identity for the viewer pass (the criteria concern roles): a
// role 'user' identity booted the production way — the token in the URL
// hash as #access_token=..., /api/auth/config and /api/auth/me mocked for
// that user — proves the inbox still renders (and still works) while the
// admin-only controls are absent.
const AUTH_CONFIG = { auth_mode: 'development' };
const VIEWER_ME = { authenticated: true, user: { id: 9, username: 'user', roles: ['user'] } };
const VIEWER_TOKEN = 'viewer-token-572-sug';

// Boot the page the production way for a given identity: /api/auth/config
// and /api/auth/me mocked for `me`, the same stateful suggestion inbox as
// installRoutes (accept/dismiss remove the acted id), every other /api/**
// an empty list, and the token riding the URL hash fragment
// (#access_token=...).  The boot proves the token was picked up the
// production way: Auth.init() migrates it into sessionStorage and it
// arrives as the Authorization header on /api/auth/me.
async function bootAs(page, me, token, url) {
    const meAuthorizations = [];
    // Stateful suggestion inbox: starts with two cards; accept/dismiss remove the acted id.
    const inbox = new Set([ACCEPT_ID, DISMISS_ID]);

    await page.unrouteAll();
    await page.route('**/api/**', (route) => {
        const request = route.request();
        const reqUrl = request.url();
        if (reqUrl.includes('/api/auth/config')) {
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(AUTH_CONFIG) });
        }
        if (reqUrl.includes('/api/auth/me')) {
            const auth = request.headers()['authorization'];
            if (auth) meAuthorizations.push(auth);
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(me) });
        }
        if (reqUrl.includes(`/api/suggestions/${ACCEPT_ID}/accept`)) {
            inbox.delete(ACCEPT_ID);
            return route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({ id: ACCEPT_ID, status: 'accepted' }),
            });
        }
        if (reqUrl.includes('/api/suggestions')) {
            const body = [ACCEPT_ID, DISMISS_ID]
                .filter((id) => inbox.has(id))
                .map((id) => ({
                    id,
                    name: id === ACCEPT_ID ? ACCEPT_TITLE : DISMISS_TITLE,
                    title: id === ACCEPT_ID ? ACCEPT_TITLE : DISMISS_TITLE,
                    item_type: id === ACCEPT_ID ? 'bar' : 'kpi',
                    aggregation: id === ACCEPT_ID ? 'count' : 'sum',
                    status: 'suggested',
                    strategy: 'schema-only',
                    score: id === ACCEPT_ID ? 0.55 : 0.70,
                }));
            return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
        }
        return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    });
    await page.goto(url + '#access_token=' + encodeURIComponent(token));
    await expect.poll(() => meAuthorizations).toContain('Bearer ' + token);
}

async function installRoutes(page) {
    // Stateful suggestion inbox: starts with two cards; accept/dismiss remove the acted id.
    const inbox = new Set([ACCEPT_ID, DISMISS_ID]);
    // Stateful dashboard-items: the item only appears after a genuine accept.
    const dashboardItems = [];

    const rows = [
        { id: ACCEPT_ID, title: ACCEPT_TITLE, item_type: 'bar', aggregation: 'count', score: 0.55 },
        { id: DISMISS_ID, title: DISMISS_TITLE, item_type: 'kpi', aggregation: 'sum', score: 0.70 },
    ];

    await page.route(`${BASE}/api/suggestions`, (route) => {
        const body = rows
            .filter((r) => inbox.has(r.id))
            .map((r) => ({
                id: r.id,
                name: r.title,
                title: r.title,
                item_type: r.item_type,
                aggregation: r.aggregation,
                status: 'suggested',
                strategy: 'schema-only',
                score: r.score,
            }));
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
    });

    await page.route(`${BASE}/api/suggestions/${ACCEPT_ID}/accept`, (route) => {
        inbox.delete(ACCEPT_ID);
        dashboardItems.push({
            id: ITEM_ID,
            dashboard_id: DASHBOARD_ID,
            suggestion_id: ACCEPT_ID,
            name: ACCEPT_TITLE,
            title: ACCEPT_TITLE,
            item_type: 'bar',
            aggregation: 'count',
        });
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ id: ACCEPT_ID, status: 'accepted' }),
        });
    });

    await page.route(`${BASE}/api/suggestions/${DISMISS_ID}/dismiss`, (route) => {
        inbox.delete(DISMISS_ID);
        // Dismiss does NOT add the item to any dashboard.
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ id: DISMISS_ID, status: 'dismissed' }),
        });
    });

    await page.route(`${BASE}/api/dashboards`, (route) => {
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify([{ id: DASHBOARD_ID, name: 'Operations', title: 'Operations' }]),
        });
    });

    await page.route(`${BASE}/api/dashboard-items`, (route) => {
        route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(dashboardItems) });
    });

    // Item data endpoint: the chart fill resolves to a terminal state (a rendered KPI value).
    await page.route(`${BASE}/api/dashboard-items/${ITEM_ID}/data`, (route) => {
        route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({ value: 42, label: 'Orders' }),
        });
    });
}

test('inbox renders suggestions; accept lands one on a dashboard; dismiss removes one', async ({ page }) => {
    await installRoutes(page);
    await page.addInitScript((t) => { window.sessionStorage.setItem('aicrm_token', t); }, TOKEN);

    // Act on the inbox on the studio page.
    await page.goto('/studio.html?panel=suggestions');
    const inbox = page.getByTestId('inbox');
    await expect(inbox.getByText(ACCEPT_TITLE)).toBeVisible();
    await expect(inbox.getByText(DISMISS_TITLE)).toBeVisible();

    // Accept -> the card leaves the inbox (the mocked list no longer returns it) and the item
    // lands on a dashboard, rendered from the mocked dashboard-items on /.
    await page.locator(`[data-testid="suggestion"][data-id="${ACCEPT_ID}"] [data-action="accept"]`).click();
    await expect(page.locator(`[data-testid="suggestion"][data-id="${ACCEPT_ID}"]`)).toHaveCount(0);

    await page.goto('/');
    const item = page.locator('[data-testid="dashboard-item"]', { hasText: ACCEPT_TITLE });
    await expect(item).toBeVisible();
    const chart = item.getByTestId('chart');
    await expect(chart).toBeVisible();

    // The fill must terminate: a rendered chart (svg / kpi / value list) or a non-empty
    // explanatory note — never left on the transient "Loading data…" placeholder.
    await expect
        .poll(async () => {
            if (await chart.locator('[data-testid="chart-svg"], [data-testid="chart-kpi"]').count()) {
                return 'rendered';
            }
            const notes = await chart.locator('[data-testid="chart-note"]').allTextContents();
            if (notes.length && notes[0].trim() && !notes[0].startsWith('Loading')) return 'note';
            return 'pending';
        }, { timeout: 10000 })
        .not.toBe('pending');

    // Dismiss -> the card leaves the inbox.
    await page.goto('/studio.html?panel=suggestions');
    await page.locator(`[data-testid="suggestion"][data-id="${DISMISS_ID}"] [data-action="dismiss"]`).click();
    await expect(page.locator(`[data-testid="suggestion"][data-id="${DISMISS_ID}"]`)).toHaveCount(0);
});

test('inbox renders suggestions; accept lands one on a dashboard; dismiss removes one (viewer)', async ({ page }) => {
    // Non-admin pass: boot the production way as a role 'user' identity
    // (the token in the URL hash) and prove the inbox still renders while
    // the admin-only controls are absent.
    await bootAs(page, VIEWER_ME, VIEWER_TOKEN, '/studio.html?panel=suggestions');

    // The page renders for a non-admin: both suggestion cards show...
    await expect(page.locator('.aidw-page-title')).toHaveText('Studio · Suggestions');
    await expect(page.locator(`[data-testid="suggestion"][data-id="${ACCEPT_ID}"]`)).toBeVisible();
    await expect(page.locator(`[data-testid="suggestion"][data-id="${DISMISS_ID}"]`)).toBeVisible();
    await expect(page.locator('[data-testid="sidebar"] [data-testid="auth-status"]')).toHaveText('Signed in · user');

    // ...and the inbox still works for the viewer (accept is not an
    // admin-only control): the acted card leaves the inbox.
    await page.locator(`[data-testid="suggestion"][data-id="${ACCEPT_ID}"] [data-action="accept"]`).click();
    await expect(page.locator(`[data-testid="suggestion"][data-id="${ACCEPT_ID}"]`)).toHaveCount(0);

    // The admin-only controls are absent: the role-gated Feed keys nav item
    // leaves the DOM, the Feed keys section is removed by its module, and
    // the admin-only source form is gone.
    await expect(page.locator('.aidw-nav-item[data-nav-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="sidebar-nav"] [data-requires-role="admin"]')).toHaveCount(0);
    await expect(page.locator('[data-panel="feedkeys"]')).toHaveCount(0);
    await expect(page.locator('#source-form')).toHaveCount(0);
});
